<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
require_once __DIR__.'/db.php';
admin_require_auth();
date_default_timezone_set('Asia/Karachi');

function aij(array $value,int $code=200):never{http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function ain($value):string{return strtolower(trim((string)$value));}
function ait(array $row,array $keys,string $fallback=''):string{foreach($keys as$key){$value=$row[$key]??null;if(is_scalar($value)&&trim((string)$value)!=='')return trim((string)$value);if(is_array($value)){foreach(['address','name','label','formattedAddress']as$child)if(isset($value[$child])&&trim((string)$value[$child])!=='')return trim((string)$value[$child]);}}return $fallback;}
function aib($value):bool{return filter_var($value,FILTER_VALIDATE_BOOLEAN)||$value===1||$value==='1';}
function aim(array $row,array $keys):?float{foreach($keys as$key)if(isset($row[$key])&&is_numeric($row[$key])){$value=(float)$row[$key];if(is_finite($value)&&$value>=0)return round($value,2);}return null;}
function aid($value):?DateTimeImmutable{try{if($value instanceof \Google\Cloud\Core\Timestamp)$value=$value->get();if($value instanceof DateTimeInterface)return(new DateTimeImmutable($value->format(DATE_ATOM)))->setTimezone(new DateTimeZone('Asia/Karachi'));if(is_numeric($value)){$number=(float)$value;if($number>9999999999)$number/=1000;return(new DateTimeImmutable('@'.(string)(int)$number))->setTimezone(new DateTimeZone('Asia/Karachi'));}if(is_string($value)&&trim($value)!=='')return(new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Asia/Karachi'));}catch(Throwable){}return null;}
function ais($value):string{$status=ain($value);if(in_array($status,['completed','ride_completed','finished','success','successful'],true))return'completed';if(in_array($status,['cancelled','canceled','rejected','declined','expired','no_driver_found'],true))return$status==='expired'||$status==='no_driver_found'?'expired':'cancelled';if(in_array($status,['accepted','assigned','driver_assigned','confirmed','driver_arriving','arriving','arrived','started','ride_started','in_progress','ongoing','active','on_trip'],true))return'active';return'waiting';}
function aitype(array $row):string{$type=ain($row['rideType']??$row['bookingType']??$row['requestType']??$row['serviceType']??'');if(aib($row['isCarpool']??false)||aib($row['sharedRide']??false)||str_contains($type,'carpool')||str_contains($type,'shared'))return'carpool';if(aib($row['isScheduled']??false)||isset($row['scheduledAt'])||isset($row['scheduledDateTime'])||str_contains($type,'sched')||$type==='advance'||$type==='prebooked')return'scheduled';return'instant';}
function aiplatform(array $row,string $collection):string{$value=ain($row['sourcePlatform']??$row['source']??$row['platform']??$row['createdFrom']??'');if(str_contains($value,'passenger')&&str_contains($value,'web'))return'passenger_website';if(str_contains($value,'passenger')&&(str_contains($value,'app')||str_contains($value,'mobile')))return'passenger_app';if(str_contains($value,'driver')&&str_contains($value,'web'))return'driver_website';if(str_contains($value,'driver')&&(str_contains($value,'app')||str_contains($value,'mobile')))return'driver_app';if(in_array($value,['web','website','passenger_web'],true))return'passenger_website';if(in_array($value,['mobile','app','android','ios'],true))return'passenger_app';return'unknown';}
function aiplatform_label(string $value):string{return match($value){'passenger_app'=>'Passenger Mobile App','passenger_website'=>'Passenger Website','driver_app'=>'Driver Mobile App','driver_website'=>'Driver Website',default=>'Source unavailable'};}
function aireal(array $row):bool{$text=ain(ait($row,['rideId','bookingId','requestId','uid']).' '.ait($row,['name','email','rideCode']));return!aib($row['isDemo']??false)&&!aib($row['isTest']??false)&&!aib($row['isDeleted']??$row['deleted']??false)&&!str_contains($text,'demo')&&!str_contains($text,'test');}
function aiarea(string $address):string{$address=trim($address);if($address==='')return'Location unavailable';$parts=array_values(array_filter(array_map('trim',explode(',',$address))));$generic=['karachi','sindh','pakistan'];foreach($parts as$part){$clean=preg_replace('/\s+/', ' ', $part)??$part;if(strlen($clean)>=3&&!in_array(ain($clean),$generic,true)&&!preg_match('/^-?\d+(\.\d+)?$/',$clean))return ucwords(strtolower($clean));}return ucwords(strtolower($parts[0]??$address));}
function aiavg(array $values):?float{return$values?round(array_sum($values)/count($values),2):null;}
function aipercent(int|float $part,int|float $total):?float{return$total>0?round(($part/$total)*100,1):null;}
function aitrend(float $current,float $previous):array{if($current<=0||$previous<=0)return['current'=>$current,'previous'=>$previous,'change'=>null,'label'=>'No trend data'];$change=round((($current-$previous)/$previous)*100,1);return['current'=>$current,'previous'=>$previous,'change'=>$change,'label'=>$change>0?'Increasing':($change<0?'Decreasing':'No change')];}
function airide(array $row,string $collection):?array{if(!aireal($row))return null;$id=ait($row,['rideId','bookingId','requestId','uid']);if($id==='')return null;$status=ais($row['status']??$row['rideStatus']??$row['bookingStatus']??$row['requestStatus']??'');$created=aid($row['createdAt']??$row['requestedAt']??$row['bookingTime']??null);$completed=aid($row['completedAt']??$row['rideCompletedAt']??$row['endedAt']??null);$cancelled=aid($row['cancelledAt']??$row['canceledAt']??null);$source=aiplatform($row,$collection);$updateSource=aiplatform(['sourcePlatform'=>$row['lastUpdatedSource']??$row['updatedSource']??$row['driverPlatform']??$row['completedSource']??''],$collection);return['id'=>$id,'collection'=>$collection,'status'=>$status,'raw_status'=>ain($row['status']??$row['rideStatus']??$row['bookingStatus']??''),'type'=>aitype($row),'vehicle'=>ain($row['vehicleType']??$row['requestedVehicleType']??$row['driverVehicleType']??'unknown')?:'unknown','passenger_id'=>ait($row,['passengerId','passengerUid','userId']),'driver_id'=>ait($row,['assignedDriverId','driverId','driverUid']),'pickup'=>ait($row,['pickupAddress','pickupLocation','pickup']),'dropoff'=>ait($row,['destinationAddress','dropoffAddress','dropoffLocation','dropoff','destination']),'fare'=>aim($row,['finalFare','totalFare','acceptedFare','agreedFare','fare']),'original_fare'=>aim($row,['originalFare','estimatedFare','systemFare']),'shared_fare'=>aim($row,['sharedFare','carpoolFare','discountedFare']),'created'=>$created,'completed'=>$completed,'cancelled'=>$cancelled,'event_time'=>$completed??$cancelled??$created,'source'=>$source,'update_source'=>$updateSource,'cancelled_by'=>ain($row['cancelledBy']??$row['canceledBy']??''),'cancellation_reason'=>ait($row,['cancellationReason','cancelReason','reason']),'payment_status'=>ain($row['paymentStatus']??''),'payment_method'=>ain($row['paymentMethod']??''),'raw'=>$row];}

try{
  $now=new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi'));$date=ain($_GET['date']??'30d');$type=ain($_GET['type']??'all');$vehicle=ain($_GET['vehicle']??'all');$source=ain($_GET['source']??'all');$status=ain($_GET['status']??'all');
  $cacheKey=hash('sha256',implode('|',[$date,$type,$vehicle,$source,$status]));$cached=$_SESSION['ai_analytics_cache'][$cacheKey]??null;if(ain($_GET['export']??'')===''&&is_array($cached)&&time()-(int)($cached['time']??0)<45&&is_array($cached['payload']??null))aij($cached['payload']);
  $from=match($date){'today'=>$now->setTime(0,0),'7d'=>$now->modify('-6 days')->setTime(0,0),'30d'=>$now->modify('-29 days')->setTime(0,0),'month'=>$now->modify('first day of this month')->setTime(0,0),'year'=>$now->setDate((int)$now->format('Y'),1,1)->setTime(0,0),default=>null};
  $span=$from?max(86400,$now->getTimestamp()-$from->getTimestamp()+1):null;$previousFrom=$span?$from->modify('-'.$span.' seconds'):null;$previousTo=$from;
  $map=[];$collections=[];foreach(['rides']as$collection){$records=admin_list_recent_collection($collection,1000,'createdAt');if($records)$collections[]=$collection;foreach($records as$row){$ride=airide($row,$collection);if(!$ride)continue;$old=$map[$ride['id']]??null;$newStamp=$ride['event_time']?->getTimestamp()??0;$oldStamp=$old&&$old['event_time']?$old['event_time']->getTimestamp():0;if(!$old||$newStamp>=$oldStamp)$map[$ride['id']]=$ride;}}
  $all=array_values($map);$matches=static function(array $ride,?DateTimeImmutable $start,?DateTimeImmutable $end=null)use($type,$vehicle,$source,$status):bool{if($type!=='all'&&$ride['type']!==$type)return false;if($vehicle!=='all'&&!str_contains($ride['vehicle'],$vehicle))return false;if($source!=='all'&&$ride['source']!==$source&&$ride['update_source']!==$source)return false;if($status!=='all'&&$ride['status']!==$status)return false;$time=$ride['event_time'];if($start&&(!$time||$time<$start))return false;if($end&&$time&&$time>=$end)return false;return true;};
  $rides=array_values(array_filter($all,fn($ride)=>$matches($ride,$from)));$previous=$previousFrom?array_values(array_filter($all,fn($ride)=>$matches($ride,$previousFrom,$previousTo))):[];
  $drivers=[];foreach(admin_list_collection('drivers',500)as$row){$id=ait($row,['uid','driverId']);if($id!=='')$drivers[$id]=$row;}
  $payments=[];foreach(admin_list_collection('payments',1000)as$row){if(!aireal($row))continue;$id=ait($row,['rideId','bookingId','requestId','uid']);if($id!=='')$payments[$id]=$row;}
  $ratings=[];$ratingByDriver=[];foreach(['ratings','rideReviews']as$collection)foreach(admin_list_recent_collection($collection,700,'createdAt')as$row){if(!aireal($row))continue;$value=aim($row,['rating','driverRating','stars','score']);if($value===null||$value<1||$value>5)continue;$driverId=ait($row,['driverId','driverUid','ratedUserId','revieweeId']);$role=ain($row['revieweeRole']??$row['ratedRole']??'driver');if($driverId===''||($role!==''&&!in_array($role,['driver','female_driver'],true)))continue;$rideId=ait($row,['rideId','bookingId','requestId']);$key=ain($rideId.'|'.$driverId.'|'.ait($row,['passengerId','reviewerId','ratedBy','uid']));$ratings[$key]=['driver_id'=>$driverId,'value'=>$value,'created'=>aid($row['createdAt']??$row['submittedAt']??null)];}
  foreach($ratings as$rating){if($from&&(!$rating['created']||$rating['created']<$from))continue;$ratingByDriver[$rating['driver_id']][]=$rating['value'];}
  $completed=array_values(array_filter($rides,fn($r)=>$r['status']==='completed'));$cancelled=array_values(array_filter($rides,fn($r)=>in_array($r['status'],['cancelled','expired'],true)));$fares=[];$revenue=0.;$commission=0.;$driverEarnings=0.;$carpoolSavings=[];
  foreach($completed as&$ride){$payment=$payments[$ride['id']]??[];$fare=aim($payment,['paidAmount','paymentAmount','finalFare','amount'])??$ride['fare'];$payStatus=ain($payment['paymentStatus']??$payment['status']??$ride['payment_status']);$refundStatus=ain($payment['refundStatus']??$payStatus);$refund=aim($payment,['refundedAmount','refundAmount'])??0.;if($fare===null||$fare<=0||in_array($payStatus,['failed','cancelled','canceled','expired'],true)||in_array($refundStatus,['refunded','reversed'],true))continue;$net=max(0,$fare-$refund);if($net<=0)continue;$fares[]=$net;$revenue+=$net;$storedCommission=aim($payment,['adminCommission','platformCommission'])??aim($ride['raw'],['adminCommission','platformCommission']);$storedDriver=aim($payment,['driverEarning','driverShare'])??aim($ride['raw'],['driverEarning','driverShare']);$rideCommission=$refund>0?round($net*.30,2):($storedCommission??round($net*.30,2));$rideDriver=$refund>0?round($net-$rideCommission,2):($storedDriver??round($net-$rideCommission,2));$commission+=$rideCommission;$driverEarnings+=$rideDriver;if($ride['type']==='carpool'){$original=$ride['original_fare'];$shared=$ride['shared_fare']??$net;if($original!==null&&$shared!==null&&$original>=$shared)$carpoolSavings[]=$original-$shared;}$ride['net_fare']=$net;$ride['driver_earning']=$rideDriver;}unset($ride);
  $recentCutoff=$now->modify('-15 minutes');$activeDrivers=0;foreach($drivers as$driver){$approved=in_array(ain($driver['verificationStatus']??$driver['accountStatus']??''),['approved','verified','active'],true)||aib($driver['isApproved']??false);$heartbeat=aid($driver['lastLocationAt']??$driver['lastHeartbeatAt']??$driver['lastOnlineAt']??$driver['updatedAt']??null);if($approved&&aib($driver['isOnline']??false)&&$heartbeat&&$heartbeat>=$recentCutoff)$activeDrivers++;}
  $allRatings=array_merge(...array_values($ratingByDriver)?:[[]]);$summary=['total_requests'=>count($rides),'completed_rides'=>count($completed),'completion_rate'=>aipercent(count($completed),count($rides)),'active_drivers'=>$activeDrivers,'average_final_fare'=>aiavg($fares),'average_driver_rating'=>aiavg($allRatings),'rating_count'=>count($allRatings)];
  $pickup=[];$dropoff=[];$hours=array_fill(0,24,0);$days=array_fill(1,7,0);$types=['instant'=>0,'scheduled'=>0,'carpool'=>0];$vehicles=[];$platforms=['passenger_app'=>0,'passenger_website'=>0,'driver_app'=>0,'driver_website'=>0,'unknown'=>0];$statuses=['waiting'=>0,'active'=>0,'completed'=>0,'cancelled'=>0,'expired'=>0];
  $platformComparison=['passenger_app'=>0,'passenger_website'=>0,'driver_app'=>0,'driver_website'=>0,'unknown'=>0];foreach($rides as$ride){$pickup[aiarea($ride['pickup'])]=($pickup[aiarea($ride['pickup'])]??0)+1;$dropoff[aiarea($ride['dropoff'])]=($dropoff[aiarea($ride['dropoff'])]??0)+1;if($ride['created']){$hours[(int)$ride['created']->format('G')]++;$days[(int)$ride['created']->format('N')]++;}$types[$ride['type']]++;$vehicles[$ride['vehicle']]=($vehicles[$ride['vehicle']]??0)+1;$platforms[$ride['source']]++;$statuses[$ride['status']]++;if(in_array($ride['source'],['passenger_app','passenger_website'],true))$platformComparison[$ride['source']]++;elseif($ride['source']==='unknown')$platformComparison['unknown']++;if($ride['status']==='completed'&&in_array($ride['update_source'],['driver_app','driver_website'],true))$platformComparison[$ride['update_source']]++;}arsort($pickup);arsort($dropoff);arsort($vehicles);
  $driverStats=[];foreach($completed as$ride){$id=$ride['driver_id'];if($id==='')continue;if(!isset($driverStats[$id])){$profile=$drivers[$id]??[];$driverStats[$id]=['driver_id'=>$id,'name'=>ait($profile,['fullName','name'],ait($ride['raw'],['driverName'],'Driver profile unavailable')),'completed_rides'=>0,'accepted_requests'=>0,'received_requests'=>null,'acceptance_rate'=>null,'cancellation_rate'=>null,'average_rating'=>aiavg($ratingByDriver[$id]??[]),'rating_count'=>count($ratingByDriver[$id]??[]),'driver_earnings'=>0.];}$driverStats[$id]['completed_rides']++;$driverStats[$id]['driver_earnings']+=($ride['driver_earning']??0);}$driverRows=array_values($driverStats);foreach($driverRows as&$row){$profile=$drivers[$row['driver_id']]??[];$received=aim($profile,['receivedRequestCount','eligibleRequestCount']);$accepted=aim($profile,['acceptedRequestCount']);if($received!==null&&$received>0&&$accepted!==null){$row['received_requests']=$received;$row['accepted_requests']=$accepted;$row['acceptance_rate']=round(($accepted/$received)*100,1);}else{$row['acceptance_rate']=null;}$row['driver_earnings']=round($row['driver_earnings'],2);}unset($row);usort($driverRows,fn($a,$b)=>$b['completed_rides']<=>$a['completed_rides']);$driverRows=array_slice($driverRows,0,8);
  $weekBuckets=[];for($i=5;$i>=0;$i--){$start=$now->modify('monday this week')->modify("-{$i} weeks")->setTime(0,0);$key=$start->format('Y-m-d');$weekBuckets[$key]=['label'=>$start->format('d M'),'requests'=>0,'completed'=>0,'revenue'=>0.];}foreach($rides as$ride){if(!$ride['event_time'])continue;$key=$ride['event_time']->modify('monday this week')->format('Y-m-d');if(isset($weekBuckets[$key])){$weekBuckets[$key]['requests']++;if($ride['status']==='completed'){$weekBuckets[$key]['completed']++;$weekBuckets[$key]['revenue']+=($ride['net_fare']??0);}}}
  $sosCurrent=[];$sosPrevious=[];foreach(admin_list_recent_collection('sosAlerts',500,'createdAt')as$alert){if(!aireal($alert))continue;$created=aid($alert['triggeredAt']??$alert['createdAt']??null);$resolved=aid($alert['resolvedAt']??null);$record=['created'=>$created,'resolved'=>$resolved,'status'=>ain($alert['status']??(($alert['isResolved']??false)?'resolved':'active'))];if($from&&$created&&$created>=$from)$sosCurrent[]=$record;elseif($previousFrom&&$created&&$created>=$previousFrom&&$created<$previousTo)$sosPrevious[]=$record;elseif(!$from)$sosCurrent[]=$record;}
  $responseTimes=[];foreach($sosCurrent as$alert)if($alert['created']&&$alert['resolved']&&$alert['resolved']>=$alert['created'])$responseTimes[]=($alert['resolved']->getTimestamp()-$alert['created']->getTimestamp())/60;$resolvedCount=count(array_filter($sosCurrent,fn($a)=>$a['resolved']||in_array($a['status'],['resolved','closed','completed','safe'],true)));$reports=admin_list_recent_collection('reports',500,'createdAt');$lost=admin_list_recent_collection('lost_found_cases',500,'createdAt');$currentReports=count(array_filter($reports,fn($r)=>!$from||(aid($r['createdAt']??null)?->getTimestamp()??0)>=$from->getTimestamp()));$currentLost=count(array_filter($lost,fn($r)=>!$from||(aid($r['createdAt']??null)?->getTimestamp()??0)>=$from->getTimestamp()));
  $safety=['sos_alerts'=>aitrend(count($sosCurrent),count($sosPrevious)),'resolved_sos'=>['current'=>$resolvedCount,'previous'=>null,'change'=>null,'label'=>'No trend data'],'average_response_minutes'=>['current'=>aiavg($responseTimes),'previous'=>null,'change'=>null,'label'=>'No trend data'],'reports_submitted'=>['current'=>$currentReports,'previous'=>null,'change'=>null,'label'=>'No trend data'],'lost_found_cases'=>['current'=>$currentLost,'previous'=>null,'change'=>null,'label'=>'No trend data']];
  $peakHour=max($hours)>0?array_search(max($hours),$hours,true):null;$peakDay=max($days)>0?array_search(max($days),$days,true):null;$dayNames=[1=>'Monday',2=>'Tuesday',3=>'Wednesday',4=>'Thursday',5=>'Friday',6=>'Saturday',7=>'Sunday'];$topVehicle=array_key_first($vehicles);$topArea=array_key_first($pickup);$insights=[];$periodLabel=match($date){'today'=>'Today','7d'=>'Last 7 Days','30d'=>'Last 30 Days','month'=>'This Month','year'=>'This Year',default=>'All Time'};
  if($topArea&&$topArea!=='Location unavailable')$insights[]=['title'=>'Highest demand area','text'=>"{$topArea} generated {$pickup[$topArea]} ride request".($pickup[$topArea]===1?'':'s').'.','metric'=>$pickup[$topArea].' requests','period'=>$periodLabel];if($peakHour!==null)$insights[]=['title'=>'Peak booking hour','text'=>date('g A',mktime($peakHour)).' to '.date('g A',mktime(($peakHour+1)%24)).' had the highest demand.','metric'=>$hours[$peakHour].' requests','period'=>$periodLabel];if(array_sum($platforms)>0){$topSource=array_key_first(array_filter($platforms,fn($v)=>$v>0));if($topSource)$insights[]=['title'=>'Leading booking source','text'=>aiplatform_label($topSource).' represented '.(aipercent($platforms[$topSource],array_sum($platforms))??0).'% of ride activity.','metric'=>$platforms[$topSource].' records','period'=>$periodLabel];}if($summary['completion_rate']!==null)$insights[]=['title'=>'Ride completion','text'=>$summary['completion_rate'].'% of valid requests were completed.','metric'=>count($completed).' completed','period'=>$periodLabel];if($summary['average_driver_rating']!==null)$insights[]=['title'=>'Service quality','text'=>'Passenger-to-driver reviews averaged '.$summary['average_driver_rating'].' out of 5.','metric'=>count($allRatings).' ratings','period'=>$periodLabel];
  $positive=count(array_filter($allRatings,fn($v)=>$v>=4));$low=count(array_filter($allRatings,fn($v)=>$v<=2));$cancellationReasons=[];foreach($cancelled as$ride)if($ride['cancellation_reason']!=='')$cancellationReasons[$ride['cancellation_reason']]=($cancellationReasons[$ride['cancellation_reason']]??0)+1;arsort($cancellationReasons);
  $payload=['ok'=>true,'generated_at'=>$now->format(DATE_ATOM),'period_label'=>$periodLabel,'summary'=>$summary,'demand'=>['pickup'=>array_slice($pickup,0,8,true),'dropoff'=>array_slice($dropoff,0,8,true),'peak_hour'=>$peakHour===null?null:date('g A',mktime($peakHour)).' - '.date('g A',mktime(($peakHour+1)%24)),'peak_day'=>$peakDay?$dayNames[$peakDay]:null,'top_vehicle'=>$topVehicle?ucwords($topVehicle):null],'distribution'=>['ride_type'=>$types,'ride_status'=>$statuses,'vehicle_type'=>$vehicles,'source_platform'=>$platforms],'driver_performance'=>$driverRows,'weekly_trend'=>array_values($weekBuckets),'safety'=>$safety,'platforms'=>array_map(fn($key,$value)=>['key'=>$key,'label'=>aiplatform_label($key),'count'=>$value],array_keys($platformComparison),array_values($platformComparison)),'financial'=>['completed_revenue'=>round($revenue,2),'average_final_fare'=>aiavg($fares),'wow_commission'=>round($commission,2),'driver_earnings'=>round($driverEarnings,2),'average_carpool_saving'=>aiavg($carpoolSavings)],'ratings'=>['average_driver_rating'=>aiavg($allRatings),'total_reviews'=>count($allRatings),'positive_share'=>aipercent($positive,count($allRatings)),'low_rating_rides'=>$low,'low_rating_rule'=>'Ratings of 1 or 2 stars'],'cancellations'=>['total'=>count($cancelled),'passenger'=>count(array_filter($cancelled,fn($r)=>str_contains($r['cancelled_by'],'passenger'))),'driver'=>count(array_filter($cancelled,fn($r)=>str_contains($r['cancelled_by'],'driver'))),'expired'=>count(array_filter($cancelled,fn($r)=>$r['status']==='expired')),'top_reason'=>array_key_first($cancellationReasons)],'insights'=>['state'=>count($rides)>=2&&$insights?'loaded':'insufficient','items'=>$insights],'collections'=>$collections,'filters'=>['date'=>$date,'type'=>$type,'vehicle'=>$vehicle,'source'=>$source,'status'=>$status]];
  $_SESSION['ai_analytics_cache'][$cacheKey]=['time'=>time(),'payload'=>$payload];if(count($_SESSION['ai_analytics_cache'])>8)$_SESSION['ai_analytics_cache']=array_slice($_SESSION['ai_analytics_cache'],-8,null,true);
  if(ain($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="ai-analytics-'.date('Ymd-His').'.csv"');$out=fopen('php://output','w');fputcsv($out,['Section','Metric','Value','Period']);foreach($summary as$key=>$value)fputcsv($out,['Summary',ucwords(str_replace('_',' ',$key)),$value??'Not available',$periodLabel]);foreach($payload['financial']as$key=>$value)fputcsv($out,['Financial',ucwords(str_replace('_',' ',$key)),$value??'Not available',$periodLabel]);foreach($platforms as$key=>$value)fputcsv($out,['Platform',aiplatform_label($key),$value,$periodLabel]);foreach($safety as$key=>$value)fputcsv($out,['Safety',ucwords(str_replace('_',' ',$key)),$value['current']??'Not available',$periodLabel]);fclose($out);exit;}
  aij($payload);
}catch(Throwable $error){error_log('AI Analytics: '.$error->getMessage());aij(['ok'=>false,'message'=>'Analytics data could not be loaded.'],500);}
