<?php declare(strict_types=1);require_once __DIR__.'/auth.php';admin_require_auth(); ?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#9a48ff"><title>AI Analytics - Women on Wheels</title><link rel="stylesheet" href="dashboard.css?v=20260802"><link rel="stylesheet" href="dashboard_v2.css?v=20260802"><link rel="stylesheet" href="ai_analytics.css?v=20260803"></head>
<body class="aia-page"><div class="admin-layout"><?php require __DIR__.'/shared_sidebar.php'; ?><main class="content"><?php require __DIR__.'/shared_header.php'; ?>
<section class="aia-head"><div><h1>AI Analytics</h1><p>Analyze real ride demand, service performance, growth and safety trends.</p></div><button class="aia-btn secondary" id="aiaExport">&#8681; Export Data</button></section>
<section class="aia-toolbar" aria-label="Analytics filters"><label>Date Range<select id="aiaDate"><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d" selected>Last 30 Days</option><option value="month">This Month</option><option value="year">This Year</option><option value="all">All Time</option></select></label><label>Ride Type<select id="aiaType"><option value="all">All Ride Types</option><option value="instant">Instant</option><option value="scheduled">Scheduled</option><option value="carpool">Carpool</option></select></label><label>Vehicle<select id="aiaVehicle"><option value="all">All Vehicles</option><option value="car">Car</option><option value="bike">Bike</option><option value="scooty">Scooty</option></select></label><label>Source Platform<select id="aiaSource"><option value="all">All Platforms</option><option value="passenger_app">Passenger Mobile App</option><option value="passenger_website">Passenger Website</option><option value="driver_app">Driver Mobile App</option><option value="driver_website">Driver Website</option><option value="unknown">Unknown Source</option></select></label><label>Ride Status<select id="aiaStatus"><option value="all">All Statuses</option><option value="waiting">Waiting</option><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select></label><button class="aia-btn secondary" id="aiaRefresh">&#8635; Refresh</button></section>
<div class="aia-global-error" id="aiaError" hidden><strong>Analytics data could not be loaded.</strong><span id="aiaErrorText">Check the connection and retry.</span><button class="aia-btn secondary" data-retry>Retry</button></div>
<section class="aia-kpis" id="aiaKpis" aria-label="Analytics summary"></section>
<section class="aia-grid">
 <article class="aia-panel"><header><div><h2>Ride Demand by Area</h2><p id="aiaDemandPeriod">Selected period</p></div><select id="aiaAreaMode" aria-label="Demand location type"><option value="pickup">Pickup Areas</option><option value="dropoff">Drop-off Areas</option></select></header><div class="aia-chart" id="aiaDemandChart" role="img" aria-label="Top ride demand areas"></div></article>
 <article class="aia-panel"><header><div><h2>Ride Distribution</h2><p>Real filtered ride records</p></div><select id="aiaDistributionMode" aria-label="Distribution metric"><option value="ride_type">Ride Type</option><option value="ride_status">Ride Status</option><option value="vehicle_type">Vehicle Type</option><option value="source_platform">Source Platform</option></select></header><div class="aia-donut-layout"><canvas id="aiaDistributionChart" width="280" height="280" aria-label="Ride distribution chart"></canvas><div id="aiaDistributionLegend" class="aia-legend"></div></div></article>
 <article class="aia-panel wide"><header><div><h2>Driver Performance</h2><p>Completed rides, real ratings and earnings</p></div></header><div class="aia-table-wrap"><table><thead><tr><th>Driver</th><th>Completed Rides</th><th>Acceptance Rate</th><th>Average Rating</th><th>Driver Earnings</th><th>Performance</th></tr></thead><tbody id="aiaDriverBody"></tbody></table></div></article>
 <article class="aia-panel wide"><header><div><h2>Weekly Growth Trend</h2><p>Comparable historical weeks</p></div><select id="aiaTrendMode" aria-label="Weekly trend metric"><option value="requests">Ride Requests</option><option value="completed">Completed Rides</option><option value="revenue">Revenue</option></select></header><div class="aia-chart-canvas"><canvas id="aiaWeeklyChart" width="900" height="290" aria-label="Weekly analytics trend"></canvas><div class="aia-chart-state" id="aiaWeeklyState" hidden></div></div></article>
 <article class="aia-panel"><header><div><h2>Peak Demand</h2><p>Asia/Karachi local time</p></div></header><div class="aia-fact-grid" id="aiaPeakFacts"></div></article>
 <article class="aia-panel"><header><div><h2>Platform Comparison</h2><p>Verifies app and website coverage</p></div></header><div class="aia-platform-list" id="aiaPlatforms"></div></article>
 <article class="aia-panel"><header><div><h2>Financial Analytics</h2><p>Same 30% / 70% ride model</p></div></header><div class="aia-fact-grid" id="aiaFinancial"></div></article>
 <article class="aia-panel"><header><div><h2>Ratings &amp; Service Quality</h2><p>Passenger-to-driver reviews only</p></div></header><div class="aia-fact-grid" id="aiaRatings"></div></article>
 <article class="aia-panel wide"><header><div><h2>Safety Trends</h2><p>Only supported incident records</p></div></header><div class="aia-safety" id="aiaSafety"></div></article>
 <article class="aia-panel"><header><div><h2>Cancellation Analysis</h2><p>Stored reasons only</p></div></header><div class="aia-fact-grid" id="aiaCancellations"></div></article>
 <article class="aia-panel"><header><div><h2>Automated Insights</h2><p>Transparent rule-based observations</p></div></header><div class="aia-insights" id="aiaInsights"><div class="aia-skeleton"></div></div></article>
</section>
<div class="aia-toast" id="aiaToast" hidden></div>
</main></div><script src="admin_realtime.js?v=20260802"></script><script src="ai_analytics.js?v=20260803"></script></body></html>
