(function(){
"use strict";
const API="ai_analytics_data.php",COLORS=["#7a35bd","#d736a4","#31a7a3","#efa52f","#6875d8","#b96a42","#718096"];
const state={payload:null,request:0,timer:null,areaMode:"pickup",distributionMode:"ride_type",trendMode:"requests"},el={};
const $=id=>document.getElementById(id),esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
document.addEventListener("DOMContentLoaded",init,{once:true});
function init(){["aiaExport","aiaDate","aiaType","aiaVehicle","aiaSource","aiaStatus","aiaRefresh","aiaError","aiaErrorText","aiaKpis","aiaDemandPeriod","aiaAreaMode","aiaDemandChart","aiaDistributionMode","aiaDistributionChart","aiaDistributionLegend","aiaDriverBody","aiaTrendMode","aiaWeeklyChart","aiaWeeklyState","aiaPeakFacts","aiaPlatforms","aiaFinancial","aiaRatings","aiaSafety","aiaCancellations","aiaInsights","aiaToast"].forEach(id=>el[id]=$(id));
[el.aiaDate,el.aiaType,el.aiaVehicle,el.aiaSource,el.aiaStatus].forEach(input=>input.onchange=debouncedLoad);el.aiaRefresh.onclick=load;el.aiaExport.onclick=()=>location.assign(`${API}?${parameters({export:"csv"})}`);el.aiaAreaMode.onchange=()=>{state.areaMode=el.aiaAreaMode.value;renderDemand()};el.aiaDistributionMode.onchange=()=>{state.distributionMode=el.aiaDistributionMode.value;renderDistribution()};el.aiaTrendMode.onchange=()=>{state.trendMode=el.aiaTrendMode.value;renderWeekly()};el.aiaError.querySelector("[data-retry]").onclick=load;window.addEventListener("resize",resizeCharts);load()}
function parameters(extra={}){return new URLSearchParams({date:el.aiaDate.value,type:el.aiaType.value,vehicle:el.aiaVehicle.value,source:el.aiaSource.value,status:el.aiaStatus.value,...extra})}
function debouncedLoad(){clearTimeout(state.timer);state.timer=setTimeout(load,300)}
async function load(){const request=++state.request;loading();try{const response=await fetch(`${API}?${parameters()}`,{credentials:"same-origin",headers:{Accept:"application/json"}});const data=await response.json();if(request!==state.request)return;if(!response.ok||!data.ok)throw new Error(data.message||"Analytics data could not be loaded.");state.payload=data;el.aiaError.hidden=true;render()}catch(error){if(request!==state.request)return;el.aiaError.hidden=false;el.aiaErrorText.textContent=error.message||"Check the connection and retry.";errorWidgets()} }
function loading(){el.aiaError.hidden=true;el.aiaKpis.innerHTML=Array.from({length:6},()=>'<article class="aia-kpi"><div class="aia-skeleton"></div></article>').join("");[el.aiaDemandChart,el.aiaDriverBody,el.aiaPeakFacts,el.aiaPlatforms,el.aiaFinancial,el.aiaRatings,el.aiaSafety,el.aiaCancellations,el.aiaInsights].forEach(node=>{if(node)node.innerHTML='<div class="aia-skeleton"></div>'});clearCanvas(el.aiaDistributionChart);clearCanvas(el.aiaWeeklyChart)}
function errorWidgets(){el.aiaKpis.innerHTML='<article class="aia-kpi"><strong>Unable to load summary</strong><small>Retry analytics data.</small></article>';[el.aiaDemandChart,el.aiaPeakFacts,el.aiaPlatforms,el.aiaFinancial,el.aiaRatings,el.aiaSafety,el.aiaCancellations,el.aiaInsights].forEach(node=>empty(node,"This analytics widget could not be loaded."));el.aiaDriverBody.innerHTML='<tr><td colspan="6" class="aia-empty">Driver performance could not be loaded.</td></tr>';showCanvasState("aiaWeeklyState","Weekly trend could not be loaded.");empty(el.aiaDistributionLegend,"Ride distribution could not be loaded.")}
function render(){renderKpis();renderDemand();renderDistribution();renderDrivers();renderWeekly();renderPeaks();renderPlatforms();renderFinancial();renderRatings();renderSafety();renderCancellations();renderInsights()}
function renderKpis(){const s=state.payload.summary||{};const cards=[["Total Ride Requests",number(s.total_requests),"Valid filtered requests"],["Completed Rides",number(s.completed_rides),"Completed in selected period"],["Completion Rate",s.completion_rate===null?"Not available":`${s.completion_rate}%`,"Completed ÷ requests"],["Active Drivers",number(s.active_drivers),"Approved with recent heartbeat"],["Average Final Fare",moneyOrNA(s.average_final_fare),"Eligible completed rides"],["Average Driver Rating",s.average_driver_rating===null?"Not rated":`${Number(s.average_driver_rating).toFixed(1)} ★`,`${number(s.rating_count)} passenger ratings`]];el.aiaKpis.innerHTML=cards.map(([title,value,note])=>`<article class="aia-kpi"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`).join("")}
function renderDemand(){const payload=state.payload;if(!payload)return;const rows=payload.demand?.[state.areaMode]||{};el.aiaDemandPeriod.textContent=`${payload.period_label} · Top ${state.areaMode} areas`;const entries=Object.entries(rows).filter(([,value])=>Number(value)>0);if(!entries.length){empty(el.aiaDemandChart,"Not enough location data to analyze ride demand.");return}const max=Math.max(...entries.map(([,v])=>Number(v)));const total=entries.reduce((sum,[,v])=>sum+Number(v),0);el.aiaDemandChart.innerHTML=entries.map(([name,value])=>`<div class="aia-bar" title="${esc(name)}"><span>${esc(name)}</span><div class="aia-track"><i style="width:${Math.max(3,(Number(value)/max)*100)}%"></i></div><b>${number(value)}</b><small hidden>${percent(value,total)}% of demand</small></div>`).join("")}
function renderDistribution(){const payload=state.payload;if(!payload)return;const source=payload.distribution?.[state.distributionMode]||{};const entries=Object.entries(source).filter(([,value])=>Number(value)>0);const canvas=el.aiaDistributionChart,ctx=canvas.getContext("2d");clearCanvas(canvas);if(!entries.length){canvas.hidden=true;empty(el.aiaDistributionLegend,"No ride distribution data for these filters.");return}canvas.hidden=false;const total=entries.reduce((sum,[,value])=>sum+Number(value),0),cx=140,cy=140,radius=86;let start=-Math.PI/2;entries.forEach(([key,value],index)=>{const angle=(Number(value)/total)*Math.PI*2;ctx.beginPath();ctx.strokeStyle=COLORS[index%COLORS.length];ctx.lineWidth=28;ctx.arc(cx,cy,radius,start,start+angle);ctx.stroke();start+=angle});ctx.fillStyle="#542766";ctx.font="700 26px Segoe UI";ctx.textAlign="center";ctx.fillText(number(total),cx,cy+4);ctx.fillStyle="#786b80";ctx.font="13px Segoe UI";ctx.fillText("rides",cx,cy+25);el.aiaDistributionLegend.innerHTML=entries.map(([key,value],index)=>`<span><i style="background:${COLORS[index%COLORS.length]}"></i>${esc(displayLabel(key))} <b>${number(value)} · ${percent(value,total)}%</b></span>`).join("")}
function renderDrivers(){const rows=state.payload?.driver_performance||[];if(!rows.length){el.aiaDriverBody.innerHTML='<tr><td colspan="6" class="aia-empty">No completed driver rides are available for this period.</td></tr>';return}el.aiaDriverBody.innerHTML=rows.map(row=>{const rating=row.average_rating===null?"Not rated":`${Number(row.average_rating).toFixed(1)} ★`;const acceptance=row.acceptance_rate===null?"Insufficient data":`${row.acceptance_rate}%`;const quality=row.average_rating!==null&&row.average_rating>=4.5?"Excellent":row.completed_rides>=5?"Active":"Developing";return`<tr><td><strong>${esc(row.name)}</strong><small>${number(row.rating_count)} ratings</small></td><td>${number(row.completed_rides)}</td><td>${esc(acceptance)}</td><td>${esc(rating)}</td><td>${money(row.driver_earnings)}</td><td><span class="aia-pill">${quality}</span></td></tr>`}).join("")}
function renderWeekly(){const rows=state.payload?.weekly_trend||[],canvas=el.aiaWeeklyChart,values=rows.map(row=>Number(row[state.trendMode]||0));if(rows.length<2||values.every(value=>value===0)){clearCanvas(canvas);showCanvasState("aiaWeeklyState","Not enough historical data to calculate a trend.");return}el.aiaWeeklyState.hidden=true;canvas.hidden=false;fitCanvas(canvas);const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,p={l:55,r:25,t:20,b:42},gw=w-p.l-p.r,gh=h-p.t-p.b,max=Math.max(...values,1);ctx.clearRect(0,0,w,h);ctx.strokeStyle="#eadff3";ctx.fillStyle="#786b80";ctx.font="12px Segoe UI";ctx.textAlign="left";for(let i=0;i<=4;i++){const y=p.t+(gh/4)*i;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(formatMetric(max-(max/4)*i),5,y+4)}ctx.strokeStyle="#8a3fc5";ctx.lineWidth=3;ctx.beginPath();rows.forEach((row,index)=>{const x=p.l+(gw/Math.max(1,rows.length-1))*index,y=p.t+gh-(values[index]/max)*gh;if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);ctx.fillStyle="#786b80";ctx.textAlign="center";ctx.fillText(row.label,x,h-14)});ctx.stroke()}
function renderPeaks(){const d=state.payload.demand||{};facts(el.aiaPeakFacts,[["Peak Ride Hour",d.peak_hour||"Not enough data","Karachi local time"],["Peak Ride Day",d.peak_day||"Not enough data","Selected period"],["Most Requested Area",firstKey(d.pickup)||"Not enough data","Normalized pickup locality"],["Most Requested Vehicle",d.top_vehicle||"Not enough data","Based on valid requests"]])}
function renderPlatforms(){const rows=state.payload.platforms||[],total=rows.reduce((sum,row)=>sum+Number(row.count||0),0);if(!total){empty(el.aiaPlatforms,"Source data unavailable for the selected records.");return}el.aiaPlatforms.innerHTML=rows.map(row=>`<div class="aia-platform"><strong>${esc(row.label)}</strong><b>${number(row.count)}</b><small>${percent(row.count,total)}% of filtered ride activity</small></div>`).join("")}
function renderFinancial(){const f=state.payload.financial||{};facts(el.aiaFinancial,[["Completed Ride Revenue",money(f.completed_revenue),"Eligible net completed fares"],["Average Final Fare",moneyOrNA(f.average_final_fare),"Completed rides"],["WOW Commission",money(f.wow_commission),"30% platform share"],["Driver Earnings",money(f.driver_earnings),"70% driver share"],["Average Carpool Saving",moneyOrNA(f.average_carpool_saving),"Completed carpool rides only"]])}
function renderRatings(){const r=state.payload.ratings||{};facts(el.aiaRatings,[["Average Driver Rating",r.average_driver_rating===null?"Not rated":`${Number(r.average_driver_rating).toFixed(1)} ★`,"Passenger-to-driver only"],["Total Driver Reviews",number(r.total_reviews),"Valid submitted ratings"],["Positive Feedback Share",r.positive_share===null?"Not available":`${r.positive_share}%`,"Ratings of 4 or 5"],["Low-Rating Rides",number(r.low_rating_rides),r.low_rating_rule||"Ratings of 1 or 2 stars"]])}
function renderSafety(){const safety=state.payload.safety||{},items=[["SOS Alerts",safety.sos_alerts],["Resolved SOS Alerts",safety.resolved_sos],["Average Response Time",safety.average_response_minutes,true],["Reports Submitted",safety.reports_submitted],["Lost & Found Cases",safety.lost_found_cases]];el.aiaSafety.innerHTML=items.map(([title,item,isMinutes])=>{const value=item?.current===null||item?.current===undefined?"Not available":isMinutes?`${Number(item.current).toFixed(1)} min`:number(item.current);const trend=item?.change===null||item?.change===undefined?"No trend data":`${Math.abs(item.change)}% ${item.label.toLowerCase()}`;const cls=item?.change>0?"up":item?.change<0?"down":"none";return`<div class="aia-fact"><span>${esc(title)}</span><strong>${esc(value)}</strong><small class="aia-trend ${cls}">${esc(trend)}</small></div>`}).join("")}
function renderCancellations(){const c=state.payload.cancellations||{};facts(el.aiaCancellations,[["Total Cancelled",number(c.total),"Cancelled and expired"],["Passenger Cancellations",number(c.passenger),"Explicit cancelledBy field"],["Driver Cancellations",number(c.driver),"Explicit cancelledBy field"],["Expired Requests",number(c.expired),"No-driver or expired state"],["Most Common Reason",c.top_reason||"No stored reason data","No inference from status"]])}
function renderInsights(){const insights=state.payload.insights||{};if(insights.state!=="loaded"||!insights.items?.length){empty(el.aiaInsights,"Not enough valid data to generate insights for this period.");return}el.aiaInsights.innerHTML=insights.items.map(item=>`<article class="aia-insight"><strong>${esc(item.title)}</strong><span>${esc(item.text)}</span><small>${esc(item.metric)} · ${esc(item.period)}</small></article>`).join("")}
function facts(node,rows){node.innerHTML=rows.map(([title,value,note])=>`<div class="aia-fact"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`).join("")}
function empty(node,message){if(node)node.innerHTML=`<div class="aia-empty">${esc(message)}</div>`}
function showCanvasState(id,message){const node=$(id);node.hidden=false;node.textContent=message;el.aiaWeeklyChart.hidden=true}
function resizeCharts(){if(state.payload){renderDistribution();renderWeekly()}}
function fitCanvas(canvas){const box=canvas.getBoundingClientRect(),ratio=Math.min(window.devicePixelRatio||1,2),w=Math.max(520,Math.floor(box.width*ratio)),h=Math.max(260,Math.floor(box.height*ratio));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function clearCanvas(canvas){if(!canvas?.getContext)return;canvas.getContext("2d").clearRect(0,0,canvas.width,canvas.height)}
function displayLabel(value){return String(value).replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function firstKey(value){return Object.keys(value||{}).find(key=>key!=="Location unavailable")||null}
function number(value){return new Intl.NumberFormat("en-PK").format(Number(value||0))}
function money(value){return `Rs. ${new Intl.NumberFormat("en-PK",{maximumFractionDigits:0}).format(Number(value||0))}`}
function moneyOrNA(value){return value===null||value===undefined?"Not available":money(value)}
function percent(value,total){return total>0?Math.round((Number(value)/total)*100):0}
function formatMetric(value){return state.trendMode==="revenue"?money(value):number(Math.round(value))}
})();
