<?php
declare(strict_types=1);require_once __DIR__.'/auth.php';require_once __DIR__.'/db.php';admin_require_auth();date_default_timezone_set('Asia/Karachi');
function amj(array$v,int$c=200):never{http_response_code($c);header('Content-Type: application/json; charset=utf-8');echo json_encode($v);exit;}function amn($v):string{return strtolower(trim((string)$v));}function amt(array$v,array$keys,string$f=''):string{foreach($keys as$k){$x=$v[$k]??null;if(is_scalar($x)&&trim((string)$x)!=='')return trim((string)$x);}return$f;}function amd($v):string{return wow_timestamp_to_string($v??'');}function aml(string$v):string{return ucwords(str_replace('_',' ',$v));}function am_source(string$v):string{return match(amn($v)){'passenger_app','passenger_mobile_app'=>'passenger_app','passenger_website','passenger_web'=>'passenger_website','driver_app','driver_mobile_app'=>'driver_app','driver_website','driver_web'=>'driver_website','admin_website','admin_web'=>'admin_website',default=>'unknown'};}function am_provider(string$v):string{$n=amn($v);return match($n){'google','google.com'=>'google.com','phone','phone_otp'=>'phone',default=>'password'};}function am_source_label(string$v):string{return match($v){'passenger_app'=>'Passenger Mobile App','passenger_website'=>'Passenger Website','driver_app'=>'Driver Mobile App','driver_website'=>'Driver Website','admin_website'=>'Admin Website',default=>'Source unavailable'};}function am_provider_label(string$v):string{return match($v){'google.com'=>'Google','phone'=>'Phone OTP',default=>'Email and Password'};}
$amInput=json_decode((string)file_get_contents('php://input'),true);if(!is_array($amInput))$amInput=[];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  if(!admin_verify_csrf_token((string)($amInput['csrf_token']??'')))amj(['ok'=>false,'message'=>'Your admin session token expired. Refresh and retry.'],403);
  $action=amn($amInput['action']??'');$eventId=trim((string)($amInput['event_id']??''));
  if($action!=='mark_reviewed'||$eventId===''||strlen($eventId)>128)amj(['ok'=>false,'message'=>'This authentication action is not valid.'],422);
  $event=wow_doc_data('authAuditLogs',$eventId);if(!$event)amj(['ok'=>false,'message'=>'Authentication event could not be found.'],404);
  $admin=$_SESSION['admin_auth']??[];$adminId=(string)($admin['uid']??$admin['id']??'');$adminName=(string)($admin['full_name']??'Admin');
  wow_set_doc('authAuditLogs',$eventId,['reviewed'=>true,'reviewedAt'=>wow_now(),'reviewedBy'=>$adminId],true);
  $actionId=hash('sha256',$eventId.'|mark_reviewed|'.$adminId.'|'.(string)floor(time()/10));
  wow_set_doc('authAdminActions',$actionId,['actionId'=>$actionId,'adminId'=>$adminId,'adminName'=>$adminName,'targetUserId'=>(string)($event['userId']??''),'eventId'=>$eventId,'action'=>'marked_event_reviewed','reason'=>'Reviewed from Authentication Monitoring','previousState'=>['reviewed'=>(bool)($event['reviewed']??false)],'newState'=>['reviewed'=>true],'createdAt'=>wow_now()],true);
  amj(['ok'=>true,'message'=>'Authentication event marked as reviewed.']);
}
try{$profiles=[];$unverified=0;foreach(['passengers'=>'passenger','drivers'=>'driver','admins'=>'admin']as$c=>$role)foreach(admin_list_collection($c,700)as$p){$uid=amt($p,['uid']);$email=amt($p,['email']);$verified=array_key_exists('emailVerified',$p)?(bool)$p['emailVerified']:(array_key_exists('isEmailVerified',$p)?(bool)$p['isEmailVerified']:null);if($uid!=='')$profiles[$uid]=['name'=>amt($p,['fullName','name'],'User profile unavailable'),'email'=>$email,'role'=>$role,'account_status'=>amt($p,['accountStatus','status'],'Active'),'email_verified'=>$verified];if($email!==''&&$verified===false&&amn($p['authProvider']??$p['provider']??'password')!=='google.com')$unverified++;}
$rows=[];foreach(admin_list_recent_collection('authAuditLogs',500,'createdAt')as$a){$uid=amt($a,['userId']);$profile=$profiles[$uid]??[];$type=amn($a['eventType']??'unknown');$status=amn($a['status']??'pending');$source=am_source((string)($a['sourcePlatform']??''));$provider=am_provider((string)($a['authProvider']??''));$rows[]=['id'=>amt($a,['eventId','uid']),'user_id'=>$uid,'user_name'=>amt($profile,['name'],amt($a,['userName'],'User profile unavailable')),'email'=>amt($a,['email'],amt($profile,['email'])),'role'=>amn($a['role']??$profile['role']??'unknown'),'event_type'=>$type,'activity_label'=>aml($type),'status'=>$status,'source'=>$source,'source_label'=>am_source_label($source),'provider'=>$provider,'provider_label'=>am_provider_label($provider),'created_at'=>amd($a['createdAt']??''),'failure_reason'=>amt($a,['failureReasonCode']),'device'=>amt($a,['deviceType'],'Unavailable'),'client'=>amt($a,['browserOrApp'],'Unavailable'),'is_suspicious'=>(bool)($a['isSuspicious']??false),'risk_reason'=>amt($a,['riskReason']),'reviewed'=>(bool)($a['reviewed']??false),'account_status'=>amt($profile,['account_status'],'Unknown'),'email_verified'=>$profile['email_verified']??null,'legacy'=>false];}
foreach(admin_list_recent_collection('adminLoginAudit',250,'attemptedAt')as$a){$status=amn($a['attemptStatus']??'failed')==='success'?'successful':'failed';$rows[]=['id'=>amt($a,['uid']),'user_id'=>amt($a,['adminUid']),'user_name'=>'Admin account','email'=>amt($a,['emailEntered']),'role'=>'admin','event_type'=>$status==='successful'?'login_success':'login_failed','activity_label'=>$status==='successful'?'Login Success':'Login Failed','status'=>$status,'source'=>'admin_website','source_label'=>'Admin Website','provider'=>'password','provider_label'=>'Email and Password','created_at'=>amd($a['attemptedAt']??''),'failure_reason'=>amt($a,['failureReason']),'device'=>'Web browser','client'=>amt($a,['userAgent'],'Unavailable'),'is_suspicious'=>in_array(amn($a['failureReason']??''),['invalid_admin_role','inactive_account'],true),'risk_reason'=>'','reviewed'=>false,'account_status'=>'Unknown','email_verified'=>null,'legacy'=>true];}
usort($rows,static fn($a,$b)=>strcmp($b['created_at'],$a['created_at']));$unique=[];$seen=[];foreach($rows as$r){$stamp=strtotime($r['created_at'])?:0;$key=amn(($r['user_id']?:$r['email']).'|'.$r['event_type'].'|'.(string)floor($stamp/20));if(isset($seen[$key]))continue;$seen[$key]=true;$unique[]=$r;}$rows=$unique;$failures=[];foreach($rows as$i=>$r)if($r['event_type']==='login_failed'){$key=$r['user_id']?:$r['email'];$time=strtotime($r['created_at'])?:0;$failures[$key][]=[$i,$time];}foreach($failures as$list)foreach($list as[$i,$time]){$near=count(array_filter($list,fn($x)=>abs($x[1]-$time)<=900));if($near>=5){$rows[$i]['is_suspicious']=true;$rows[$i]['risk_reason']='5 or more failed logins within 15 minutes';$rows[$i]['status']='needs_review';}}
$today=(new DateTimeImmutable('today',new DateTimeZone('Asia/Karachi')))->format('Y-m-d');$summary=['successful_today'=>0,'failed_today'=>0,'resets_today'=>0,'unverified_accounts'=>$unverified,'suspicious'=>0];foreach($rows as$r){if(str_starts_with($r['created_at'],$today)){if(in_array($r['event_type'],['login_success','google_sign_in_success'],true))$summary['successful_today']++;if(in_array($r['event_type'],['login_failed','google_sign_in_failed'],true))$summary['failed_today']++;if($r['event_type']==='password_reset_requested')$summary['resets_today']++;}if($r['is_suspicious']&&!$r['reviewed'])$summary['suspicious']++;}
$q=amn($_GET['q']??'');$tab=amn($_GET['tab']??'all');$role=amn($_GET['role']??'all');$status=amn($_GET['status']??'all');$source=amn($_GET['source']??'all');$provider=amn($_GET['provider']??'all');$date=amn($_GET['date']??'7d');$now=new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi'));$from=match($date){'today'=>$now->setTime(0,0),'7d'=>$now->modify('-6 days')->setTime(0,0),'30d'=>$now->modify('-29 days')->setTime(0,0),default=>null};$filtered=array_values(array_filter($rows,static function($r)use($q,$tab,$role,$status,$source,$provider,$from){$type=$r['event_type'];if($tab==='login'&&!str_contains($type,'login')&&!str_contains($type,'sign_in')&&$type!=='logout')return false;if($tab==='recovery'&&!str_contains($type,'password_reset')&&$type!=='password_changed')return false;if($tab==='verification'&&!str_contains($type,'verification')&&$type!=='email_verified')return false;if($tab==='security'&&!$r['is_suspicious']&&!in_array($type,['account_disabled','account_enabled','role_access_denied'],true))return false;if($role!=='all'&&$r['role']!==$role)return false;if($status!=='all'&&$r['status']!==$status)return false;if($source!=='all'&&$r['source']!==$source)return false;if($provider!=='all'&&$r['provider']!==$provider)return false;if($from){try{if(!$r['created_at']||new DateTimeImmutable($r['created_at'])<$from)return false;}catch(Throwable){return false;}}if($q!=='')return str_contains(amn(implode(' ',[$r['id'],$r['user_name'],$r['email'],$r['failure_reason']])), $q);return true;}));
if(amn($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="authentication-activity-'.date('Ymd-His').'.csv"');$o=fopen('php://output','w');fputcsv($o,['Event ID','User Name','Email','Role','Event Type','Provider','Source Platform','Status','Risk Level','Created At','Failure Reason Code','Reviewed']);foreach($filtered as$r)fputcsv($o,[$r['id'],$r['user_name'],$r['email'],$r['role'],$r['event_type'],$r['provider_label'],$r['source_label'],$r['status'],$r['is_suspicious']?'High':($r['status']==='failed'?'Low':'Normal'),$r['created_at'],$r['failure_reason'],$r['reviewed']?'Yes':'No']);fclose($o);exit;}$size=max(20,min(50,(int)($_GET['page_size']??25)));$total=count($filtered);$pages=max(1,(int)ceil($total/$size));$page=max(1,min($pages,(int)($_GET['page']??1)));amj(['ok'=>true,'summary'=>$summary,'rows'=>array_slice($filtered,($page-1)*$size,$size),'pagination'=>['page'=>$page,'total'=>$total,'total_pages'=>$pages,'has_prev'=>$page>1,'has_next'=>$page<$pages],'capabilities'=>['phone_otp'=>false,'google_sign_in'=>true,'central_audit'=>true]]);}catch(Throwable$e){error_log('Authentication Monitoring: '.$e->getMessage());amj(['ok'=>false,'message'=>'Authentication activity could not be loaded.'],500);}
