<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php'; require_once __DIR__.'/db.php'; admin_require_auth();
date_default_timezone_set('Asia/Karachi');
function cpj(array $x,int $s=200):void{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($x,JSON_UNESCAPED_SLASHES);exit;}
function cpn($v):string{return strtolower(trim((string)$v));}
function cpb($v):bool{return filter_var($v,FILTER_VALIDATE_BOOLEAN);}
function cpt($v):int{if($v instanceof \Google\Cloud\Core\Timestamp)return $v->get()->getTimestamp();if($v instanceof DateTimeInterface)return $v->getTimestamp();if(is_numeric($v)){$n=(int)$v;return $n>20000000000?(int)floor($n/1000):$n;}$t=strtotime((string)$v);return $t?:0;}
function cpd($v):string{$t=cpt($v);return $t?date(DATE_ATOM,$t):'';}
function cps($v):string{if(is_string($v)||is_numeric($v))return trim((string)$v);if(is_array($v))foreach(['address','formattedAddress','name','label','placeName'] as $k)if(trim((string)($v[$k]??''))!=='')return trim((string)$v[$k]);return '';}
function cpm(array $r,array $keys):?float{foreach($keys as $k)if(array_key_exists($k,$r)&&is_numeric($r[$k]))return round((float)$r[$k],2);return null;}
function cpid(array $r):string{return trim((string)($r['rideId']??$r['carpoolRideId']??$r['bookingId']??$r['uid']??''));}
function cp_is(array $r):bool{$type=cpn($r['rideType']??$r['bookingType']??$r['serviceType']??'');return cpb($r['isCarpool']??false)||cpb($r['sharedRide']??false)||cpb($r['isShared']??false)||in_array($type,['carpool','shared','shared_ride'],true)||is_array($r['carpool']??null);}
function cp_group($v,bool $scheduled=false):string{$s=cpn($v);if(in_array($s,['completed','ride_completed','finished','success','successful'],true))return 'completed';if(str_starts_with($s,'cancelled')||str_starts_with($s,'canceled')||in_array($s,['rejected','expired','declined','no_driver_found'],true))return 'cancelled';if(in_array($s,['accepted','matched','driver_assigned','driver_selected','driver_arriving','arrived','started','in_progress','ongoing','ride_started'],true))return 'active';if($scheduled||in_array($s,['scheduled','upcoming','scheduled_pending'],true))return 'scheduled';return 'waiting';}
function cp_label(string $s):string{$map=['ride_started'=>'In Progress','started'=>'In Progress','in_progress'=>'In Progress','driver_selected'=>'Driver Assigned','driver_assigned'=>'Driver Assigned','searching'=>'Waiting for Match','searching_driver'=>'Waiting for Match','ride_completed'=>'Completed'];return $map[$s]??ucwords(str_replace('_',' ',$s?:'waiting'));}
function cp_profile(array $p,string $fallback):array{return ['name'=>(string)($p['fullName']??$p['name']??$fallback),'email'=>(string)($p['email']??''),'phone'=>(string)($p['phoneNumber']??$p['phone']??''),'rating'=>$p['averageRating']??$p['rating']??null,'vehicle'=>(string)($p['vehicleModel']??$p['vehicleName']??''),'plate'=>(string)($p['vehicleNumber']??$p['registrationNumber']??'')];}
function cp_row(array $r,array $passengers,array $drivers,array $payments):array{
 $id=(string)($r['uid']??cpid($r)); $rid=cpid($r)?:$id;
 $ids=array_values(array_unique(array_filter(array_map('strval',(array)($r['passengerIds']??[]))))); $single=(string)($r['passengerId']??$r['passengerUid']??''); if($single!==''&&!in_array($single,$ids,true))$ids[]=$single;
 $plist=[]; foreach($ids as $pid)$plist[]=array_merge(['id'=>$pid],cp_profile($passengers[$pid]??[],(string)($r['passengerName']??'Passenger')));
 $did=(string)($r['assignedDriverId']??$r['driverId']??$r['driverUid']??''); $driver=cp_profile($drivers[$did]??[],(string)($r['driverName']??($did?'Driver':'Waiting for driver')));
 $scheduled=cpt($r['scheduledAt']??$r['scheduledDateTime']??null)>0; $status=cpn($r['status']??$r['rideStatus']??$r['bookingStatus']??'pending'); $group=cp_group($status,$scheduled); $pay=$payments[$id]??$payments[$rid]??[];
 $original=cpm($r,['originalFare','estimatedFare','totalFare']); $shared=cpm($r,['finalFare','sharedFare','carpoolFare','discountedFare','acceptedFare','fare']); $saving=cpm($r,['savings','passengerSavings','discount']); if($saving===null&&$original!==null&&$shared!==null)$saving=max(0,$original-$shared);
 $count=max(count($ids),(int)($r['totalPassengers']??$r['passengerCount']??0)); $capacity=(int)($r['totalSeats']??$r['vehicleCapacity']??$r['maxPassengers']??$r['seatCount']??0); $occupied=(int)($r['occupiedSeats']??$r['bookedSeats']??$r['totalSeatsUsed']??($count?:0)); $available=array_key_exists('availableSeats',$r)?(int)$r['availableSeats']:($capacity?max(0,$capacity-$occupied):null);
 $commission=cpm($pay,['adminCommission','platformCommission','wowCommission'])??cpm($r,['adminCommission','platformCommission','wowCommission']); $driverShare=cpm($pay,['driverEarning','driverShare'])??cpm($r,['driverEarning','driverShare']);
 return ['id'=>$id,'ride_id'=>$rid,'ride_code'=>(string)($r['rideCode']??$r['carpoolRideId']??$rid),'status'=>$status,'status_group'=>$group,'status_label'=>cp_label($status),'scheduled'=>$scheduled,'passengers'=>$plist,'passenger_count'=>$count,'driver_id'=>$did,'driver'=>$driver,'pickup'=>cps($r['pickupAddress']??$r['pickupLocation']??$r['pickup']??'')?:'Not available','dropoff'=>cps($r['dropoffAddress']??$r['destinationAddress']??$r['dropoff']??$r['destination']??'')?:'Not available','vehicle_type'=>(string)($r['vehicleType']??$r['requestedVehicleType']??'car'),'distance_km'=>cpm($r,['distanceKm','totalDistanceKm','distance']),'duration_min'=>cpm($r,['durationMin','totalDurationMinutes','durationMinutes']),'capacity'=>$capacity?:null,'occupied'=>$occupied?:($count?:null),'available'=>$available,'original_fare'=>$original,'shared_fare'=>$shared,'savings'=>$saving,'final_fare'=>$shared,'admin_commission'=>$commission??($shared!==null?round($shared*.3,2):null),'driver_share'=>$driverShare??($shared!==null?round($shared*.7,2):null),'payment_method'=>(string)($pay['paymentMethod']??$r['paymentMethod']??''),'payment_status'=>(string)($pay['paymentStatus']??$pay['status']??$r['paymentStatus']??''),'created_at'=>cpd($r['createdAt']??$r['requestedAt']??null),'scheduled_at'=>cpd($r['scheduledAt']??$r['scheduledDateTime']??null),'accepted_at'=>cpd($r['acceptedAt']??$r['matchedAt']??null),'started_at'=>cpd($r['startedAt']??null),'completed_at'=>cpd($r['completedAt']??$r['rideCompletedAt']??null),'cancelled_at'=>cpd($r['cancelledAt']??$r['canceledAt']??($group==='cancelled'?($r['updatedAt']??null):null)),'source'=>(string)($r['_collection']??'rides')];
}
try{
 $sources=[]; foreach(['rides','rideRequests','scheduledRides','bookings','carpoolRides'] as $c)foreach(admin_list_collection($c,1500) as $r){$r['_collection']=$c;if(cp_is($r)&&!cpb($r['isDemo']??false)&&!cpb($r['deleted']??$r['isDeleted']??false))$sources[]=$r;}
 $merged=[]; foreach($sources as $r){$k=cpid($r);if($k==='')continue;$old=$merged[$k]??null;if(!$old||cpt($r['updatedAt']??$r['createdAt']??null)>=cpt($old['updatedAt']??$old['createdAt']??null))$merged[$k]=$r;}
 $pass=[]; foreach(admin_list_collection('passengers',1000) as $p)$pass[(string)($p['uid']??'')]=$p; $drivers=[];foreach(admin_list_collection('drivers',1000) as $d)$drivers[(string)($d['uid']??'')]=$d; $payments=[];foreach(admin_list_collection('payments',1000) as $p){$k=(string)($p['rideId']??'');if($k!=='')$payments[$k]=$p;}
 $rows=[]; foreach($merged as $r)try{$rows[]=cp_row($r,$pass,$drivers,$payments);}catch(Throwable $e){error_log('[Carpool] malformed '.cpid($r).': '.$e->getMessage());} usort($rows,static fn($a,$b)=>cpt($b['created_at'])<=>cpt($a['created_at']));
 $today=date('Y-m-d');$unique=[];$summary=['active'=>0,'completed_today'=>0,'passengers_today'=>0,'revenue_today'=>0.0];foreach($rows as $x){if($x['status_group']==='active')$summary['active']++;$todayRide=str_starts_with($x['completed_at']?:$x['created_at'],$today);if($x['status_group']==='completed'&&str_starts_with($x['completed_at'],$today)){$summary['completed_today']++;$ps=cpn($x['payment_status']);if(!in_array($ps,['pending','failed','refunded','reversed','cancelled','canceled','unpaid'],true)&&($x['final_fare']??0)>0)$summary['revenue_today']+=$x['final_fare'];}if($todayRide)foreach($x['passengers'] as $p)$unique[$p['id']]=true;}$summary['passengers_today']=count($unique);$summary['revenue_today']=round($summary['revenue_today'],2);
 $q=cpn($_GET['q']??'');$status=cpn($_GET['status']??'all');$date=cpn($_GET['date']??'all');$payment=cpn($_GET['payment']??'all');$from=match($date){'today'=>strtotime('today'),'7d'=>strtotime('-6 days midnight'),'30d'=>strtotime('-29 days midnight'),'month'=>strtotime('first day of this month midnight'),default=>0};
 $filtered=array_values(array_filter($rows,static function($x)use($q,$status,$payment,$from){if($status!=='all'&&$x['status_group']!==$status)return false;if($from&&cpt($x['created_at']?:$x['scheduled_at'])<$from)return false;$ps=cpn($x['payment_status']);$pm=cpn($x['payment_method']);if($payment!=='all'){if($payment==='cash'&&$pm!=='cash')return false;if($payment==='online'&&$pm==='cash')return false;if(!in_array($payment,['cash','online'],true)&&!str_contains($ps,$payment))return false;}if($q==='')return true;$names=implode(' ',array_column($x['passengers'],'name'));$contacts=implode(' ',array_merge(array_column($x['passengers'],'email'),array_column($x['passengers'],'phone')));return str_contains(cpn(implode(' ',[$x['ride_code'],$names,$contacts,$x['driver']['name'],$x['driver']['email'],$x['pickup'],$x['dropoff'],$x['vehicle_type']])), $q);}));
 if(cpn($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=carpools_'.date('Ymd_His').'.csv');$o=fopen('php://output','w');fputcsv($o,['Ride ID','Passenger Names','Passenger Count','Driver','Vehicle','Pickup','Drop-off','Scheduled Time','Seat Capacity','Occupied Seats','Original Fare','Shared Fare','Savings','Final Fare','Payment Method','Payment Status','Ride Status','Admin Commission','Driver Share','Created At','Completed At']);foreach($filtered as $x)fputcsv($o,[$x['ride_code'],implode('; ',array_column($x['passengers'],'name')),$x['passenger_count'],$x['driver']['name'],$x['vehicle_type'],$x['pickup'],$x['dropoff'],$x['scheduled_at'],$x['capacity'],$x['occupied'],$x['original_fare'],$x['shared_fare'],$x['savings'],$x['final_fare'],$x['payment_method'],$x['payment_status'],$x['status'],$x['admin_commission'],$x['driver_share'],$x['created_at'],$x['completed_at']]);fclose($o);exit;}
 $size=max(10,min(20,(int)($_GET['page_size']??15)));$total=count($filtered);$pages=max(1,(int)ceil($total/$size));$page=max(1,min($pages,(int)($_GET['page']??1)));cpj(['ok'=>true,'summary'=>$summary,'carpools'=>array_slice($filtered,($page-1)*$size,$size),'pagination'=>['page'=>$page,'page_size'=>$size,'total'=>$total,'total_pages'=>$pages,'has_prev'=>$page>1,'has_next'=>$page<$pages],'collections'=>array_values(array_unique(array_column($sources,'_collection')))]);
}catch(Throwable $e){error_log('[Carpool Management] '.$e->getMessage());cpj(['ok'=>false,'error'=>'Carpool data could not be loaded.'],500);}
