<?php
declare(strict_types=1);require_once __DIR__.'/auth.php';require_once __DIR__.'/db.php';admin_require_auth();header('Content-Type: application/json; charset=utf-8');
function kb_json(array $v,int $c=200):never{http_response_code($c);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function kb_in():array{$v=json_decode((string)file_get_contents('php://input'),true);return is_array($v)?array_merge($_GET,$_POST,$v):array_merge($_GET,$_POST);}function kb_list(mixed $v):array{if(is_array($v))return array_values(array_filter(array_map(fn($x)=>trim((string)$x),$v)));return array_values(array_filter(array_map('trim',explode(',',(string)$v))));}
$in=kb_in();$action=strtolower(trim((string)($in['action']??'list')));$admin=$_SESSION['admin_auth']??[];
try{
 if($action==='list'){kb_json(['ok'=>true,'items'=>wow_list_collection('chatbotKnowledgeBase',500)]);}
 if($action==='save'){$id=trim((string)($in['id']??''));$category=trim((string)($in['category']??''));$intent=trim((string)($in['intent']??''));$answer=trim((string)($in['answer']??$in['answerEnglish']??''));$status=strtolower(trim((string)($in['status']??'draft')));if($category===''||$intent===''||$answer==='')kb_json(['ok'=>false,'message'=>'Intent, category and answer are required.'],422);if(!in_array($status,['draft','active','archived'],true))$status='draft';$ref=$id!==''?wow_firestore()->collection('chatbotKnowledgeBase')->document($id):wow_firestore()->collection('chatbotKnowledgeBase')->newDocument();$phrases=kb_list($in['phrases']??$in['alternativeQuestions']??$in['keywords']??[]);$ref->set(['intent'=>$intent,'category'=>$category,'phrases'=>$phrases,'keywords'=>$phrases,'alternativeQuestions'=>$phrases,'answer'=>$answer,'answerEnglish'=>$answer,'userRole'=>strtolower(trim((string)($in['userRole']??'all'))),'allowedRoles'=>strtolower(trim((string)($in['userRole']??'all')))==='all'?['passenger','driver']:[strtolower(trim((string)$in['userRole']))],'sourcePlatform'=>strtolower(trim((string)($in['sourcePlatform']??'all'))),'priority'=>max(0,min(100,(int)($in['priority']??50))),'status'=>$status,'isActive'=>$status==='active','updatedBy'=>(string)($admin['uid']??''),'updatedAt'=>wow_now()],['merge'=>true]);kb_json(['ok'=>true,'id'=>$ref->id()]);}
 if($action==='status'){$id=trim((string)($in['id']??''));$status=strtolower(trim((string)($in['status']??'')));if($id===''||!in_array($status,['draft','active','archived'],true))kb_json(['ok'=>false,'message'=>'Invalid knowledge status.'],422);wow_set_doc('chatbotKnowledgeBase',$id,['status'=>$status,'isActive'=>$status==='active','updatedBy'=>(string)($admin['uid']??''),'updatedAt'=>wow_now()],true);kb_json(['ok'=>true]);}
 if($action==='delete'){$id=trim((string)($in['id']??''));if($id==='')kb_json(['ok'=>false,'message'=>'Knowledge ID is required.'],422);wow_firestore()->collection('chatbotKnowledgeBase')->document($id)->delete();kb_json(['ok'=>true]);}
 kb_json(['ok'=>false,'message'=>'Unsupported action.'],422);
}catch(Throwable $e){error_log('Chatbot KB API: '.$e->getMessage());kb_json(['ok'=>false,'message'=>'Knowledge base operation failed.'],500);}
