<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
admin_require_auth();
$admin=$_SESSION['admin_auth']??[];
$adminName=(string)($admin['full_name']??'Admin');
$adminRole=(string)($admin['role']??'admin');
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#9a48ff"><title>Driver Verification - Women on Wheels</title><link rel="stylesheet" href="dashboard.css?v=20260802-driver1"><link rel="stylesheet" href="dashboard_v2.css?v=20260802-admin-layout2"><link rel="stylesheet" href="drivers.css?v=20260803-themed-dialog1"></head><body class="dm-page"><div class="admin-layout"><?php require __DIR__.'/shared_sidebar.php'; ?><main class="content">
<header class="topbar"><span>Driver Verification</span></header>
<section class="dm-head"><div><h1>Driver Verification</h1><p>Review female driver applications, approve verified drivers, and manage active driver profiles</p></div><button id="driversExport" class="dm-primary-small" type="button"><span aria-hidden="true">&#8681;</span> Export Data</button></section>
<section class="dm-kpis">
<article><span class="dm-kpi-icon">&#128663;</span><div><p>Total Drivers</p><h3 id="dmTotalDrivers" class="dm-skeleton-text">--</h3><small>All registered driver accounts</small></div></article>
<article><span class="dm-kpi-icon online">&#9679;</span><div><p>Online Now</p><h3 id="dmOnlineDrivers" class="dm-skeleton-text">--</h3><small>Approved drivers currently online</small></div></article>
<article><span class="dm-kpi-icon pending">&#9203;</span><div><p>Pending Applications</p><h3 id="dmPendingDrivers" class="dm-skeleton-text">--</h3><small>Applications awaiting admin review</small></div></article>
<article><span class="dm-kpi-icon rating">&#9733;</span><div><p>Average Rating</p><h3 id="dmAvgRating" class="dm-skeleton-text">--</h3><small id="dmRatingCount">Average of passenger ratings</small></div></article>
</section>
<section class="dm-toolbar"><label class="dm-search"><span>&#128269;</span><input id="driverSearch" type="search" placeholder="Search name, email, phone, CNIC or vehicle" autocomplete="off"><button id="driverSearchClear" type="button" aria-label="Clear driver search" hidden>&times;</button></label><select id="driverStatusFilter" aria-label="Filter by account status"><option value="all">All Statuses</option><option value="pending">Pending</option><option value="offline">Approved / Offline</option><option value="active">Active / Online</option><option value="blocked">Blocked</option><option value="rejected">Rejected</option></select><select id="driverVerificationFilter" aria-label="Filter by verification state"><option value="all">All Verification States</option><option value="fully_verified">Fully Verified</option><option value="partially_verified">Partially Verified</option><option value="documents_missing">Documents Missing</option><option value="documents_rejected">Documents Rejected</option></select><button id="driversRefreshNow" class="dm-secondary" type="button">&#8635; Refresh</button></section>
<section class="panel dm-table-panel"><div class="table-wrap"><table class="dm-table"><thead><tr><th>Driver</th><th>Vehicle</th><th>Verification</th><th>Performance</th><th>Earnings</th><th>Status</th><th>Actions</th></tr></thead><tbody id="driverTableBody"><tr><td colspan="7"><div class="dm-skeleton"></div><div class="dm-skeleton short"></div></td></tr></tbody></table></div><footer class="dm-pagination"><span id="dmResultCount">Loading drivers…</span><div><button id="dmPrevPage" disabled>Previous</button><strong id="dmPageLabel">Page 1</strong><button id="dmNextPage" disabled>Next</button></div></footer></section>
<div class="dm-modal-backdrop" id="driverDetailBackdrop" hidden><section class="dm-modal" role="dialog" aria-modal="true" aria-labelledby="dmModalName"><header><span class="dm-modal-avatar" id="dmModalAvatar">D</span><div><div class="dm-modal-title"><h2 id="dmModalName">Driver</h2><span id="dmModalVerification" class="dm-pill">Pending</span><span id="dmModalOnline" class="dm-pill offline">Offline</span></div><p id="dmModalId">ID: —</p></div><button id="dmModalClose" type="button" aria-label="Close driver profile">&times;</button></header><div class="dm-modal-body"><div id="dmDetailError" class="dm-error" hidden></div><section><h3>Personal Information</h3><div class="dm-detail-grid" id="dmPersonalGrid"></div></section><section><h3>Vehicle Information</h3><div class="dm-detail-grid" id="dmVehicleGrid"></div></section><section><h3>Verification Status</h3><div class="dm-detail-grid" id="dmVerificationGrid"></div><button id="dmOpenDocuments" class="dm-secondary" type="button">View Documents</button></section><section><h3>Performance</h3><div class="dm-stat-grid" id="dmPerformanceGrid"></div></section><section><h3>Earnings</h3><div class="dm-stat-grid" id="dmEarningsGrid"></div></section><section><div class="dm-section-head"><h3>Recent Passenger Reviews</h3><a id="dmAllReviews" href="ratings_reviews.php">View All Reviews</a></div><div id="dmRecentReviews"><div class="dm-skeleton"></div></div></section><section><div class="dm-section-head"><h3>Recent Rides</h3><a id="dmAllRides" href="rides.php">View Full Ride History</a></div><div id="dmRecentRides"><div class="dm-skeleton"></div></div></section></div><footer id="dmModalActions"><button class="dm-secondary" data-dm-close type="button">Close</button></footer></section></div>
<div class="dm-modal-backdrop" id="driverDocumentsBackdrop" hidden><section class="dm-modal dm-doc-modal" role="dialog" aria-modal="true" aria-labelledby="dmDocumentsTitle"><header><div><h2 id="dmDocumentsTitle">Driver Documents</h2><p>Review uploaded verification documents</p></div><button id="dmDocumentsClose" type="button" aria-label="Close documents">&times;</button></header><div class="dm-modal-body"><div class="dm-doc-grid" id="dmDocumentsGrid"></div></div><footer><button class="dm-secondary" data-dm-doc-close type="button">Close</button></footer></section></div>
<div class="dm-zoom" id="dmDocumentZoom" hidden><button type="button" aria-label="Close full-size document">&times;</button><img alt="Document full size"></div>
</main></div><script>window.ADMIN_DRIVERS_BOOTSTRAP={adminName:<?php echo json_encode($adminName); ?>,adminRole:<?php echo json_encode($adminRole); ?>};</script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-auth-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore-compat.js"></script><script src="admin_realtime.js?v=20260802-shared-header1"></script><script src="drivers.js?v=20260803-themed-dialog1"></script></body></html>
