<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
require_once __DIR__.'/db.php';
require_once __DIR__.'/financial_service.php';
require_once __DIR__.'/../php/driver_documents.php';
admin_require_auth();

function drivers_json(array $payload,int $status=200):void{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($payload);exit;}
function driver_csv(string $value):string{return '"'.str_replace('"','""',$value).'"';}
function driver_norm($value):string{return strtolower(trim((string)$value));}
function driver_bool($value):bool{return filter_var($value,FILTER_VALIDATE_BOOLEAN);}
function driver_time($value):int{if($value instanceof \Google\Cloud\Core\Timestamp)return $value->get()->getTimestamp();if($value instanceof \DateTimeInterface)return $value->getTimestamp();if(is_numeric($value))return (int)$value<20000000000?(int)$value:(int)floor((int)$value/1000);$time=strtotime((string)$value);return $time?:0;}
function driver_real(array $row):bool{$id=driver_norm($row['uid']??$row['rideId']??$row['ratingId']??'');$email=driver_norm($row['email']??'');$moderation=driver_norm($row['moderationStatus']??'visible');$hidden=($row['isVisible']??true)===false||in_array($moderation,['hidden','deleted'],true);return !str_starts_with($id,'test_')&&!str_contains($email,'test.')&&!driver_bool($row['isDemo']??false)&&!driver_bool($row['isDemoPayment']??false)&&!driver_bool($row['deleted']??$row['isDeleted']??false)&&!$hidden;}
function driver_id(array $row):string{return trim((string)($row['driverId']??$row['driverUid']??$row['assignedDriverId']??$row['driverID']??''));}
function driver_ride_id(array $row):string{return trim((string)($row['rideId']??$row['uid']??$row['rideCode']??''));}
function driver_completed(array $ride):bool{return in_array(driver_norm($ride['status']??$ride['rideStatus']??''),['completed','ride_completed'],true);}
function driver_cancelled(array $ride):bool{$s=driver_norm($ride['status']??$ride['rideStatus']??'');return str_starts_with($s,'cancelled')||str_starts_with($s,'canceled');}
function driver_money(array $row):float{foreach(['finalFare','paidAmount','totalFare','acceptedFare','agreedFare','amount','fare'] as $key)if(isset($row[$key])&&is_numeric($row[$key]))return max(0,(float)$row[$key]);return 0;}
function driver_share(array $row):float{foreach(['driverEarning','driverShare','netEarning','earning','paidToDriver'] as $key)if(isset($row[$key])&&is_numeric($row[$key]))return max(0,(float)$row[$key]);return round(driver_money($row)*.7,2);}
function driver_mask_cnic(string $cnic):string{$d=preg_replace('/\D+/','',$cnic)??'';return strlen($d)>=7?substr($d,0,5).'-*****-'.substr($d,-1):'';}
function driver_location($value):string{if(is_string($value)&&trim($value)!=='')return trim($value);if(is_array($value)){foreach(['address','name','formattedAddress'] as $key)if(trim((string)($value[$key]??''))!=='')return trim((string)$value[$key]);}return 'Location pending';}
function driver_status(array $row):string{if(driver_bool($row['isBlocked']??false))return'blocked';$v=driver_norm($row['verificationStatus']??$row['accountStatus']??'pending');if(in_array($v,['rejected','declined'],true))return'rejected';if(!wow_driver_is_approved($row))return'pending';return driver_bool($row['isOnline']??false)?'active':'offline';}
function driver_verification_state(array $row):string{$v=driver_norm($row['verificationStatus']??$row['verification_status']??'pending');if(in_array($v,['approved','verified'],true))return'fully_verified';if(in_array($v,['rejected','declined'],true))return'documents_rejected';$hasCnic=trim((string)driver_pick($row,['cnicFrontUrl','cnic_front_url','cnicUploadUrl','cnic_upload_url','cnicFileUrl','cnic_file_url'],''))!=='';$hasLicence=trim((string)driver_pick($row,['licenceImageUrl','licence_image_url','licenseImageUrl','license_image_url'],''))!=='';$hasVehicle=trim((string)driver_pick($row,['vehicleNumber','vehicle_number','driverVehicleNumber','driver_vehicle_number','vehicleNo','vehicle_no','numberPlate','number_plate','plateNumber','plate_number','registrationNumber','registration_number'],''))!=='';if(!$hasCnic||!$hasLicence||!$hasVehicle)return'documents_missing';return'partially_verified';}
function driver_doc_status(array $row,string $key,string $url):string{$map=is_array($row['documentVerification']??null)?$row['documentVerification']:[];$stored=driver_norm($map[$key]['status']??$map[$key]??'');if(in_array($stored,['approved','verified','rejected','expired','pending'],true))return $stored==='approved'?'verified':$stored;if($url==='')return'missing';return wow_driver_is_approved($row)?'verified':'pending';}
function driver_doc_url(string $url,string $uid='',string $slot=''):string{if($uid!==''&&$slot!==''&&($url!==''||wow_driver_document_existing_local_file($uid,$slot)!==''))return wow_driver_document_url($uid,$slot);if($url===''||preg_match('#^(https?:)?//#i',$url))return$url;return '../php/'.ltrim($url,'/');}
function driver_rating_value(array $row):?float{foreach(['rating','driverRating','stars','score'] as $key){if(!array_key_exists($key,$row))continue;$n=(float)$row[$key];if(is_numeric($row[$key])&&$n>=1&&$n<=5)return$n;}return null;}
function driver_pick(array $row,array $keys,$fallback=''){foreach($keys as $key){if(!array_key_exists($key,$row))continue;$value=$row[$key];if(is_scalar($value)&&trim((string)$value)!=='')return$value;}return$fallback;}
function driver_merge_profile(array $application,array $driver):array{$merged=$application;foreach($driver as $key=>$value){if($value===null)continue;if(is_string($value)&&trim($value)==='')continue;if(is_array($value)&&$value===[])continue;$merged[$key]=$value;}return$merged;}

function driver_build_context():array{
 $drivers=array_values(array_filter(admin_list_collection('drivers',500),'driver_real'));
 $apps=array_values(array_filter(admin_list_collection('driverApplications',500),'driver_real'));
 $rides=array_values(array_filter(admin_list_collection('rides',1000),'driver_real'));
 $ratings=array_merge(array_values(array_filter(admin_list_collection('ratings',500),'driver_real')),array_values(array_filter(admin_list_collection('rideReviews',500),'driver_real')));
 $payments=array_values(admin_list_collection('payments',500));
 $ridesById=[];$ridesByDriver=[];foreach($rides as $ride){$rid=driver_ride_id($ride);if($rid!=='')$ridesById[$rid]=$ride;$did=driver_id($ride);if($did!=='')$ridesByDriver[$did][]=$ride;}
 $ratingsByDriver=[];$ratingByRide=[];foreach($ratings as $rating){$value=driver_rating_value($rating);$rid=driver_ride_id($rating);$ride=$ridesById[$rid]??[];$did=driver_id($rating)?:driver_id($ride);if($value===null||$rid===''||$did===''||!$ride||!driver_completed($ride)||driver_id($ride)!==$did)continue;if(isset($ratingByRide[$rid])){if(driver_time($rating['updatedAt']??$rating['createdAt']??'')<=driver_time($ratingByRide[$rid]['updatedAt']??$ratingByRide[$rid]['createdAt']??''))continue;}$rating['_numeric']=$value;$rating['_driver']=$did;$ratingByRide[$rid]=$rating;}
 foreach($ratingByRide as $rating)$ratingsByDriver[$rating['_driver']][]=$rating;
 $paymentsByDriver=[];foreach($payments as $payment){$did=driver_id($payment);if($did!=='')$paymentsByDriver[$did][]=$payment;}
 return compact('drivers','apps','ridesById','ridesByDriver','ratingsByDriver','paymentsByDriver');
}
function driver_financials(string $uid,array $rides,array $payments):array{$result=wow_financial_reconcile('all',false,$rides,$payments);$totals=$result['totals'];return['total'=>round((float)$totals['driverEarnings'],2),'paid'=>round((float)$totals['driverEarnings'],2),'pending'=>round((float)$totals['pendingOnlinePayments']*.70,2),'commission'=>round((float)$totals['wowCommissionEarnings'],2)];}
function driver_row(array $driver,array $rides,array $ratings,array $payments,string $applicationId=''):array{$values=array_column($ratings,'_numeric');$ratingCount=count($values);$completed=count(array_filter($rides,'driver_completed'));$cancelled=count(array_filter($rides,'driver_cancelled'));$financial=driver_financials((string)($driver['uid']??''),$rides,$payments);$lastHeartbeat=driver_time($driver['lastOnlineAt']??$driver['locationUpdatedAt']??$driver['updatedAt']??'');$approved=wow_driver_is_approved($driver);$online=$approved&&driver_bool($driver['isOnline']??false)&&$lastHeartbeat>0&&(time()-$lastHeartbeat)<=900;$status=driver_status($driver);if($status==='active'&&!$online)$status='offline';$uid=(string)($driver['uid']??$driver['driverId']??'');$location=driver_location($driver['city']??$driver['currentLocation']??$driver['location']??'');$name=(string)driver_pick($driver,['fullName','full_name','name','driverName','driver_name','displayName'],'Driver');$email=(string)driver_pick($driver,['email','emailAddress','email_address'],'');$phone=(string)driver_pick($driver,['phoneNumber','phone_number','phone','mobile','contactNumber','contact_number'],'');$cnic=(string)driver_pick($driver,['cnicNumber','cnic_number','cnic','nationalId','national_id'],'');$vehicleType=(string)driver_pick($driver,['vehicleType','vehicle_type','driverVehicleType','driver_vehicle_type','vehicleCategory','vehicle_category'],'');$vehicleNumber=(string)driver_pick($driver,['vehicleNumber','vehicle_number','driverVehicleNumber','driver_vehicle_number','vehicleNo','vehicle_no','numberPlate','number_plate','plateNumber','plate_number','registrationNumber','registration_number'],'');$vehicleModel=(string)driver_pick($driver,['vehicleModel','vehicle_model','driverVehicleName','driver_vehicle_name','vehicleName','vehicle_name','carModel','car_model','model','vehicle'],'');return[
 'driver_id'=>$uid,'uid'=>$uid,'application_id'=>$applicationId?:((string)($driver['applicationId']??'')),'name'=>$name,'email'=>$email,'phone'=>$phone,'gender'=>(string)driver_pick($driver,['gender'],''),'location'=>$location,'masked_cnic'=>driver_mask_cnic($cnic),'search_cnic'=>$cnic,
 'vehicle_type'=>$vehicleType,'vehicle_number'=>$vehicleNumber,'vehicle_model'=>$vehicleModel,'vehicle_color'=>(string)driver_pick($driver,['vehicleColor','vehicle_color','color','colour'],''),'capacity'=>$driver['capacity']??$driver['seatCapacity']??$driver['seat_capacity']??null,'license_number'=>(string)driver_pick($driver,['licenceNumber','licence_number','licenseNumber','license_number','driverLicenseNumber','driver_license_number'],''),
 'verification_status'=>(string)($driver['verificationStatus']??'pending'),'verification_state'=>driver_verification_state($driver),'is_approved'=>$approved,'is_online'=>$online,'is_blocked'=>driver_bool($driver['isBlocked']??false),'status'=>$status,
 'rating'=>$ratingCount?round(array_sum($values)/$ratingCount,1):null,'rating_count'=>$ratingCount,'completed_rides'=>$completed,'cancelled_rides'=>$cancelled,'acceptance_rate'=>($completed+$cancelled)>0?round($completed/($completed+$cancelled)*100,1):null,
 'earnings'=>$financial['total'],'pending_earnings'=>$financial['pending'],'paid_earnings'=>$financial['paid'],'commission_generated'=>$financial['commission'],'has_documents'=>trim((string)driver_pick($driver,['cnicFrontUrl','cnic_front_url','cnicUploadUrl','cnic_upload_url'],''))!==''||trim((string)driver_pick($driver,['licenceImageUrl','licence_image_url','licenseImageUrl','license_image_url'],''))!=='','cnic_status'=>driver_doc_status($driver,'cnic_front',(string)driver_pick($driver,['cnicFrontUrl','cnic_front_url','cnicUploadUrl','cnic_upload_url'],'')),'licence_status'=>driver_doc_status($driver,'licence',(string)driver_pick($driver,['licenceImageUrl','licence_image_url','licenseImageUrl','license_image_url'],'')),'vehicle_documents_status'=>driver_doc_status($driver,'vehicle_registration',(string)driver_pick($driver,['vehicleRegistrationUrl','vehicle_registration_url','registrationDocumentUrl','registration_document_url'],'')),'profile_photo_status'=>driver_doc_status($driver,'profile_photo',(string)driver_pick($driver,['profilePhotoUrl','profile_photo_url','profileImageUrl','profile_image_url'],'')),'application_date'=>wow_timestamp_to_string($driver['createdAt']??$driver['created_at']??''),'last_active'=>wow_timestamp_to_string($driver['lastOnlineAt']??$driver['last_online_at']??$driver['updatedAt']??$driver['updated_at']??$driver['createdAt']??$driver['created_at']??'')];}

try{
 $mode=driver_norm($_GET['mode']??'list');$ctx=driver_build_context();$profiles=[];$seen=[];
 foreach($ctx['drivers'] as $raw){$uid=(string)($raw['uid']??'');$normalized=wow_normalize_driver_profile($uid,$raw,false)?:$raw;$normalized=array_merge($raw,$normalized);$location=is_array($normalized['currentLocation']??null)?$normalized['currentLocation']:[];$hasHeartbeat=driver_time($normalized['lastOnlineAt']??$normalized['locationUpdatedAt']??$normalized['lastLocationUpdate']??$location['updatedAt']??$location['timestamp']??'')>0;if(!$hasHeartbeat)$normalized['isOnline']=false;$profiles[$uid]=$normalized;$seen[$uid]=true;}
 foreach($ctx['apps'] as $app){$uid=(string)($app['driverId']??$app['userId']??$app['firebaseUid']??$app['uid']??'');if($uid==='')continue;$app['uid']=$uid;if(isset($seen[$uid])){$profiles[$uid]=driver_merge_profile($app,$profiles[$uid]);if(empty($profiles[$uid]['applicationId']))$profiles[$uid]['applicationId']=(string)($app['applicationId']??$app['uid']??'');continue;}$profiles[$uid]=$app;}
 if($mode==='detail'){$uid=trim((string)($_GET['uid']??''));if($uid===''||!isset($profiles[$uid]))drivers_json(['ok'=>false,'error'=>'driver_not_found'],404);$profile=$profiles[$uid];$row=driver_row($profile,$ctx['ridesByDriver'][$uid]??[],$ctx['ratingsByDriver'][$uid]??[],$ctx['paymentsByDriver'][$uid]??[]);unset($row['search_cnic']);$docs=[['key'=>'cnic_front','title'=>'CNIC Front','url'=>(string)driver_pick($profile,['cnicFrontPath','cnicImagePath','cnicFrontUrl','cnic_front_url','cnicUploadUrl','cnic_upload_url','cnicFileUrl','cnic_file_url'],'')],['key'=>'cnic_back','title'=>'CNIC Back','url'=>(string)driver_pick($profile,['cnicBackPath','cnicBackUrl','cnic_back_url'],'')],['key'=>'licence','title'=>'Driving Licence','url'=>(string)driver_pick($profile,['licenceImagePath','licenseImagePath','licencePath','licensePath','licenceImageUrl','licence_image_url','licenseImageUrl','license_image_url','licenceUrl','licenseUrl'],'')],['key'=>'vehicle_registration','title'=>'Vehicle Registration','url'=>(string)driver_pick($profile,['vehicleRegistrationPath','registrationDocumentPath','vehicleDocumentPath','vehicleRegistrationUrl','vehicle_registration_url','registrationDocumentUrl','registration_document_url','vehicleDocumentUrl'],'')],['key'=>'profile_photo','title'=>'Profile Photo','url'=>(string)driver_pick($profile,['profilePhotoPath','profileImagePath','profilePhotoUrl','profile_photo_url','profileImageUrl','profile_image_url','profileImage','photoURL'],'')]];foreach($docs as &$doc){$doc['status']=driver_doc_status($profile,$doc['key'],$doc['url']);$doc['url']=driver_doc_url($doc['url'],$uid,$doc['key']);}unset($doc);
  $passengers=[];foreach(admin_list_collection('passengers',300) as $p)$passengers[(string)($p['uid']??'')]=$p;$reviews=$ctx['ratingsByDriver'][$uid]??[];usort($reviews,static fn($a,$b)=>driver_time($b['updatedAt']??$b['createdAt']??'')<=>driver_time($a['updatedAt']??$a['createdAt']??''));$reviewRows=array_map(static function($r)use($passengers){$pid=(string)($r['passengerId']??$r['passengerUid']??'');$p=$passengers[$pid]??[];return['passenger'=>(string)($p['name']??$p['fullName']??'Passenger'),'rating'=>$r['_numeric'],'review'=>(string)($r['reviewText']??$r['review']??''),'ride_id'=>driver_ride_id($r),'date'=>wow_timestamp_to_string($r['updatedAt']??$r['createdAt']??'')];},array_slice($reviews,0,5));$rideRows=$ctx['ridesByDriver'][$uid]??[];usort($rideRows,static fn($a,$b)=>driver_time($b['completedAt']??$b['updatedAt']??$b['createdAt']??'')<=>driver_time($a['completedAt']??$a['updatedAt']??$a['createdAt']??''));$recent=array_map(static fn($r)=>['ride_id'=>(string)($r['rideCode']??driver_ride_id($r)),'passenger'=>(string)($r['passengerName']??'Passenger'),'pickup'=>driver_location($r['pickup']??$r['pickupAddress']??''),'dropoff'=>driver_location($r['dropoff']??$r['dropoffAddress']??$r['destinationAddress']??''),'date'=>wow_timestamp_to_string($r['completedAt']??$r['updatedAt']??$r['createdAt']??''),'fare'=>driver_money($r),'status'=>(string)($r['status']??'')],array_slice($rideRows,0,5));drivers_json(['ok'=>true,'driver'=>$row,'documents'=>$docs,'recent_reviews'=>$reviewRows,'recent_rides'=>$recent]);}
 $rows=[];$ratingSum=0.0;$ratingCount=0;$summary=['total'=>count($profiles),'online_now'=>0,'pending_approval'=>0,'avg_rating'=>null,'rating_count'=>0];foreach($profiles as $uid=>$profile){$row=driver_row($profile,$ctx['ridesByDriver'][$uid]??[],$ctx['ratingsByDriver'][$uid]??[],$ctx['paymentsByDriver'][$uid]??[]);$rows[]=$row;if($row['is_online'])$summary['online_now']++;if(in_array(driver_norm($row['verification_status']),['pending','under_review','submitted','awaiting_verification'],true)&&!$row['is_approved'])$summary['pending_approval']++;foreach($ctx['ratingsByDriver'][$uid]??[] as $rating){$ratingSum+=(float)$rating['_numeric'];$ratingCount++;}}
 $summary['rating_count']=$ratingCount;$summary['avg_rating']=$ratingCount?round($ratingSum/$ratingCount,1):null;usort($rows,static fn($a,$b)=>driver_time($b['last_active'])<=>driver_time($a['last_active']));$q=driver_norm($_GET['q']??'');$status=driver_norm($_GET['status']??'all');$verification=driver_norm($_GET['verification']??'all');$filtered=array_values(array_filter($rows,static function($r)use($q,$status,$verification){if($status!=='all'&&$status!==''&&driver_norm($r['status'])!==$status)return false;if($verification!=='all'&&$verification!==''&&driver_norm($r['verification_state'])!==$verification)return false;if($q==='')return true;$hay=driver_norm(implode(' ',[$r['driver_id'],$r['name'],$r['email'],$r['phone'],$r['masked_cnic'],$r['search_cnic'],$r['vehicle_type'],$r['vehicle_number'],$r['vehicle_model']]));return str_contains($hay,$q);}));
 if(driver_norm($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=drivers_export_'.date('Ymd_His').'.csv');echo implode(',',['Driver Name','Email','Phone','Masked CNIC','Vehicle Type','Registration Number','Verification Status','Account Status','Online Status','Average Rating','Rating Count','Completed Rides','Driver Earnings','Registration Date','Last Active'])."\n";foreach($filtered as $r)echo implode(',',array_map('driver_csv',[(string)$r['name'],(string)$r['email'],(string)$r['phone'],(string)$r['masked_cnic'],(string)$r['vehicle_type'],(string)$r['vehicle_number'],(string)$r['verification_status'],(string)$r['status'],$r['is_online']?'Online':'Offline',(string)($r['rating']??'Not rated'),(string)$r['rating_count'],(string)$r['completed_rides'],(string)$r['earnings'],(string)$r['application_date'],(string)$r['last_active']]))."\n";exit;}
 $size=max(10,min(20,(int)($_GET['page_size']??15)));$total=count($filtered);$pages=max(1,(int)ceil($total/$size));$page=max(1,min($pages,(int)($_GET['page']??1)));$pageRows=array_slice($filtered,($page-1)*$size,$size);foreach($pageRows as &$pageRow)unset($pageRow['search_cnic']);unset($pageRow);drivers_json(['ok'=>true,'generated_at'=>date('c'),'summary'=>$summary,'drivers'=>$pageRows,'pagination'=>['page'=>$page,'page_size'=>$size,'total'=>$total,'total_pages'=>$pages,'has_prev'=>$page>1,'has_next'=>$page<$pages]]);
}catch(Throwable $e){error_log('Firestore drivers data failed: '.$e->getMessage());drivers_json(['ok'=>false,'error'=>'Unable to load driver data.'],500);}
