<?php declare(strict_types=1);require_once __DIR__.'/auth.php';admin_require_auth();?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lost and Found - Women on Wheels</title><link rel="stylesheet" href="dashboard.css?v=20260802"><link rel="stylesheet" href="dashboard_v2.css?v=20260802"><link rel="stylesheet" href="lost_found.css?v=20260802-3"></head><body class="lf-admin-page"><div class="admin-layout"><?php require __DIR__.'/shared_sidebar.php';?><main class="content"><?php require __DIR__.'/shared_header.php';?>
<section class="lfa-head"><div><h1>Lost &amp; Found Management</h1><p>Review, track and resolve items reported after completed rides.</p></div><button id="lfExport" class="lfa-btn secondary">⇩ Export Data</button></section>
<section class="lfa-kpis"><article><span>▣</span><div><p>Total Cases</p><h3 id="lfTotal">--</h3><small>All reported cases</small></div></article><article><span>⌕</span><div><p>Open Cases</p><h3 id="lfOpen">--</h3><small>Reported, contacted or searching</small></div></article><article><span>✓</span><div><p>Items Found</p><h3 id="lfFound">--</h3><small>Driver-confirmed items</small></div></article><article><span>↗</span><div><p>Awaiting Return</p><h3 id="lfAwaiting">--</h3><small>Found items awaiting handover</small></div></article><article><span>✓</span><div><p>Returned</p><h3 id="lfReturned">--</h3><small>Successfully returned items</small></div></article></section>
<section class="lfa-toolbar"><label class="lfa-search"><span>⌕</span><input id="lfSearch" type="search" placeholder="Search by case ID, ride ID, passenger, driver or item"><button id="lfClear" hidden>×</button></label><select id="lfStatus"><option value="all">All Statuses</option><option value="reported">Reported</option><option value="driver_contacted">Driver Contacted</option><option value="searching">Searching</option><option value="item_found">Item Found</option><option value="return_arranged">Return Arranged</option><option value="returned">Returned</option><option value="closed">Closed</option><option value="not_found">Not Found</option><option value="cancelled">Cancelled</option></select><select id="lfCategory"><option value="all">All Categories</option></select><select id="lfReporter"><option value="all">Reported By: All</option><option value="passenger">Passenger</option><option value="driver">Driver</option></select><select id="lfDate"><option value="all">All Time</option><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="month">This Month</option></select><button id="lfRefresh" class="lfa-btn secondary">↻ Refresh</button></section>
<div id="lfError" class="lfa-empty" hidden><strong>Lost &amp; Found cases could not be loaded.</strong><button id="lfRetry" class="lfa-btn secondary">Retry</button></div>
<section class="lfa-table-panel"><div class="lfa-table-wrap"><table><thead><tr><th>Case</th><th>Passenger</th><th>Driver</th><th>Ride</th><th>Item</th><th>Status</th><th>Reported</th><th>Actions</th></tr></thead><tbody id="lfRows"><tr><td colspan="8"><div class="lfa-skeleton"></div></td></tr></tbody></table></div><footer><span id="lfCount">Loading cases…</span></footer></section>
<div id="lfBackdrop" class="lfa-backdrop" hidden><section id="lfModal" class="lfa-modal" role="dialog" aria-modal="true"><header><div><small>Lost &amp; Found Case</small><h2 id="lfModalTitle">Case</h2><div id="lfModalBadges"></div></div><button id="lfClose" aria-label="Close">×</button></header><div class="lfa-modal-body"><div id="lfDetailLoading" class="lfa-skeleton"></div><div id="lfDetail" hidden><div id="lfSummary" class="lfa-summary"></div><section><h3>Item Information</h3><div id="lfItemInfo" class="lfa-grid"></div></section><section><h3>Passenger and Driver</h3><div id="lfPeople" class="lfa-people"></div></section><section><h3>Ride Information</h3><div id="lfRide" class="lfa-grid"></div></section><section><h3>Case Timeline</h3><div id="lfTimeline" class="lfa-timeline"></div></section><section><h3>Internal Admin Notes</h3><form id="lfNoteForm" class="lfa-note"><textarea id="lfNote" required placeholder="Add an internal note"></textarea><button class="lfa-btn secondary">Save Note</button></form></section></div></div><footer id="lfModalActions"></footer></section></div>
<div id="lfDialogBackdrop" class="lfa-backdrop nested" hidden><section class="lfa-dialog" role="dialog" aria-modal="true"><header><div><small id="lfDialogEyebrow"></small><h2 id="lfDialogTitle"></h2></div><button id="lfDialogClose">×</button></header><form id="lfDialogForm"><div id="lfDialogBody"></div><footer><button type="button" id="lfDialogCancel" class="lfa-btn secondary">Cancel</button><button id="lfDialogSubmit" class="lfa-btn primary">Save</button></footer></form></section></div>
<div id="lfToast" class="lfa-toast" hidden></div>
</main></div><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-auth-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore-compat.js"></script><script src="admin_realtime.js?v=20260802-3"></script><script src="admin_shell.js?v=20260802-2"></script><script src="lost_found.js?v=20260802-3"></script></body></html>
