(function(){"use strict";
const API="lost_found_data.php",S={rows:[],selected:null,detail:null,unsub:null,dialog:null},$=id=>document.getElementById(id),NEXT={reported:["driver_contacted","searching","cancelled"],driver_contacted:["searching","item_found","not_found","cancelled"],searching:["item_found","not_found","cancelled"],item_found:["return_arranged"],return_arranged:["returned"],returned:["closed"],not_found:["closed"],cancelled:["closed"],closed:["reported"]};
document.addEventListener("DOMContentLoaded",init);window.addEventListener("pagehide",()=>{try{S.unsub?.()}catch{}});
async function init(){["lfStatus","lfCategory","lfReporter","lfDate"].forEach(id=>$(id).addEventListener("change",render));let t;$("lfSearch").addEventListener("input",()=>{clearTimeout(t);$("lfClear").hidden=!$("lfSearch").value;t=setTimeout(render,250)});$("lfClear").onclick=()=>{$("lfSearch").value="";$("lfClear").hidden=true;render()};$("lfRefresh").onclick=load;$("lfRetry").onclick=load;$("lfExport").onclick=exportCsv;$("lfRows").addEventListener("click",tableAction);$("lfClose").onclick=close;$("lfBackdrop").onclick=e=>{if(e.target===e.currentTarget)close()};$("lfModalActions").addEventListener("click",modalAction);$("lfNoteForm").addEventListener("submit",saveNote);$("lfDialogClose").onclick=closeDialog;$("lfDialogCancel").onclick=closeDialog;$("lfDialogBackdrop").onclick=e=>{if(e.target===e.currentTarget)closeDialog()};$("lfDialogForm").addEventListener("submit",submitDialog);document.addEventListener("keydown",e=>{if(e.key==="Escape")S.dialog?closeDialog():close()});await load();const id=new URLSearchParams(location.search).get("case");if(id)open(id)}
async function api(body={action:"list"}){const r=await fetch(API,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw Error(j.message||"Lost & Found request failed.");return j}
async function load(){try{$("lfError").hidden=true;const j=await api();S.rows=j.cases||[];categories();render()}catch(e){$("lfError").hidden=false;$("lfRows").innerHTML="";toast(e.message,true)}}
function filtered(){const q=$("lfSearch").value.trim().toLowerCase(),st=$("lfStatus").value,cat=$("lfCategory").value,role=$("lfReporter").value,date=$("lfDate").value,now=Date.now();return S.rows.filter(c=>{if(st!=="all"&&c.status!==st)return false;if(cat!=="all"&&c.category!==cat)return false;if(role!=="all"&&c.reported_by!==role)return false;const t=Date.parse(c.created_at||"");if(date==="today"&&(!t||new Date(t).toDateString()!==new Date().toDateString()))return false;if(date==="7d"&&(!t||now-t>6048e5))return false;if(date==="30d"&&(!t||now-t>2592e6))return false;if(date==="month"&&(!t||new Date(t).getMonth()!==new Date().getMonth()||new Date(t).getFullYear()!==new Date().getFullYear()))return false;return !q||[c.case_id,c.ride_code,c.ride_id,c.passenger_name,c.passenger_email,c.passenger_phone,c.driver_name,c.driver_email,c.item_name,c.category,c.description].join(" ").toLowerCase().includes(q)})}
function render(){set("lfTotal",S.rows.length);set("lfOpen",S.rows.filter(c=>["reported","driver_contacted","searching"].includes(c.status)).length);set("lfFound",S.rows.filter(c=>c.status==="item_found").length);set("lfAwaiting",S.rows.filter(c=>["item_found","return_arranged"].includes(c.status)).length);set("lfReturned",S.rows.filter(c=>c.status==="returned").length);const rows=filtered();set("lfCount",rows.length+" case"+(rows.length===1?"":"s"));$("lfRows").innerHTML=rows.length?rows.map(row).join(""):'<tr><td colspan="8"><div class="lfa-empty"><strong>No cases match the selected filters.</strong><p>Clear filters or refresh data.</p></div></td></tr>'}
function row(c){return `<tr><td><strong>${esc(c.case_id)}</strong><small>Reported by ${esc(c.reported_by)}</small></td><td>${person(c.passenger_name,c.passenger_phone)}</td><td>${person(c.driver_name,c.vehicle)}</td><td><strong>${esc(c.ride_code)}</strong><small>${c.ride_completed_at?"Completed "+date(c.ride_completed_at):"Completion date unavailable"}</small></td><td><strong>${esc(c.item_name)}</strong><small>${esc(c.category+(c.description?" · "+short(c.description):""))}</small></td><td><span class="lfa-status ${esc(c.status)}">${esc(label(c.status))}</span></td><td title="${esc(exact(c.created_at))}">${esc(date(c.created_at))}<small>${esc(time(c.created_at))}</small></td><td><div class="lfa-actions"><button class="lfa-btn primary" data-view="${esc(c.id)}">View</button><button class="lfa-more" data-menu="${esc(c.id)}" aria-label="Case actions">⋮</button><div class="lfa-menu" data-for="${esc(c.id)}" hidden>${menu(c)}</div></div></td></tr>`}
function menu(c){let out=`<button data-view="${esc(c.id)}">View Case</button><button data-contact="passenger" data-id="${esc(c.id)}">Contact Passenger</button>`;if(c.driver_id)out+=`<button data-contact="driver" data-id="${esc(c.id)}">Contact Driver</button>`;if(NEXT[c.status]?.length)out+=`<button data-status-dialog data-id="${esc(c.id)}">Update Status</button>`;if(c.status==="item_found")out+=`<button data-return data-id="${esc(c.id)}">Arrange Return</button>`;return out}
function person(name,sub){return `<div class="lfa-person"><span>${esc(initials(name))}</span><div><strong>${esc(name)}</strong><small>${esc(sub||"Not available")}</small></div></div>`}
function tableAction(e){const more=e.target.closest("[data-menu]");if(more){document.querySelectorAll(".lfa-menu").forEach(m=>m.hidden=m.dataset.for!==more.dataset.menu||!m.hidden);return}const v=e.target.closest("[data-view]");if(v)return open(v.dataset.view);const b=e.target.closest("[data-contact],[data-status-dialog],[data-return]");if(!b)return;const c=S.rows.find(x=>x.id===b.dataset.id);if(b.dataset.contact)contactDialog(c,b.dataset.contact);else if(b.hasAttribute("data-status-dialog"))statusDialog(c);else returnDialog(c)}
async function open(id){S.selected=id;$("lfBackdrop").hidden=false;document.body.style.overflow="hidden";$("lfDetailLoading").hidden=false;$("lfDetail").hidden=true;try{S.detail=await api({action:"detail",id});drawDetail()}catch(e){toast(e.message,true)}}
function drawDetail(){const c=S.detail.case;$("lfDetailLoading").hidden=true;$("lfDetail").hidden=false;set("lfModalTitle",c.case_id);$("lfModalBadges").innerHTML=`<span class="lfa-status ${c.status}">${esc(label(c.status))}</span> <span class="lfa-chip">${esc(c.category)}</span>`;$("lfSummary").innerHTML=facts([["Current Status",label(c.status)],["Reported Date",exact(c.created_at)],["Ride ID",c.ride_code],["Reported By",label(c.reported_by)]]);$("lfItemInfo").innerHTML=facts([["Item Name",c.item_name],["Category",c.category],["Description",c.description],["Color",c.color||"Not provided"],["Last Seen",c.last_seen||"Not provided"],["Photo",c.photo?"Photo uploaded":"No photo uploaded"]]);$("lfPeople").innerHTML=profile("Passenger",c.passenger_name,c.passenger_phone,c.passenger_email)+profile("Driver",c.driver_name,c.driver_phone,c.vehicle)+`<div class="lfa-profile"><strong>Driver response</strong><span>${esc(c.driver_response)}</span></div>`;$("lfRide").innerHTML=facts([["Ride ID",c.ride_code],["Pickup",c.pickup||"Not available"],["Drop-off",c.dropoff||"Not available"],["Completed",exact(c.ride_completed_at)],["Vehicle",c.vehicle],["Final fare",c.fare?"Rs. "+Number(c.fare).toLocaleString():"Not available"]]);$("lfTimeline").innerHTML=(S.detail.timeline||[]).length?S.detail.timeline.map(x=>`<div><strong>${esc(x.event||label(x.status))}</strong><span>${esc(exact(x.created_at))}${x.admin?" · "+esc(x.admin):""}</span></div>`).join(""):'<p>No timeline events available.</p>';drawActions(c)}
function drawActions(c){let out=`<button class="lfa-btn secondary" data-contact-modal="passenger">Contact Passenger</button>`;if(c.driver_id)out+=`<button class="lfa-btn secondary" data-contact-modal="driver">Contact Driver</button>`;if(NEXT[c.status]?.length)out+=`<button class="lfa-btn primary" data-update-status>Update Status</button>`;if(c.status==="item_found")out+=`<button class="lfa-btn primary" data-arrange>Arrange Return</button>`;out+='<button class="lfa-btn secondary" data-close>Close</button>';$("lfModalActions").innerHTML=out}
function modalAction(e){const c=S.detail?.case;if(e.target.closest("[data-close]"))close();else if(e.target.closest("[data-contact-modal]"))contactDialog(c,e.target.closest("[data-contact-modal]").dataset.contactModal);else if(e.target.closest("[data-update-status]"))statusDialog(c);else if(e.target.closest("[data-arrange]"))returnDialog(c)}
function contactDialog(c,role){const name=role==="driver"?c.driver_name:c.passenger_name,def=role==="driver"?`A passenger reported a lost item linked to ride ${c.ride_code}. Please check your vehicle and respond through the Lost & Found section.`:"The Women on Wheels support team is reviewing your Lost & Found case.";dialog("Contact "+label(role),`${name} · ${c.case_id}`,`<label>Message<textarea name="message" required>${esc(def)}</textarea></label><input type="hidden" name="role" value="${role}">`,{action:"contact",caseId:c.id})}
function statusDialog(c){const opts=(NEXT[c.status]||[]).map(s=>`<option value="${s}">${label(s)}</option>`).join("");dialog("Update Case Status","Current status: "+label(c.status),`<label>Change to<select name="status" required>${opts}</select></label><label>Reason / notes<textarea name="notes" placeholder="Required for Not Found, Cancelled, Closed or Reopen"></textarea></label>`,{action:"status",caseId:c.id})}
function returnDialog(c){dialog("Arrange Return",c.case_id,`<label>Return Method<select name="returnMethod" required><option value="">Select method</option><option>Driver will return item</option><option>Passenger will collect</option><option>Meet at agreed location</option><option>Women on Wheels support handover</option><option>Other</option></select></label><label>Return Date and Time<input type="datetime-local" name="returnScheduledAt" required></label><label>Return Location<input name="returnLocation" required></label><label>Notes<textarea name="notes"></textarea></label>`,{action:"arrange_return",caseId:c.id})}
function dialog(title,sub,body,payload){S.dialog=payload;set("lfDialogTitle",title);set("lfDialogEyebrow",sub);$("lfDialogBody").innerHTML=body;$("lfDialogBackdrop").hidden=false}
async function submitDialog(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());try{$("lfDialogSubmit").disabled=true;await api({...S.dialog,...data});closeDialog();toast("Case updated successfully.");await load();if(S.selected){S.detail=await api({action:"detail",id:S.selected});drawDetail()}}catch(err){toast(err.message,true)}finally{$("lfDialogSubmit").disabled=false}}
async function saveNote(e){e.preventDefault();try{await api({action:"note",id:S.selected,notes:$("lfNote").value});$("lfNote").value="";S.detail=await api({action:"detail",id:S.selected});drawDetail();toast("Internal note saved.")}catch(err){toast(err.message,true)}}
function close(){if($("lfBackdrop").hidden)return;$("lfBackdrop").hidden=true;document.body.style.overflow="";S.selected=null;S.detail=null}function closeDialog(){$("lfDialogBackdrop").hidden=true;S.dialog=null;$("lfDialogForm").reset()}
function categories(){const current=$("lfCategory").value,cats=[...new Set(S.rows.map(c=>c.category).filter(Boolean))].sort();$("lfCategory").innerHTML='<option value="all">All Categories</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join("");if(cats.includes(current))$("lfCategory").value=current}
function exportCsv(){const head=["Case ID","Ride ID","Passenger","Driver","Item Name","Category","Description","Status","Reported By","Source Platform","Reported At","Driver Contacted At","Driver Response","Found At","Return Method","Return Scheduled At","Returned At","Closed At","Closure Reason"],rows=filtered().map(c=>[c.case_id,c.ride_code,c.passenger_name,c.driver_name,c.item_name,c.category,c.description,label(c.status),c.reported_by,c.source,c.created_at,c.driver_contacted_at,c.driver_response,c.found_at,c.return_method,c.return_scheduled_at,c.returned_at,c.closed_at,c.closure_reason]);download([head,...rows].map(r=>r.map(csv).join(",")).join("\r\n"))}
function facts(a){return a.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v||"Not available")}</strong></div>`).join("")}function profile(t,n,p,x){return `<div class="lfa-profile"><strong>${esc(t)}</strong><span>${esc(n)}</span><span>${esc(p||"Contact unavailable")}</span><span>${esc(x||"")}</span></div>`}function label(v){return String(v||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())}function initials(v){return String(v||"?").split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()}function short(v){return String(v||"").length>48?String(v).slice(0,48)+"…":v}function date(v){const d=new Date(v);return isNaN(d)?"Date unavailable":d.toLocaleDateString("en-PK",{day:"numeric",month:"short",year:"numeric"})}function time(v){const d=new Date(v);return isNaN(d)?"":d.toLocaleTimeString("en-PK",{hour:"numeric",minute:"2-digit"})}function exact(v){const d=new Date(v);return isNaN(d)?"Date unavailable":d.toLocaleString("en-PK",{dateStyle:"medium",timeStyle:"short"})}function set(id,v){$(id).textContent=String(v)}function toast(m,bad){const n=$("lfToast");n.textContent=m;n.classList.toggle("bad",!!bad);n.hidden=false;setTimeout(()=>n.hidden=true,3200)}function csv(v){return '"'+String(v??"").replace(/"/g,'""')+'"'}function download(t){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:"text/csv"}));a.download="wow-lost-found.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
})();
