<?php declare(strict_types=1);require_once __DIR__.'/auth.php';admin_require_auth();if(strtolower(trim((string)($_GET['view']??'')))==='driver-earnings'){header('Location: driver_earnings.php',true,302);exit;}?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payments - Women on Wheels</title><link rel="stylesheet" href="dashboard.css?v=20260802"><link rel="stylesheet" href="dashboard_v2.css?v=20260802"><link rel="stylesheet" href="payments.css?v=20260802-3"></head><body class="pay-page"><div class="admin-layout"><?php require __DIR__.'/shared_sidebar.php';?><main class="content"><?php require __DIR__.'/shared_header.php';?>
<section class="pay-head"><div><h1>Payments</h1><p>Monitor ride payments, platform commission and driver earnings.</p></div><button id="payExport" class="pay-btn secondary">⇩ Export Data</button></section>
<section class="pay-kpis"><article><span>Rs</span><div><p>Gross Ride Revenue</p><h3 id="payGross">--</h3><small>Confirmed completed ride payments</small></div></article><article><span>30%</span><div><p>WOW Commission</p><h3 id="payCommission">--</h3><small>30% platform commission</small></div></article><article><span>70%</span><div><p>Driver Earnings</p><h3 id="payDrivers">--</h3><small>70% driver share</small></div></article><article><span>⌛</span><div><p>Pending Online Payments</p><h3 id="payPending">--</h3><small>Completed online rides awaiting confirmation</small></div></article><article><span>↩</span><div><p>Refunded Amount</p><h3 id="payRefunded">--</h3><small>Confirmed refunds and reversals</small></div></article></section>
<section class="pay-chart-panel"><header><div><h2>Revenue by Day</h2><p>Confirmed net ride payment activity</p></div></header><div id="payChart" class="pay-chart"><div class="pay-skeleton"></div></div></section>
<section class="pay-toolbar"><label class="pay-search"><span>⌕</span><input id="paySearch" type="search" placeholder="Search by payment ID, ride ID, passenger or driver"><button id="payClear" hidden>×</button></label><select id="payStatus"><option value="all">All Statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option><option value="reversed">Reversed</option></select><select id="payMethod"><option value="all">All Methods</option><option>Cash</option><option>Easypaisa</option><option>JazzCash</option><option>NayaPay</option><option>Online</option></select><select id="payDate"><option value="all">All Time</option><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="month">This Month</option><option value="year">This Year</option></select><select id="payType"><option value="all">All Ride Types</option><option value="instant">Instant</option><option value="scheduled">Scheduled</option><option value="carpool">Carpool</option></select><button id="payRefresh" class="pay-btn secondary">↻ Refresh</button></section>
<div id="payError" class="pay-empty" hidden><strong>Payment data could not be loaded.</strong><button id="payRetry" class="pay-btn secondary">Retry</button></div><section class="pay-table-panel"><div class="pay-table-wrap"><table><thead><tr><th>Payment</th><th>Ride</th><th>Passenger</th><th>Driver</th><th>Fare Breakdown</th><th>Method</th><th>Payment Status</th><th>Date</th><th>Actions</th></tr></thead><tbody id="payRows"><tr><td colspan="9"><div class="pay-skeleton"></div></td></tr></tbody></table></div><footer><span id="payCount">Loading payments…</span></footer></section>
<div id="payBackdrop" class="pay-backdrop" hidden><section class="pay-modal"><header><div><small>Payment Details</small><h2 id="payModalTitle">Payment</h2><div id="payModalBadges"></div></div><button id="payClose">×</button></header><div class="pay-modal-body"><section><h3>Ride Information</h3><div id="payRideInfo" class="pay-grid"></div></section><section><h3>Passenger and Driver</h3><div id="payPeople" class="pay-people"></div></section><section><h3>Fare Breakdown</h3><div id="payFareInfo" class="pay-grid"></div></section><section><h3>Payment Information</h3><div id="payPaymentInfo" class="pay-grid"></div></section><section id="payRefundSection" hidden><h3>Refund Information</h3><div id="payRefundInfo" class="pay-grid"></div></section></div><footer id="payModalActions"></footer></section></div>
<div id="payDialogBackdrop" class="pay-backdrop nested" hidden><section class="pay-dialog"><header><div><small>Payment Action</small><h2 id="payDialogTitle"></h2></div><button id="payDialogClose">×</button></header><form id="payDialogForm"><div id="payDialogBody"></div><footer><button type="button" id="payDialogCancel" class="pay-btn secondary">Cancel</button><button class="pay-btn primary">Confirm</button></footer></form></section></div><div id="payToast" class="pay-toast" hidden></div>
</main></div><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-auth-compat.js"></script><script src="https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore-compat.js"></script><script src="admin_realtime.js?v=20260802-5"></script><script src="admin_shell.js?v=20260802-2"></script><script src="payments.js?v=20260802-3"></script></body></html>
