<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
require_once __DIR__.'/db.php';
admin_require_auth();
date_default_timezone_set('Asia/Karachi');

function rm_json(array $data,int $status=200):void{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_SLASHES);exit;}
function rm_norm($v):string{return strtolower(trim((string)$v));}
function rm_bool($v):bool{return filter_var($v,FILTER_VALIDATE_BOOLEAN);}
function rm_time($v):int{if($v instanceof \Google\Cloud\Core\Timestamp)return $v->get()->getTimestamp();if($v instanceof DateTimeInterface)return $v->getTimestamp();if(is_numeric($v)){$n=(int)$v;return $n>20000000000?(int)floor($n/1000):$n;}$t=strtotime((string)$v);return $t?:0;}
function rm_date($v):string{$t=rm_time($v);return $t?date(DATE_ATOM,$t):'';}
function rm_text($v):string{if(is_string($v)||is_numeric($v))return trim((string)$v);if(is_array($v)){foreach(['address','formattedAddress','name','label','placeName','description'] as $k)if(trim((string)($v[$k]??''))!=='')return trim((string)$v[$k]);}return'';}
function rm_num(array $r,array $keys):?float{foreach($keys as $k)if(array_key_exists($k,$r)&&is_numeric($r[$k])){$n=(float)$r[$k];if(is_finite($n))return round($n,2);}return null;}
function rm_id(array $r):string{return trim((string)($r['rideId']??$r['bookingId']??$r['requestId']??$r['uid']??''));}
function rm_doc_id(array $r):string{return trim((string)($r['uid']??$r['rideId']??$r['bookingId']??$r['requestId']??''));}
function rm_group(string $s,bool $scheduled=false):string{$s=rm_norm($s);if(in_array($s,['completed','ride_completed','finished','success','successful'],true))return'completed';if(str_starts_with($s,'cancelled')||str_starts_with($s,'canceled')||in_array($s,['rejected','expired','declined','no_driver_found'],true))return'cancelled';if(in_array($s,['accepted','driver_assigned','driver_selected','driver_arriving','arrived','started','in_progress','ongoing','ride_started'],true))return'active';if($scheduled||in_array($s,['scheduled','upcoming','scheduled_pending'],true))return'scheduled';if(in_array($s,['pending','waiting','requested','searching','searching_driver','awaiting_driver','awaiting_driver_acceptance','offer_pending','counter_offer_pending','driver_responded'],true))return'waiting';return'waiting';}
function rm_real(array $r):bool{$id=rm_norm(rm_id($r));return $id!==''&&!str_starts_with($id,'test_')&&!rm_bool($r['isDemo']??false)&&!rm_bool($r['deleted']??$r['isDeleted']??false);}
function rm_profile(array $p,string $fallback):array{return['name'=>(string)($p['fullName']??$p['name']??$fallback),'email'=>(string)($p['email']??''),'phone'=>(string)($p['phoneNumber']??$p['phone']??''),'photo'=>(string)($p['photoURL']??$p['profileImageUrl']??$p['profilePhotoUrl']??''),'rating'=>$p['averageRating']??$p['rating']??null];}
function rm_row(array $r,array $passengers,array $drivers,array $payments,array $sos):array{
 $doc=rm_doc_id($r);$rid=rm_id($r)?:$doc;$pid=trim((string)($r['passengerId']??$r['passengerUid']??$r['userId']??''));$did=trim((string)($r['assignedDriverId']??$r['driverId']??$r['driverUid']??$r['respondingDriverId']??''));
 $p=rm_profile($passengers[$pid]??[],(string)($r['passengerName']??'Passenger'));$d=rm_profile($drivers[$did]??[],(string)($r['driverName']??$r['respondingDriverName']??($did?'Driver':'Waiting for driver')));
 $pickup=rm_text($r['pickupAddress']??$r['pickupLocation']??$r['pickup']??$r['origin']??'');$drop=rm_text($r['dropoffAddress']??$r['dropOffAddress']??$r['destinationAddress']??$r['dropoff']??$r['destination']??'');
 $scheduled=rm_time($r['scheduledAt']??$r['scheduledDateTime']??$r['scheduledDate']??null)>0;$carpool=rm_bool($r['isCarpool']??false)||str_contains(rm_norm($r['rideType']??''),'carpool');$status=rm_norm($r['status']??$r['rideStatus']??$r['bookingStatus']??$r['requestStatus']??'pending');$group=rm_group($status,$scheduled);if($group==='scheduled'&&rm_time($r['scheduledAt']??null)<time()&&!in_array($status,['scheduled','upcoming','scheduled_pending'],true))$group=rm_group($status,false);
 $pay=$payments[$doc]??$payments[$rid]??[];$alert=$sos[$doc]??$sos[$rid]??[];$fare=rm_num($r,['finalFare','acceptedFare','agreedFare','fare','estimatedFare','passengerOffer','offeredFare']);
 $type=$carpool?'carpool':($scheduled?'scheduled':'instant');$created=$r['createdAt']??$r['requestedAt']??$r['bookingCreatedAt']??null;
 return['id'=>$doc,'ride_id'=>$rid,'ride_code'=>(string)($r['rideCode']??$r['bookingCode']??$rid),'passenger_id'=>$pid,'driver_id'=>$did,'passenger'=>$p,'driver'=>$d,'pickup'=>$pickup?:'Not available','dropoff'=>$drop?:'Not available','status'=>$status,'status_group'=>$group,'status_label'=>ucwords(str_replace('_',' ',match($status){'ride_started','started','in_progress'=>'in progress','ride_completed'=>'completed','driver_selected','driver_assigned'=>'driver assigned','searching_driver','awaiting_driver','awaiting_driver_acceptance'=>'waiting for driver',default=>$status?:'waiting'})),'ride_type'=>$type,'vehicle_type'=>(string)($r['vehicleType']??$r['requestedVehicleType']??$r['driverVehicleType']??''),'distance_km'=>rm_num($r,['distanceKm','totalDistanceKm','distance']),'duration_min'=>rm_num($r,['durationMin','durationMinutes','totalDurationMinutes']),'fare'=>$fare,'initial_offer'=>rm_num($r,['passengerOffer','passengerOfferFare','offeredFare','estimatedFare']),'driver_offer'=>rm_num($r,['driverOffer','driverOfferFare','counterOfferFare']),'payment_method'=>(string)($pay['paymentMethod']??$r['paymentMethod']??''),'payment_status'=>(string)($pay['paymentStatus']??$pay['status']??$r['paymentStatus']??''),'created_at'=>rm_date($created),'scheduled_at'=>rm_date($r['scheduledAt']??$r['scheduledDateTime']??$r['scheduledDate']??null),'accepted_at'=>rm_date($r['acceptedAt']??$r['driverConfirmedAt']??$r['matchedAt']??null),'arrived_at'=>rm_date($r['arrivedAt']??null),'started_at'=>rm_date($r['startedAt']??null),'completed_at'=>rm_date($r['completedAt']??$r['endedAt']??$r['rideCompletedAt']??null),'cancelled_at'=>rm_date($r['cancelledAt']??$r['canceledAt']??($group==='cancelled'?($r['updatedAt']??null):null)),'sos_active'=>!empty($alert)&&!in_array(rm_norm($alert['status']??''),['resolved','closed','cancelled'],true),'sos_id'=>(string)($alert['uid']??$alert['alertId']??''),'coordinates'=>['pickup'=>['lat'=>$r['pickupLatitude']??$r['pickupLat']??null,'lng'=>$r['pickupLongitude']??$r['pickupLng']??null],'dropoff'=>['lat'=>$r['dropoffLatitude']??$r['destinationLatitude']??$r['dropLat']??null,'lng'=>$r['dropoffLongitude']??$r['destinationLongitude']??$r['dropLng']??null]],'carpool'=>['original_fare'=>rm_num($r,['originalFare','totalFare']),'shared_fare'=>rm_num($r,['sharedFare','individualFare']),'passengers'=>$r['totalPassengers']??count((array)($r['passengerIds']??[]))],'raw_collection'=>(string)($r['_collection']??'rides')];
}
try{
 // The connected passenger and driver platforms use `rides` as the canonical
 // ride document. Loading six speculative legacy collections made the initial
 // admin request take tens of seconds even when those collections were empty.
 $sources=[];foreach(admin_list_collection('rides',300) as $r){$r['_collection']='rides';if(rm_real($r))$sources[]=$r;}
 $merged=[];foreach($sources as $r){$key=rm_id($r)?:rm_doc_id($r);$old=$merged[$key]??null;if(!$old||rm_time($r['updatedAt']??$r['createdAt']??null)>=rm_time($old['updatedAt']??$old['createdAt']??null))$merged[$key]=$r;}
 $passengers=[];foreach(admin_list_collection('passengers',500) as $p)$passengers[(string)($p['uid']??'')]=$p;$drivers=[];foreach(admin_list_collection('drivers',500) as $d)$drivers[(string)($d['uid']??'')]=$d;
 $payments=[];foreach(admin_list_collection('payments',500) as $p){$k=(string)($p['rideId']??$p['uid']??'');if($k!=='')$payments[$k]=$p;}$sos=[];foreach(admin_list_collection('sosAlerts',200) as $a){$k=(string)($a['rideId']??$a['rideCode']??'');if($k!=='')$sos[$k]=$a;}
 $rows=[];foreach($merged as $r)try{$rows[]=rm_row($r,$passengers,$drivers,$payments,$sos);}catch(Throwable $e){error_log('[Ride Monitoring] malformed ride '.rm_doc_id($r).': '.$e->getMessage());}
 usort($rows,static fn($a,$b)=>rm_time($b['created_at']?:$b['scheduled_at'])<=>rm_time($a['created_at']?:$a['scheduled_at']));$today=date('Y-m-d');$summary=['active_now'=>0,'scheduled'=>0,'completed_today'=>0,'cancelled_today'=>0];foreach($rows as $x){if($x['status_group']==='active')$summary['active_now']++;if($x['status_group']==='scheduled'&&(!$x['scheduled_at']||rm_time($x['scheduled_at'])>=time()))$summary['scheduled']++;if($x['status_group']==='completed'&&str_starts_with($x['completed_at'],$today))$summary['completed_today']++;if($x['status_group']==='cancelled'&&str_starts_with($x['cancelled_at'],$today))$summary['cancelled_today']++;}
 $mode=rm_norm($_GET['mode']??'list');if($mode==='detail'){$id=trim((string)($_GET['id']??''));foreach($rows as $x)if($x['id']===$id||$x['ride_id']===$id||$x['ride_code']===$id)rm_json(['ok'=>true,'ride'=>$x]);rm_json(['ok'=>false,'error'=>'ride_not_found'],404);}
 $q=rm_norm($_GET['q']??'');$status=rm_norm($_GET['status']??'all');$type=rm_norm($_GET['type']??'all');$vehicle=rm_norm($_GET['vehicle']??'all');$date=rm_norm($_GET['date']??'all');$from=match($date){'today'=>strtotime('today'),'7d'=>strtotime('-6 days midnight'),'30d'=>strtotime('-29 days midnight'),'month'=>strtotime('first day of this month midnight'),default=>0};$filtered=array_values(array_filter($rows,static function($x)use($q,$status,$type,$vehicle,$from){if($status!=='all'&&$x['status_group']!==$status)return false;if($type!=='all'&&$x['ride_type']!==$type)return false;if($vehicle!=='all'&&rm_norm($x['vehicle_type'])!==$vehicle)return false;if($from&&rm_time($x['created_at']?:$x['scheduled_at'])<$from)return false;if(!$q)return true;$hay=rm_norm(implode(' ',[$x['ride_id'],$x['ride_code'],$x['passenger']['name'],$x['passenger']['email'],$x['passenger']['phone'],$x['driver']['name'],$x['driver']['email'],$x['pickup'],$x['dropoff']]));return str_contains($hay,$q);}));
 if(rm_norm($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=rides_'.date('Ymd_His').'.csv');$out=fopen('php://output','w');fputcsv($out,['Ride ID','Ride Type','Passenger','Driver','Pickup','Drop-off','Vehicle','Fare','Payment Method','Payment Status','Ride Status','Scheduled Time','Created Time','Started Time','Completed Time','Cancelled Time','SOS Status']);foreach($filtered as $x)fputcsv($out,[$x['ride_code'],$x['ride_type'],$x['passenger']['name'],$x['driver']['name'],$x['pickup'],$x['dropoff'],$x['vehicle_type'],$x['fare'],$x['payment_method'],$x['payment_status'],$x['status'],$x['scheduled_at'],$x['created_at'],$x['started_at'],$x['completed_at'],$x['cancelled_at'],$x['sos_active']?'Active':'None']);fclose($out);exit;}
 $size=max(10,min(20,(int)($_GET['page_size']??15)));$total=count($filtered);$pages=max(1,(int)ceil($total/$size));$page=max(1,min($pages,(int)($_GET['page']??1)));rm_json(['ok'=>true,'summary'=>$summary,'rides'=>array_slice($filtered,($page-1)*$size,$size),'pagination'=>['page'=>$page,'page_size'=>$size,'total'=>$total,'total_pages'=>$pages,'has_prev'=>$page>1,'has_next'=>$page<$pages],'collections'=>array_values(array_unique(array_column($sources,'_collection')))]);
}catch(Throwable $e){error_log('[Ride Monitoring] '.$e->getMessage());rm_json(['ok'=>false,'error'=>'Ride data could not be loaded.'],500);}
