<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php'; require_once __DIR__.'/db.php'; admin_require_auth();
date_default_timezone_set('Asia/Karachi');
function srj(array$x,int$s=200):void{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($x,JSON_UNESCAPED_SLASHES);exit;}
function srn($v):string{return strtolower(trim((string)$v));}
function srb($v):bool{return filter_var($v,FILTER_VALIDATE_BOOLEAN);}
function srt($v):int{if($v instanceof \Google\Cloud\Core\Timestamp)return$v->get()->getTimestamp();if($v instanceof DateTimeInterface)return$v->getTimestamp();if(is_numeric($v)){$n=(int)$v;return$n>20000000000?(int)floor($n/1000):$n;}$t=strtotime((string)$v);return$t?:0;}
function srd($v):string{$t=srt($v);return$t?date(DATE_ATOM,$t):'';}
function srs($v):string{if(is_string($v)||is_numeric($v))return trim((string)$v);if(is_array($v))foreach(['address','formattedAddress','name','label','placeName']as$k)if(trim((string)($v[$k]??''))!=='')return trim((string)$v[$k]);return'';}
function srm(array$r,array$k):?float{foreach($k as$x)if(array_key_exists($x,$r)&&is_numeric($r[$x]))return round((float)$r[$x],2);return null;}
function srid(array$r):string{return trim((string)($r['rideId']??$r['bookingId']??$r['requestId']??$r['uid']??''));}
function sr_is(array$r):bool{$type=srn($r['rideType']??$r['bookingType']??$r['requestType']??$r['scheduleType']??'');return srb($r['isScheduled']??false)||srb($r['scheduled']??false)||in_array($type,['scheduled','schedule','advance','prebooked'],true)||srt($r['scheduledAt']??$r['scheduledDateTime']??$r['scheduledDate']??$r['pickupTime']??null)>0;}
function sr_group(array$r):string{$s=srn($r['status']??$r['rideStatus']??$r['bookingStatus']??'');$time=srt($r['scheduledAt']??$r['scheduledDateTime']??$r['scheduledDate']??$r['pickupTime']??null);$driver=trim((string)($r['assignedDriverId']??$r['driverId']??$r['driverUid']??''));if(in_array($s,['completed','ride_completed','finished','success','successful'],true))return'completed';if(str_starts_with($s,'cancelled')||str_starts_with($s,'canceled')||in_array($s,['rejected','declined'],true))return'cancelled';if(in_array($s,['expired','missed','no_driver_found'],true))return'expired';if(in_array($s,['driver_arriving','arrived','started','in_progress','ongoing','ride_started'],true))return'active';if($driver!==''||in_array($s,['accepted','assigned','driver_assigned','confirmed_by_driver','driver_selected'],true))return'assigned';if($time>0&&$time<time())return'expired';if(in_array($s,['pending','waiting','requested','searching','searching_driver','awaiting_driver','awaiting_driver_acceptance','offer_pending'],true))return'awaiting_driver';return'upcoming';}
function sr_profile(array$p,string$f):array{return['name'=>(string)($p['fullName']??$p['name']??$f),'email'=>(string)($p['email']??''),'phone'=>(string)($p['phoneNumber']??$p['phone']??''),'rating'=>$p['averageRating']??$p['rating']??null,'vehicle'=>(string)($p['vehicleModel']??$p['vehicleName']??''),'plate'=>(string)($p['vehicleNumber']??'')];}
function sr_row(array$r,array$pass,array$drivers,array$payments):array{$id=(string)($r['uid']??srid($r));$rid=srid($r)?:$id;$pid=(string)($r['passengerId']??$r['passengerUid']??$r['userId']??'');$did=(string)($r['assignedDriverId']??$r['driverId']??$r['driverUid']??'');$p=sr_profile($pass[$pid]??[],(string)($r['passengerName']??'Passenger profile unavailable'));$d=sr_profile($drivers[$did]??[],(string)($r['driverName']??($did?'Driver':'Awaiting driver')));$pay=$payments[$id]??$payments[$rid]??[];$group=sr_group($r);$fare=srm($r,['finalFare','acceptedFare','agreedFare','fare','estimatedFare']);$scheduled=srd($r['scheduledAt']??$r['scheduledDateTime']??$r['scheduledDate']??$r['pickupTime']??null);$carpool=srb($r['isCarpool']??false)||str_contains(srn($r['rideType']??''),'carpool');return['id'=>$id,'ride_id'=>$rid,'ride_code'=>(string)($r['rideCode']??$r['bookingCode']??$rid),'passenger_id'=>$pid,'driver_id'=>$did,'passenger'=>$p,'driver'=>$d,'group'=>$group,'status'=>(string)($r['status']??''),'label'=>match($group){'awaiting_driver'=>'Awaiting Driver','assigned'=>'Driver Assigned','active'=>'In Progress',default=>ucwords(str_replace('_',' ',$group))},'carpool'=>$carpool,'pickup'=>srs($r['pickupAddress']??$r['pickupLocation']??$r['pickup']??'')?:'Not available','dropoff'=>srs($r['dropoffAddress']??$r['destinationAddress']??$r['dropoff']??$r['destination']??'')?:'Not available','vehicle'=>(string)($r['vehicleType']??$r['requestedVehicleType']??''),'distance'=>srm($r,['distanceKm','totalDistanceKm','distance']),'duration'=>srm($r,['durationMin','durationMinutes','totalDurationMinutes']),'offer'=>srm($r,['passengerOffer','passengerOfferFare','offeredFare','estimatedFare']),'driver_offer'=>srm($r,['driverOffer','counterOfferFare']),'fare'=>$fare,'fare_label'=>$group==='completed'?'Final':($did?'Agreed':'Estimated'),'payment_method'=>(string)($pay['paymentMethod']??$r['paymentMethod']??''),'payment_status'=>(string)($pay['paymentStatus']??$pay['status']??$r['paymentStatus']??''),'scheduled_at'=>$scheduled,'created_at'=>srd($r['createdAt']??$r['requestedAt']??null),'assigned_at'=>srd($r['acceptedAt']??$r['driverConfirmedAt']??$r['matchedAt']??null),'started_at'=>srd($r['startedAt']??null),'completed_at'=>srd($r['completedAt']??$r['rideCompletedAt']??null),'cancelled_at'=>srd($r['cancelledAt']??$r['canceledAt']??($group==='cancelled'?($r['updatedAt']??null):null)),'urgent'=>in_array($group,['upcoming','awaiting_driver','assigned'],true)&&srt($scheduled)>time()&&srt($scheduled)-time()<=1800,'source'=>(string)($r['_collection']??'rides')];}
try{$src=[];foreach(['rides','rideRequests','scheduledRides','bookings']as$c)foreach(admin_list_collection($c,1500)as$r){$r['_collection']=$c;if(sr_is($r)&&!srb($r['isDemo']??false)&&!srb($r['deleted']??$r['isDeleted']??false))$src[]=$r;}$merged=[];foreach($src as$r){$k=srid($r);if($k==='')continue;$old=$merged[$k]??null;if(!$old||srt($r['updatedAt']??$r['createdAt']??null)>=srt($old['updatedAt']??$old['createdAt']??null))$merged[$k]=$r;}$pass=[];foreach(admin_list_collection('passengers',1000)as$p)$pass[(string)($p['uid']??'')]=$p;$drivers=[];foreach(admin_list_collection('drivers',1000)as$d)$drivers[(string)($d['uid']??'')]=$d;$payments=[];foreach(admin_list_collection('payments',1000)as$p){$k=(string)($p['rideId']??'');if($k)$payments[$k]=$p;}$rows=[];foreach($merged as$r)try{$rows[]=sr_row($r,$pass,$drivers,$payments);}catch(Throwable$e){error_log('[Scheduled Rides] malformed '.srid($r).': '.$e->getMessage());}usort($rows,static fn($a,$b)=>srt($a['scheduled_at'])<=>srt($b['scheduled_at']));$today=date('Y-m-d');$summary=['upcoming'=>0,'awaiting_driver'=>0,'assigned'=>0,'completed_today'=>0,'cancelled_today'=>0,'expired'=>0];foreach($rows as$x){if(isset($summary[$x['group']]))$summary[$x['group']]++;if($x['group']==='completed'&&str_starts_with($x['completed_at'],$today))$summary['completed_today']++;if($x['group']==='cancelled'&&str_starts_with($x['cancelled_at'],$today))$summary['cancelled_today']++;}
$q=srn($_GET['q']??'');$status=srn($_GET['status']??'all');$date=srn($_GET['date']??'all');$assign=srn($_GET['assignment']??'all');$now=time();$filtered=array_values(array_filter($rows,static function($x)use($q,$status,$date,$assign,$now){if($status!=='all'&&$x['group']!==$status)return false;if($assign==='assigned'&&$x['driver_id']==='')return false;if($assign==='unassigned'&&$x['driver_id']!=='')return false;if($assign==='awaiting'&&$x['group']!=='awaiting_driver')return false;$t=srt($x['scheduled_at']);if($date==='today'&&date('Y-m-d',$t)!==date('Y-m-d'))return false;if($date==='tomorrow'&&date('Y-m-d',$t)!==date('Y-m-d',strtotime('+1 day')))return false;if($date==='7d'&&($t<$now||$t>strtotime('+7 days')))return false;if($date==='30d'&&($t<$now||$t>strtotime('+30 days')))return false;if($date==='past'&&$t>=$now)return false;if(!$q)return true;return str_contains(srn(implode(' ',[$x['ride_code'],$x['passenger']['name'],$x['passenger']['email'],$x['passenger']['phone'],$x['driver']['name'],$x['driver']['email'],$x['pickup'],$x['dropoff']])), $q);}));
if(srn($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=scheduled_rides_'.date('Ymd_His').'.csv');$o=fopen('php://output','w');fputcsv($o,['Ride ID','Passenger','Driver','Pickup','Drop-off','Scheduled Date Time','Vehicle','Ride Type','Passenger Offer','Final Fare','Payment Method','Payment Status','Ride Status','Created At','Driver Assigned At','Started At','Completed At','Cancelled At']);foreach($filtered as$x)fputcsv($o,[$x['ride_code'],$x['passenger']['name'],$x['driver']['name'],$x['pickup'],$x['dropoff'],$x['scheduled_at'],$x['vehicle'],$x['carpool']?'Scheduled Carpool':'Scheduled',$x['offer'],$x['fare'],$x['payment_method'],$x['payment_status'],$x['status'],$x['created_at'],$x['assigned_at'],$x['started_at'],$x['completed_at'],$x['cancelled_at']]);fclose($o);exit;}$size=max(10,min(20,(int)($_GET['page_size']??15)));$total=count($filtered);$pages=max(1,(int)ceil($total/$size));$page=max(1,min($pages,(int)($_GET['page']??1)));srj(['ok'=>true,'summary'=>$summary,'rides'=>array_slice($filtered,($page-1)*$size,$size),'pagination'=>['page'=>$page,'page_size'=>$size,'total'=>$total,'total_pages'=>$pages,'has_prev'=>$page>1,'has_next'=>$page<$pages],'collections'=>array_values(array_unique(array_column($src,'_collection')))]);}catch(Throwable$e){error_log('[Scheduled Rides] '.$e->getMessage());srj(['ok'=>false,'error'=>'Scheduled ride data could not be loaded.'],500);}

