<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php'; require_once __DIR__.'/db.php';
admin_require_auth(); header('Content-Type: application/json; charset=utf-8');
function sj(array $x,int $c=200):never{http_response_code($c);echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function clean($v){if(is_array($v)){foreach($v as $k=>$x)$v[$k]=clean($x);return $v;}return is_string($v)?trim($v):$v;}
function at($v):string{return wow_timestamp_to_string($v);}
function defaults():array{return[
 'appName'=>'Women on Wheels','supportEmail'=>'support@womenonwheels.pk','supportContact'=>'','currency'=>'PKR','timezone'=>'Asia/Karachi','dateFormat'=>'D MMM YYYY','distanceUnit'=>'km',
 'fareSettings'=>['platformCommissionPercent'=>30,'vehicles'=>['car'=>['baseFare'=>140,'perKmRate'=>38,'perMinRate'=>5,'minimumFare'=>140,'enabled'=>true],'bike'=>['baseFare'=>80,'perKmRate'=>24,'perMinRate'=>3,'minimumFare'=>80,'enabled'=>true],'scooty'=>['baseFare'=>90,'perKmRate'=>28,'perMinRate'=>3.5,'minimumFare'=>90,'enabled'=>true]],'carpool'=>['enabled'=>true,'allowedVehicles'=>['car'],'discountPercent'=>20,'minimumSavings'=>50,'maxPassengers'=>4,'allowScheduled'=>true]],
 'rideLimits'=>['maxActiveRidesPerDriver'=>1,'maxSearchMinutes'=>5,'requestExpiryMinutes'=>5,'driverLocationStaleMinutes'=>5],
 'driverApprovalSettings'=>['manualApprovalRequired'=>true,'requireCnic'=>true,'requireLicence'=>true,'requireVehicleDocs'=>true,'requireProfilePhoto'=>true,'allowOnlineBeforeApproval'=>false,'minimumRatingWarning'=>3],
 'scheduledRideSettings'=>['enabled'=>true,'maxDaysAhead'=>30,'minimumAdvanceMinutes'=>30,'assignmentStartMinutes'=>60,'allowPassengerReschedule'=>true,'rescheduleCutoffMinutes'=>60,'allowAdminReschedule'=>true,'reminderMinutes'=>60],
 'safetySettings'=>['enabled'=>true,'countdownSeconds'=>5,'adminEmergencyNotification'=>true,'sharePassengerLocation'=>true,'shareDriverLocation'=>true,'locationUpdateSeconds'=>10,'emergencyContactRequired'=>false,'autoCreateIncident'=>true,'allowFalseAlarm'=>true,'overdueWarningMinutes'=>15],
 'notificationSettings'=>['channels'=>['inApp'=>true,'mobilePush'=>false,'website'=>true,'browserPush'=>false],'admin'=>['driverApplication'=>true,'sos'=>true,'pendingPayment'=>true,'lostFound'=>true,'supportEscalation'=>true,'authAlert'=>true,'rideIssue'=>true],'passenger'=>['rideUpdates'=>true,'driverAssigned'=>true,'driverArriving'=>true,'scheduledReminder'=>true,'paymentUpdates'=>true,'lostFound'=>true,'sosResponse'=>true,'promotions'=>false],'driver'=>['rideRequest'=>true,'scheduledReminder'=>true,'passengerOffer'=>true,'earningUpdate'=>true,'verification'=>true,'lostFound'=>true,'sosResponse'=>true,'promotions'=>false]],
 'paymentSettings'=>['cash'=>['enabled'=>true,'displayName'=>'Cash','instructions'=>'Pay the driver after the ride.','confirmationRequired'=>false],'easypaisa'=>['enabled'=>true,'displayName'=>'Easypaisa','instructions'=>'Manual payment confirmation required.','confirmationRequired'=>true],'jazzcash'=>['enabled'=>true,'displayName'=>'JazzCash','instructions'=>'Manual payment confirmation required.','confirmationRequired'=>true],'nayapay'=>['enabled'=>true,'displayName'=>'NayaPay','instructions'=>'Manual payment confirmation required.','confirmationRequired'=>true]],
 'themeSettings'=>['mode'=>'light','primaryColor'=>'#8A45D4','accentColor'=>'#E458A8'],
 'platformSettings'=>['maintenanceMode'=>false,'maintenanceMessage'=>'Women on Wheels is undergoing scheduled maintenance.','blockNewBookingsOnly'=>true,'passengerAppEnabled'=>true,'passengerWebsiteEnabled'=>true,'driverAppEnabled'=>true,'driverWebsiteEnabled'=>true,'newRideBookingEnabled'=>true,'newDriverRegistrationEnabled'=>true,'newPassengerRegistrationEnabled'=>true,'announcement'=>''],
 'locationSettings'=>['serviceCity'=>'Karachi','mapProvider'=>'Mapbox','locationUpdateSeconds'=>10,'routeRefreshSeconds'=>30,'allowOutsideServiceArea'=>false]
];}
function mergeDeep(array $a,array $b):array{foreach($b as$k=>$v)$a[$k]=is_array($v)&&isset($a[$k])&&is_array($a[$k])?mergeDeep($a[$k],$v):$v;return$a;}
function validateSection(string$s,array$d):array{
 $err=[];$num=function(string$path,$v,float$min,float$max)use(&$err){if(!is_numeric($v)||(float)$v<$min||(float)$v>$max)$err[$path]="Enter a value between $min and $max.";};
 if($s==='pricing'){ $num('commission',$d['platformCommissionPercent']??null,0,50); foreach(['car','bike','scooty']as$v){$r=$d['vehicles'][$v]??[];$num("$v.baseFare",$r['baseFare']??null,0,100000);$num("$v.perKmRate",$r['perKmRate']??null,0,10000);$num("$v.perMinRate",$r['perMinRate']??null,0,10000);$num("$v.minimumFare",$r['minimumFare']??null,0,100000);if(is_numeric($r['minimumFare']??null)&&is_numeric($r['baseFare']??null)&&(float)$r['minimumFare']<(float)$r['baseFare'])$err["$v.minimumFare"]='Minimum fare cannot be lower than base fare.';}}
 if($s==='drivers'){$num('maxActiveRidesPerDriver',$d['rideLimits']['maxActiveRidesPerDriver']??null,1,5);$num('maxSearchMinutes',$d['rideLimits']['maxSearchMinutes']??null,1,60);$num('driverLocationStaleMinutes',$d['rideLimits']['driverLocationStaleMinutes']??null,1,60);}
 if($s==='safety'){$num('countdownSeconds',$d['countdownSeconds']??null,3,30);$num('locationUpdateSeconds',$d['locationUpdateSeconds']??null,5,300);}
 if($s==='rides'){$num('maxDaysAhead',$d['scheduled']['maxDaysAhead']??null,1,365);$num('minimumAdvanceMinutes',$d['scheduled']['minimumAdvanceMinutes']??null,10,10080);$num('discountPercent',$d['carpool']['discountPercent']??null,0,80);}
 if($s==='appearance'){foreach(['primaryColor','accentColor']as$k)if(!preg_match('/^#[0-9a-f]{6}$/i',(string)($d[$k]??'')))$err[$k]='Enter a valid hex color.';}
 return$err;
}
$admin=$_SESSION['admin_auth']??[];$uid=(string)($admin['uid']??$admin['id']??'');$name=(string)($admin['full_name']??'Admin');
$in=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$action=(string)($in['action']??$_GET['action']??'load');
try{
 if($action==='load'){$raw=wow_doc_data('appSettings','global')?:[];$cfg=mergeDeep(defaults(),$raw);$profile=wow_doc_data('admins',$uid)?:[];$history=[];try{$docs=wow_firestore()->collection('settingsAuditLogs')->orderBy('createdAt','DESC')->limit(50)->documents();foreach($docs as$x)if($x->exists()){$z=$x->data();$history[]=['id'=>$x->id(),'section'=>$z['section']??'System','summary'=>$z['summary']??'Settings updated','oldValue'=>$z['oldValue']??null,'newValue'=>$z['newValue']??null,'changedByName'=>$z['changedByName']??'Admin','reason'=>$z['reason']??'','createdAt'=>at($z['createdAt']??'')];}}catch(Throwable $e){error_log('[settings audit] '.$e->getMessage());}
  sj(['ok'=>true,'config'=>$cfg,'profile'=>['fullName'=>$profile['fullName']??$name,'email'=>$profile['email']??$admin['email']??'','phone'=>$profile['phone']??'','role'=>$profile['role']??$admin['role']??'admin','status'=>$profile['status']??'active','emailVerified'=>(bool)($profile['emailVerified']??true),'photoURL'=>$profile['photoURL']??$profile['profilePhotoUrl']??'','lastLogin'=>at($profile['lastLoginAt']??$profile['lastLogin']??''),'createdAt'=>at($profile['createdAt']??''),'provider'=>$profile['provider']??'password'],'version'=>(int)($raw['version']??1),'updatedAt'=>at($raw['updatedAt']??''),'history'=>$history,'capabilities'=>['mobilePush'=>false,'browserPush'=>false,'profileUpload'=>false,'activeSessions'=>false]]);}
 if(!admin_verify_csrf_token((string)($in['csrf']??'')))sj(['ok'=>false,'message'=>'Your secure session expired. Refresh and try again.'],403);
 if($action==='save'){$section=(string)($in['section']??'');$data=clean(is_array($in['data']??null)?$in['data']:[]);$clientVersion=(int)($in['version']??0);$current=wow_doc_data('appSettings','global')?:[];$version=(int)($current['version']??1);if($clientVersion!==$version)sj(['ok'=>false,'code'=>'conflict','message'=>'This configuration changed in another session. Reload before saving.'],409);$errors=validateSection($section,$data);if($errors)sj(['ok'=>false,'message'=>'Review the highlighted settings.','errors'=>$errors],422);
  $map=['general'=>['generalSettings',$data],'pricing'=>['fareSettings',$data],'drivers'=>['driverOperations',$data],'rides'=>['rideConfiguration',$data],'safety'=>['safetySettings',$data],'notifications'=>['notificationSettings',$data],'payments'=>['paymentSettings',$data],'appearance'=>['themeSettings',$data],'system'=>['platformConfiguration',$data]];if(!isset($map[$section]))sj(['ok'=>false,'message'=>'Unknown settings section.'],422);[$key,$payload]=$map[$section];
  $critical=(bool)($in['critical']??false);$reason=trim((string)($in['reason']??''));if($critical&&strlen($reason)<5)sj(['ok'=>false,'message'=>'A reason is required for critical changes.'],422);
  $write=[$key=>$payload,'version'=>$version+1,'updatedBy'=>$uid,'updatedByName'=>$name,'effectiveFrom'=>wow_now()];
  if($section==='general')$write=array_merge($write,['appName'=>$payload['appName']??'Women on Wheels','supportEmail'=>$payload['supportEmail']??'','supportContact'=>$payload['supportContact']??'','currency'=>'PKR','timezone'=>'Asia/Karachi','dateFormat'=>$payload['dateFormat']??'D MMM YYYY','distanceUnit'=>'km']);
  if($section==='pricing'){$write['fareSettings']=$payload;$write['fareSettings']['perKmCharge']=null;$write['fareSettings']['minimumFare']=null;$write['pricingVersion']=$version+1;}
  if($section==='drivers'){$write['rideLimits']=$payload['rideLimits']??[];$write['driverApprovalSettings']=$payload['approval']??[];}
  if($section==='rides'){$write['scheduledRideSettings']=$payload['scheduled']??[];$write['fareSettings']=array_merge(is_array($current['fareSettings']??null)?$current['fareSettings']:[],['carpool'=>$payload['carpool']??[]]);}
  if($section==='system'){$general=$payload['general']??[];$write['platformSettings']=$payload['platform']??[];$write['locationSettings']=$payload['location']??[];$write['appName']=$general['appName']??($current['appName']??'Women on Wheels');$write['supportEmail']=$general['supportEmail']??($current['supportEmail']??'');$write['supportContact']=$general['supportContact']??($current['supportContact']??'');$write['currency']='PKR';$write['timezone']='Asia/Karachi';$write['dateFormat']=$general['dateFormat']??($current['dateFormat']??'D MMM YYYY');$write['distanceUnit']='km';}
  $old=$current[$key]??null;wow_set_doc('appSettings','global',$write,true);$auditId=date('YmdHis').'_'.bin2hex(random_bytes(4));wow_set_doc('settingsAuditLogs',$auditId,['section'=>$section,'summary'=>ucwords($section).' settings updated','oldValue'=>$old,'newValue'=>$payload,'changedBy'=>$uid,'changedByName'=>$name,'reason'=>$reason,'version'=>$version+1],false);wow_set_doc('settingsVersions','v'.($version+1),['version'=>$version+1,'section'=>$section,'configuration'=>$payload,'changedBy'=>$uid,'changedByName'=>$name,'reason'=>$reason,'effectiveFrom'=>wow_now()],false);sj(['ok'=>true,'message'=>'Settings saved to Firebase.','version'=>$version+1,'updatedAt'=>(new DateTimeImmutable())->format(DATE_ATOM)]);}
 if($action==='profile'){$full=trim((string)($in['fullName']??''));$phone=trim((string)($in['phone']??''));if(strlen($full)<2)sj(['ok'=>false,'message'=>'Enter a valid full name.'],422);wow_set_doc('admins',$uid,['fullName'=>$full,'phone'=>$phone?:null]);$_SESSION['admin_auth']['full_name']=$full;sj(['ok'=>true,'message'=>'Admin profile updated.']);}
 sj(['ok'=>false,'message'=>'Unsupported settings action.'],400);
}catch(Throwable$e){error_log('[admin settings] '.$e->getMessage());sj(['ok'=>false,'message'=>'Settings could not be processed. Please retry.'],500);}
