<?php
declare(strict_types=1);

$adminHeaderAdmin = $_SESSION['admin_auth'] ?? [];
$adminHeaderName = trim((string)($adminHeaderAdmin['full_name'] ?? 'Admin')) ?: 'Admin';
$adminHeaderRole = strtolower((string)($adminHeaderAdmin['role'] ?? 'admin'));
$adminHeaderEmail = (string)($adminHeaderAdmin['email'] ?? '');
$adminHeaderInitials = implode('', array_map(static fn(string $part): string => strtoupper(substr($part, 0, 1)), array_slice(preg_split('/\s+/', $adminHeaderName) ?: ['A'], 0, 2)));
$adminHeaderFile = strtolower(basename((string)(parse_url((string)($_SERVER['REQUEST_URI'] ?? $_SERVER['SCRIPT_NAME'] ?? 'dashboard.php'), PHP_URL_PATH) ?: 'dashboard.php')));
$adminHeaderView = strtolower(trim((string)($_GET['view'] ?? '')));
$adminHeaderTitles = [
    'dashboard.php' => 'Dashboard', 'drivers.php' => 'Driver Verification', 'rides.php' => 'Ride Monitoring',
    'fare_insights.php' => 'Fare Insights', 'payments.php' => 'Payments', 'driver_earnings.php' => 'Driver Earnings', 'carpooling.php' => 'Carpool Management',
    'sos_monitoring.php' => 'Safety and SOS', 'auth_monitoring.php' => 'Authentication Monitoring',
    'notifications.php' => 'Notifications', 'ai_analytics.php' => 'AI Analytics', 'settings.php' => 'Settings',
    'lost_found.php' => 'Lost and Found', 'ratings_reviews.php' => 'Ratings and Reviews',
    'wow_assistant.php' => 'WOW Assistant', 'financial_reconciliation.php' => 'Financial Reconciliation',
];
$adminHeaderViewTitles = ['dashboard'=>'Dashboard','passengers'=>'Passenger Management','drivers'=>'Driver Management','ride-monitoring'=>'Ride Monitoring','fare-insights'=>'Fare Insights','carpooling'=>'Carpool Management','payments'=>'Payments','safety-sos'=>'Safety and SOS','passenger-sos'=>'Passenger SOS','auth-monitoring'=>'Authentication Monitoring','notifications'=>'Notifications','ai-analytics'=>'AI Analytics','settings'=>'Settings'];
$adminHeaderTitle = $adminHeaderFile === 'rides.php' && strtolower(trim((string)($_GET['filter'] ?? ''))) === 'scheduled'
    ? 'Scheduled Rides'
    : ($adminHeaderFile === 'dashboard.php' && isset($adminHeaderViewTitles[$adminHeaderView]) ? $adminHeaderViewTitles[$adminHeaderView] : ($adminHeaderTitles[$adminHeaderFile] ?? 'Admin Dashboard'));
$adminHeaderEsc = static fn(string $value): string => htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
?>
<header class="topbar v2-topbar admin-shared-header" id="adminSharedHeader" data-page-title="<?php echo $adminHeaderEsc($adminHeaderTitle); ?>" data-csrf="<?php echo $adminHeaderEsc(admin_csrf_token()); ?>">
    <div class="v2-top-title"><strong id="adminHeaderPageTitle"><?php echo $adminHeaderEsc($adminHeaderTitle); ?></strong><span>Women on Wheels</span></div>
    <div class="admin-global-search" role="search">
        <label class="search-wrap" for="dashboardSearch"><span class="search-icon" aria-hidden="true">&#128269;</span><input id="dashboardSearch" type="search" placeholder="Search passengers, drivers, rides..." autocomplete="off" aria-controls="dashboardSearchResults" aria-expanded="false"><button id="dashboardSearchClear" type="button" aria-label="Clear global search" hidden>&times;</button></label>
        <div class="v2-search-results" id="dashboardSearchResults" role="listbox" aria-label="Global search results" hidden></div>
    </div>
    <div class="topbar-right">
        <span class="status-pill is-connecting" id="adminLiveStatus" role="status" title="Connecting to Firebase real-time services"><span class="dot"></span><span><span class="status-text">Connecting</span><small id="adminLastSync">Waiting for sync</small></span></span>
        <div class="v2-menu-wrap"><button class="icon-btn" id="adminNotificationBell" type="button" aria-label="Admin notifications" aria-expanded="false" aria-controls="adminNotificationPanel" title="Notifications"><span class="notify-dot" id="notifyCount">0</span><span aria-hidden="true">&#128276;</span></button><div class="v2-notification-panel" id="adminNotificationPanel" hidden><div class="v2-notification-head"><div><strong>Notifications</strong><small>Real-time admin inbox</small></div><button type="button" id="adminMarkAllRead">Mark all read</button></div><div id="adminNotificationList"><div class="v2-skeleton rows"></div></div><div class="v2-notification-foot"><a href="notifications.php">View all notifications</a><button type="button" id="adminNotificationRefresh">Refresh</button></div></div></div>
        <div class="v2-menu-wrap"><button class="quick-actions" id="adminQuickActionsButton" type="button" aria-expanded="false" aria-controls="quickActionsMenu"><span>Quick Actions</span> <b aria-hidden="true">&#9662;</b></button><div class="v2-dropdown admin-quick-menu" id="quickActionsMenu" hidden>
            <p class="v2-menu-label">Operations</p><a href="drivers.php?filter=pending"><span aria-hidden="true">&#10003;</span> Pending Driver Applications</a><a href="sos_monitoring.php?filter=active"><span aria-hidden="true">!</span> Active SOS Alerts</a><a href="rides.php?filter=active"><span aria-hidden="true">&#8594;</span> Live Ride Monitoring</a><a href="payments.php?filter=pending"><span aria-hidden="true">Rs</span> Pending Payments</a><p class="v2-menu-label">Communication</p><button type="button" id="quickSendNotification"><span aria-hidden="true">&#9993;</span> Broadcast Notification</button><a href="notifications.php?compose=emergency"><span aria-hidden="true">!</span> Emergency Alert</a><a href="notifications.php?compose=promotion"><span aria-hidden="true">%</span> Promo Notification</a><a href="notifications.php?compose=announcement"><span aria-hidden="true">A</span> Support Announcement</a><p class="v2-menu-label">Management</p><a href="dashboard.php?view=passengers"><span>P</span> Passenger Management</a><a href="drivers.php"><span>D</span> Driver Management</a><a href="driver_earnings.php"><span>70</span> Driver Earnings</a><a href="ratings_reviews.php"><span>&#9733;</span> Ratings & Reviews</a><a href="lost_found.php"><span>LF</span> Lost & Found</a><a href="auth_monitoring.php"><span>AU</span> Authentication Monitoring</a><a href="ai_analytics.php"><span>AI</span> AI Analytics</a><a href="wow_assistant.php"><span>WA</span> WOW Assistant</a><a href="settings.php"><span>&#9881;</span> System Settings</a>
        </div></div>
        <div class="v2-menu-wrap"><button class="v2-profile-button" id="adminProfileButton" type="button" aria-expanded="false" aria-controls="profileMenu"><span class="avatar lg" id="adminProfileAvatar"><?php echo $adminHeaderEsc($adminHeaderInitials ?: 'A'); ?></span><span id="adminProfileName"><?php echo $adminHeaderEsc($adminHeaderName); ?></span><b aria-hidden="true">&#9662;</b></button><div class="v2-dropdown profile" id="profileMenu" hidden><div class="v2-profile-summary"><span class="avatar lg" id="adminMenuAvatar"><?php echo $adminHeaderEsc($adminHeaderInitials ?: 'A'); ?></span><div><strong id="adminMenuName"><?php echo $adminHeaderEsc($adminHeaderName); ?></strong><small id="adminMenuEmail"><?php echo $adminHeaderEsc($adminHeaderEmail); ?></small><span><b id="adminMenuRole"><?php echo $adminHeaderEsc(ucwords(str_replace('_', ' ', $adminHeaderRole))); ?></b> · <b id="adminMenuStatus">Active</b></span></div></div><div class="v2-profile-meta"><span>Last login</span><strong id="adminMenuLastLogin">Loading…</strong></div><p class="v2-menu-label">Account</p><a href="settings.php#profile">Profile & Edit Profile</a><button type="button" data-wow-change-password data-token-url="firebase_custom_token.php" data-login-url="login.php" data-logout-url="logout.php" data-logout-method="GET">Change Password</button><a href="settings.php#security">Security</a><a href="settings.php#notifications">Notification Preferences</a><a href="settings.php#appearance">Theme & Appearance</a><a href="auth_monitoring.php">Activity Log</a><span class="v2-future-item" title="Not implemented in the current authentication system">Two-Factor Authentication · Future</span><span class="v2-future-item">Language · English</span><p class="v2-menu-label">System</p><a href="settings.php">Admin Settings</a><a href="wow_assistant.php?help=admin">Help & Documentation</a><a href="logout.php" class="v2-logout-link" id="adminShellLogout">Logout</a></div></div>
    </div>
</header>
