<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';require_once __DIR__.'/db.php';admin_require_auth();
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function waj(array $v,int $c=200):never{http_response_code($c);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function wan(mixed $v):string{return strtolower(trim((string)$v));}
function wat(array $r,array $keys,string $default=''):string{foreach($keys as$key){$v=trim((string)($r[$key]??''));if($v!=='')return$v;}return$default;}
function wad(mixed $v):?DateTimeImmutable{$s=wow_timestamp_to_string($v);if($s==='')return null;try{return(new DateTimeImmutable($s))->setTimezone(new DateTimeZone('Asia/Karachi'));}catch(Throwable){return null;}}
function wasource(mixed $v):string{$s=wan($v);if(str_contains($s,'passenger')&&str_contains($s,'web'))return'passenger_website';if(str_contains($s,'passenger')&&(str_contains($s,'app')||str_contains($s,'mobile')))return'passenger_app';if(str_contains($s,'driver')&&str_contains($s,'web'))return'driver_website';if(str_contains($s,'driver')&&(str_contains($s,'app')||str_contains($s,'mobile')))return'driver_app';if(in_array($s,['website','web'],true))return'passenger_website';if(in_array($s,['app','mobile','android','ios'],true))return'passenger_app';return'unknown';}
function wasource_label(string $v):string{return match($v){'passenger_app'=>'Passenger Mobile App','passenger_website'=>'Passenger Website','driver_app'=>'Driver Mobile App','driver_website'=>'Driver Website',default=>'Source unavailable'};}
function wacat(array $r):string{$v=wan($r['category']??$r['context']??$r['intent']??'general_help');return match(true){str_contains($v,'ride')||str_contains($v,'book')=>'ride_booking',str_contains($v,'location')||str_contains($v,'track')=>'driver_location',str_contains($v,'pay')=>'payments',str_contains($v,'account')=>'account',str_contains($v,'verif')||str_contains($v,'approval')=>'verification',str_contains($v,'safe')||str_contains($v,'sos')=>'safety',str_contains($v,'lost')=>'lost_found',default=>$v?:'general_help'};}
function waexplicit(array $r):bool{$status=wan($r['status']??$r['escalationStatus']??'');$flag=($r['isEscalated']??false)===true||wan($r['isEscalated']??'')==='true'||($r['needsHumanSupport']??false)===true||wan($r['needsHumanSupport']??'')==='true';return$flag||wat($r,['escalationReason'])!==''&&in_array($status,['new','open','pending','in_review','waiting_for_user','resolved','closed'],true);}
function waoutcome(array $r,bool $escalated):string{if($escalated)return'escalated';if(wat($r,['feedback'])!=='')return'feedback';if(($r['fallbackUsed']??false)===true||in_array(wan($r['intent']??''),['unknown','fallback'],true))return'fallback';return'answered';}
function waprof(array $profiles,string $uid,string $role,array $row):array{$p=$profiles[$uid]??[];$name=wat($p,['fullName','name'],wat($row,['userName','passengerName','driverName'],'User profile unavailable'));$initials='';foreach(array_slice(preg_split('/\s+/',trim($name))?:[],0,2)as$part)$initials.=strtoupper(substr($part,0,1));return['id'=>$uid,'name'=>$name,'initials'=>$initials?:'U','role'=>$role,'email'=>wat($p,['email'],wat($row,['userEmail','passengerEmail','driverEmail']))];}
try{
 $input=json_decode((string)file_get_contents('php://input'),true);if(!is_array($input))$input=array_merge($_GET,$_POST);$action=wan($input['action']??'list');$admin=$_SESSION['admin_auth']??[];$adminId=(string)($admin['uid']??'');$adminName=wat($admin,['full_name','name'],'Admin');
 if($action!=='list'){$id=trim((string)($input['id']??''));if($id==='')waj(['ok'=>false,'message'=>'Case ID is required.'],422);if($action==='case_status'){$status=wan($input['status']??'');if(!in_array($status,['in_review','waiting_for_user','resolved','closed'],true))waj(['ok'=>false,'message'=>'Invalid case status.'],422);$reply=trim((string)($input['reply']??''));if(in_array($status,['resolved','closed'],true)&&$reply==='')waj(['ok'=>false,'message'=>'A resolution response is required.'],422);$updates=['status'=>$status,'adminResponse'=>$reply,'updatedAt'=>wow_now(),'handledBy'=>$adminId,'handledByName'=>$adminName];if($status==='resolved')$updates['resolvedAt']=wow_now();if($status==='closed')$updates['closedAt']=wow_now();wow_set_doc('supportEscalations',$id,$updates,true);$case=wow_doc_data('supportEscalations',$id)??[];$uid=wat($case,['userId','userUid']);if($uid!==''&&$reply!=='')wow_set_doc('notifications','assistant_'.$id.'_'.time(),['userId'=>$uid,'recipientId'=>$uid,'type'=>'support_response','title'=>'WOW Support Update','message'=>$reply,'relatedId'=>$id,'isRead'=>false,'createdAt'=>wow_now()],true);waj(['ok'=>true]);}waj(['ok'=>false,'message'=>'Unsupported action.'],422);}
 $profiles=[];foreach(['users','passengers','drivers']as$collection){try{foreach(admin_list_collection($collection,1000)as$p){$uid=wat($p,['uid','userId']);if($uid!=='')$profiles[$uid]=array_merge($profiles[$uid]??[],$p);}}catch(Throwable $e){error_log("WOW Assistant optional {$collection} profiles: ".$e->getMessage());}}
 $escalationDocs=[];foreach(['supportEscalations','assistantEscalations','supportTickets']as$collection){try{foreach(admin_list_recent_collection($collection,200,'createdAt')as$r){$r['_collection']=$collection;$key=wat($r,['escalationId','ticketId','uid']);if($key!==''&&!isset($escalationDocs[$key]))$escalationDocs[$key]=$r;}}catch(Throwable $e){error_log("WOW Assistant optional {$collection}: ".$e->getMessage());}}
 $conversations=[];$seen=[];foreach(['chatbotMessages','wowAssistantInteractions']as$collection){try{foreach(admin_list_recent_collection($collection,500,'createdAt')as$r){$id=wat($r,['messageId','uid']);if($id===''||isset($seen[$id]))continue;$seen[$id]=true;$uid=wat($r,['userId','userUid']);$role=wan($r['userRole']??$r['userType']??'passenger');if(!in_array($role,['passenger','driver'],true))$role='passenger';$explicit=waexplicit($r);$profile=waprof($profiles,$uid,$role,$r);$source=wasource($r['sourcePlatform']??$r['source']??$r['platform']??'');$created=wad($r['createdAt']??null);$answered=wad($r['respondedAt']??$r['responseAt']??null);$responseMs=is_numeric($r['responseTimeMs']??null)?(float)$r['responseTimeMs']:($created&&$answered?max(0,($answered->getTimestamp()-$created->getTimestamp())*1000):null);$feedback=wan($r['feedback']??$r['helpful']??'');$conversations[]=['id'=>$id,'conversation_id'=>wat($r,['conversationId','sessionId'],$uid.'-'.($created?->format('Ymd')??$id)),'user'=>$profile,'question'=>wat($r,['message','question']),'answer'=>wat($r,['botReply','response','assistantAnswer']),'category'=>wacat($r),'outcome'=>waoutcome($r,$explicit),'source'=>$source,'source_label'=>wasource_label($source),'created_at'=>$created?->format(DATE_ATOM),'response_ms'=>$responseMs,'helpful'=>in_array($feedback,['helpful','yes','true','1'],true)?true:(in_array($feedback,['unhelpful','no','false','0'],true)?false:null),'is_escalated'=>$explicit,'related_ride_id'=>wat($r,['relatedRideId','rideId'])];}}catch(Throwable $e){error_log("WOW Assistant {$collection}: ".$e->getMessage());}}
 $escalations=[];foreach($escalationDocs as$id=>$r){$uid=wat($r,['userId','userUid']);$role=wan($r['userRole']??$r['role']??'passenger');$source=wasource($r['sourcePlatform']??$r['source']??'');$created=wad($r['createdAt']??null);$escalations[]=['id'=>$id,'user'=>waprof($profiles,$uid,$role,$r),'query'=>wat($r,['question','message','query'],'Support request'),'category'=>wacat($r),'reason'=>wat($r,['escalationReason','reason'],'Human support requested'),'source'=>$source,'source_label'=>wasource_label($source),'status'=>wan($r['status']??'new')?:'new','created_at'=>$created?->format(DATE_ATOM),'conversation_id'=>wat($r,['conversationId']),'related_ride_id'=>wat($r,['relatedRideId','rideId']),'related_payment_id'=>wat($r,['relatedPaymentId','paymentId']),'related_sos_id'=>wat($r,['relatedSosId','sosId']),'admin_response'=>wat($r,['adminResponse','resolutionNotes'])];}
 usort($conversations,fn($a,$b)=>strcmp((string)$b['created_at'],(string)$a['created_at']));usort($escalations,fn($a,$b)=>strcmp((string)$b['created_at'],(string)$a['created_at']));$sessions=[];$answeredCount=0;$fallback=0;$times=[];$feedback=[];$cats=[];foreach($conversations as$r){$sessions[$r['conversation_id']]=1;$cats[$r['category']]=($cats[$r['category']]??0)+1;if($r['outcome']==='answered')$answeredCount++;if($r['outcome']==='fallback')$fallback++;if($r['response_ms']!==null)$times[]=$r['response_ms'];if($r['helpful']!==null)$feedback[]=$r['helpful'];}$open=count(array_filter($escalations,fn($r)=>!in_array($r['status'],['resolved','closed'],true)));$summary=['total_conversations'=>count($sessions),'answered_successfully'=>$answeredCount,'escalated_to_support'=>count($escalations),'open_escalations'=>$open,'average_response_ms'=>$times?round(array_sum($times)/count($times)):null,'helpful_rate'=>$feedback?round(count(array_filter($feedback))*100/count($feedback),1):null,'feedback_count'=>count($feedback),'fallback_rate'=>$conversations?round($fallback*100/count($conversations),1):null,'escalation_rate'=>$conversations?round(count($escalations)*100/count($conversations),1):null];arsort($cats);
 waj(['ok'=>true,'summary'=>$summary,'conversations'=>$conversations,'escalations'=>$escalations,'analytics'=>['categories'=>$cats,'outcomes'=>['answered'=>$answeredCount,'fallback'=>$fallback,'escalated'=>count($escalations),'feedback'=>count($feedback)],'topics'=>array_slice($cats,0,6,true)],'collections'=>['conversations'=>['chatbotMessages','wowAssistantInteractions'],'escalations'=>array_values(array_unique(array_map(fn($r)=>$r['_collection']??'supportEscalations',$escalationDocs)))]]);
}catch(Throwable $e){error_log('WOW Assistant admin: '.$e->getMessage());waj(['ok'=>false,'message'=>'WOW Assistant data could not be loaded.'],500);}
