<?php declare(strict_types=1);require_once __DIR__.'/auth.php';admin_require_auth(); ?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#9a48ff"><title>WOW Assistant - Women on Wheels</title><link rel="stylesheet" href="dashboard.css?v=20260802"><link rel="stylesheet" href="dashboard_v2.css?v=20260802"><link rel="stylesheet" href="wow_assistant.css?v=20260803"></head>
<body class="wa-page"><div class="admin-layout"><?php require __DIR__.'/shared_sidebar.php'; ?><main class="content"><?php require __DIR__.'/shared_header.php'; ?>
<section class="wa-head"><div><h1>WOW Assistant</h1><p>Monitor chatbot performance, manage knowledge answers and handle genuinely escalated support queries.</p></div><button class="wa-btn secondary" id="waExport">&#8681; Export Data</button></section>
<nav class="wa-tabs" aria-label="Assistant sections"><button class="active" data-tab="overview">Overview</button><button data-tab="escalations">Escalated Queries <span id="waOpenBadge">0</span></button><button data-tab="conversations">Conversation History</button><button data-tab="knowledge">Knowledge Base</button></nav>
<section class="wa-kpis" id="waKpis" aria-label="Assistant summary"></section>
<section class="wa-toolbar" id="waToolbar"><label class="search"><span>&#128269;</span><input id="waSearch" placeholder="Search by user, question, answer or category"><button id="waClear" hidden>&times;</button></label><label>User Role<select id="waRole"><option value="all">All Users</option><option value="passenger">Passenger</option><option value="driver">Driver</option></select></label><label>Category<select id="waCategory"><option value="all">All Categories</option></select></label><label>Outcome<select id="waOutcome"><option value="all">All Outcomes</option><option value="answered">Answered</option><option value="fallback">Fallback Used</option><option value="escalated">Escalated</option><option value="feedback">Feedback Received</option></select></label><label>Source<select id="waSource"><option value="all">All Platforms</option><option value="passenger_app">Passenger Mobile App</option><option value="passenger_website">Passenger Website</option><option value="driver_app">Driver Mobile App</option><option value="driver_website">Driver Website</option><option value="unknown">Unknown Source</option></select></label><label>Date<select id="waDate"><option value="7d">Last 7 Days</option><option value="30d" selected>Last 30 Days</option><option value="all">All Time</option></select></label><button class="wa-btn secondary" id="waRefresh">&#8635; Refresh</button></section>
<div class="wa-error" id="waError" hidden><strong>WOW Assistant data could not be loaded.</strong><button class="wa-btn secondary" data-retry>Retry</button></div>
<section class="wa-view active" data-view="overview"><div class="wa-grid"><article class="wa-panel"><header><h2>Queries by Category</h2><p>Real conversation classifications</p></header><div id="waCategories" class="wa-bars"></div></article><article class="wa-panel"><header><h2>Conversation Outcomes</h2><p>Answered, fallback and escalated</p></header><div id="waOutcomes" class="wa-bars"></div></article><article class="wa-panel"><header><h2>Top Asked Topics</h2><p>Current filtered period</p></header><div id="waTopics" class="wa-list"></div></article><article class="wa-panel"><header><h2>Recent Important Activity</h2><p>Genuine support escalations only</p></header><div id="waRecent" class="wa-list"></div></article></div></section>
<section class="wa-view" data-view="escalations"><article class="wa-panel"><header><div><h2>Escalated Queries</h2><p>Only cases explicitly requiring human support</p></div></header><div class="wa-table"><table><thead><tr><th>User</th><th>Query</th><th>Category</th><th>Reason</th><th>Source</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody id="waEscalationBody"></tbody></table></div></article></section>
<section class="wa-view" data-view="conversations"><article class="wa-panel"><header><div><h2>Conversation History</h2><p>Normal messages are review-only and never receive Resolve controls</p></div></header><div class="wa-table"><table><thead><tr><th>User</th><th>Question</th><th>Assistant Answer</th><th>Category</th><th>Outcome</th><th>Source</th><th>Time</th><th>Actions</th></tr></thead><tbody id="waConversationBody"></tbody></table></div><div class="wa-pager"><button class="wa-btn secondary" id="waPrev">Previous</button><span id="waPage">Page 1</span><button class="wa-btn secondary" id="waNext">Next</button></div></article></section>
<section class="wa-view" data-view="knowledge"><article class="wa-panel"><header><div><h2>Knowledge Base</h2><p>Active answers are used by the connected passenger and driver chatbot API</p></div><button class="wa-btn primary" id="waNewAnswer">+ New Answer</button></header><div id="waKnowledge" class="wa-knowledge"></div></article></section>
<div class="wa-modal-backdrop" id="waCaseModal" hidden><section class="wa-modal" role="dialog" aria-modal="true" aria-labelledby="waCaseTitle"><button class="wa-close" data-close>&times;</button><header><h2 id="waCaseTitle">Support Case</h2><div id="waCaseBadges"></div></header><div id="waCaseContent"></div><label>Admin response<textarea id="waCaseReply" maxlength="1200" placeholder="Write a clear response for the user"></textarea></label><div class="wa-modal-actions" id="waCaseActions"></div></section></div>
<div class="wa-modal-backdrop" id="waConversationModal" hidden><section class="wa-modal" role="dialog" aria-modal="true"><button class="wa-close" data-close>&times;</button><header><h2>Conversation Details</h2></header><div id="waConversationDetail"></div><div class="wa-modal-actions"><button class="wa-btn secondary" data-close>Close</button></div></section></div>
<div class="wa-modal-backdrop" id="waKbModal" hidden><form class="wa-modal" id="waKbForm"><button class="wa-close" type="button" data-close>&times;</button><header><h2>Knowledge Answer</h2><p>Published entries affect every chatbot using the central API.</p></header><input type="hidden" id="waKbId"><div class="wa-form-grid"><label>Question or Intent<input id="waKbIntent" required></label><label>Category<input id="waKbCategory" required></label><label>Applicable User Role<select id="waKbRole"><option value="all">All Users</option><option value="passenger">Passenger</option><option value="driver">Driver</option></select></label><label>Source Platform<select id="waKbPlatform"><option value="all">All Platforms</option><option value="passenger_app">Passenger Mobile App</option><option value="passenger_website">Passenger Website</option><option value="driver_app">Driver Mobile App</option><option value="driver_website">Driver Website</option></select></label><label>Priority<input id="waKbPriority" type="number" min="0" max="100" value="50"></label><label>Status<select id="waKbStatus"><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></label></div><label>Alternative Phrases<textarea id="waKbPhrases" placeholder="Comma-separated English or Roman Urdu phrases"></textarea></label><label>Answer<textarea id="waKbAnswer" required></textarea></label><div class="wa-modal-actions"><button type="button" class="wa-btn secondary" data-close>Cancel</button><button class="wa-btn primary" type="submit">Save Answer</button></div></form></div>
<div class="wa-toast" id="waToast" hidden></div>
</main></div><script src="admin_realtime.js?v=20260802"></script><script src="wow_assistant.js?v=20260803-fault-tolerant1"></script></body></html>
