<?php
declare(strict_types=1);
require_once __DIR__.'/sos_common.php';require_once __DIR__.'/carpool_service.php';require_once __DIR__.'/driver_documents.php';
$in=array_merge($_GET,$_POST,sos_input());$user=resolve_user_context($conn,$in);$bearerUid=wow_firebase_uid_from_bearer();if(!$user['ok']&&$bearerUid!==''){$passenger=wow_doc_data('passengers',$bearerUid);$driver=$passenger?null:wow_doc_data('drivers',$bearerUid);$profile=$passenger??$driver??[];$user=['ok'=>(bool)$profile,'role'=>$driver?'driver':'passenger','uid'=>$bearerUid,'user_id'=>$bearerUid,'raw_user_id'=>$bearerUid,'email'=>(string)($profile['email']??'')];}if(!$user['ok'])sos_json(['ok'=>false,'error'=>'authentication_required'],401);$action=strtolower(trim((string)($in['action']??'')));
try{
 if($action==='create'){$rideId=trim((string)($in['ride_id']??''));$ride=wow_doc_data('rides',$rideId);if(!$ride||$user['role']!=='passenger'||(string)($ride['passengerId']??'')!==$user['uid'])sos_json(['ok'=>false,'error'=>'ride_not_owned'],403);if(empty($ride['isCarpool'])||strtolower((string)($ride['vehicleType']??''))!=='car')sos_json(['ok'=>false,'error'=>'carpool_requires_car'],422);$result=cp_create_booking_and_match($rideId,$user['uid'],$ride,$in);sos_json(['ok'=>true]+$result);}
 if($action==='assign_driver'){$rideId=trim((string)($in['ride_id']??''));$ride=wow_doc_data('rides',$rideId);if(!$ride||$user['role']!=='passenger'||(string)($ride['passengerId']??'')!==$user['uid'])sos_json(['ok'=>false,'error'=>'ride_not_owned'],403);$groupId=(string)($ride['carpoolRideId']??'');$group=$groupId!==''?wow_doc_data('carpoolRides',$groupId):null;$driverId=(string)($ride['assignedDriverId']??$ride['driverId']??'');if(!$group||$driverId==='')sos_json(['ok'=>false,'error'=>'assignment_not_ready'],409);$existing=(string)($group['driverId']??'');if($existing!==''&&$existing!==$driverId)sos_json(['ok'=>false,'error'=>'carpool_already_assigned'],409);wow_set_doc('carpoolRides',$groupId,['driverId'=>$driverId,'vehicleId'=>(string)($ride['vehicleId']??$ride['driverVehicleNumber']??''),'driverName'=>(string)($ride['driverName']??''),'status'=>'driver_assigned','assignmentStatus'=>'assigned','matchingLocked'=>true,'assignedAt'=>wow_now(),'updatedAt'=>wow_now()],true);foreach((array)($group['passengerBookingIds']??[]) as $id){wow_set_doc('carpoolBookings',(string)$id,['driverId'=>$driverId,'bookingStatus'=>'driver_assigned','updatedAt'=>wow_now()],true);$linked=wow_doc_data('carpoolBookings',(string)$id);$linkedRide=(string)($linked['legacyRideId']??'');if($linkedRide!=='')wow_set_doc('rides',$linkedRide,['assignedDriverId'=>$driverId,'driverId'=>$driverId,'driverUid'=>$driverId,'driverName'=>(string)($ride['driverName']??''),'driverPhone'=>(string)($ride['driverPhone']??''),'driverProfileImage'=>(string)($ride['driverProfileImage']??''),'driverVehicleType'=>(string)($ride['driverVehicleType']??''),'driverVehicleNumber'=>(string)($ride['driverVehicleNumber']??''),'vehicleNumber'=>(string)($ride['vehicleNumber']??''),'status'=>'driver_assigned','requestStatus'=>'matched','carpoolRideId'=>$groupId,'updatedAt'=>wow_now()],true);}cp_log($groupId,'driver_assigned','',(string)($ride['driverName']??'Driver').' assigned');sos_json(['ok'=>true,'carpoolRideId'=>$groupId]);}
 $bookingId=trim((string)($in['booking_id']??''));$booking=$bookingId!==''?wow_doc_data('carpoolBookings',$bookingId):null;if(!$booking)sos_json(['ok'=>false,'error'=>'booking_not_found'],404);$groupId=(string)$booking['carpoolRideId'];$group=wow_doc_data('carpoolRides',$groupId);if(!$group)sos_json(['ok'=>false,'error'=>'carpool_not_found'],404);
 $isPassenger=$user['role']==='passenger'&&(string)$booking['passengerId']===$user['uid'];$isDriver=$user['role']==='driver'&&(string)($group['driverId']??'')===$user['uid'];if(!$isPassenger&&!$isDriver)sos_json(['ok'=>false,'error'=>'not_authorized'],403);
 if($action==='passenger_cancel'&&$isPassenger){$reason=trim((string)($in['reason']??'Passenger cancelled'));if(in_array((string)$booking['boardingStatus'],['boarded','onboard'],true))sos_json(['ok'=>false,'error'=>'contact_support_after_boarding'],422);wow_set_doc('carpoolBookings',$bookingId,['bookingStatus'=>'cancelled','cancellationStatus'=>'cancelled','cancellationReason'=>$reason,'cancelledAt'=>wow_now(),'updatedAt'=>wow_now()],true);$linkedRide=(string)($booking['legacyRideId']??$bookingId);if($linkedRide!=='')wow_set_doc('rides',$linkedRide,['status'=>'cancelled','requestStatus'=>'closed','cancelledBy'=>'passenger','carpoolStatus'=>'cancelled','cancelledAt'=>wow_now(),'updatedAt'=>wow_now()],true);cp_recalculate_group($groupId,$group,$bookingId);cp_log($groupId,'passenger_cancelled',$bookingId,$reason);sos_json(['ok'=>true]);}
 if($action==='driver_cancel'&&$isDriver){$reason=trim((string)($in['reason']??'Driver cancelled'));wow_set_doc('carpoolRides',$groupId,['driverId'=>null,'vehicleId'=>null,'status'=>'searching_driver','assignmentStatus'=>'searching','matchingLocked'=>false,'driverCancellationReason'=>$reason,'driverCancelledAt'=>wow_now()],true);foreach((array)$group['passengerBookingIds'] as $id)wow_set_doc('carpoolBookings',(string)$id,['bookingStatus'=>'searching_driver'],true);cp_log($groupId,'driver_cancelled','',$reason);sos_json(['ok'=>true]);}
 if($action==='booking_status'&&$isDriver){$status=strtolower(trim((string)($in['status']??'')));$allowed=['arrived','boarded','segment_started','dropped_off','no_show'];if(!in_array($status,$allowed,true))sos_json(['ok'=>false,'error'=>'invalid_status'],422);$updates=['bookingStatus'=>$status];if($status==='arrived')$updates+=['pickupStatus'=>'arrived','arrivedAt'=>wow_now(),'waitStartedAt'=>wow_now()];if($status==='boarded')$updates+=['boardingStatus'=>'boarded','boardedAt'=>wow_now()];if($status==='segment_started')$updates+=['boardingStatus'=>'onboard','segmentStartedAt'=>wow_now()];if($status==='dropped_off')$updates+=['dropoffStatus'=>'completed','bookingStatus'=>'completed','completedAt'=>wow_now()];if($status==='no_show')$updates+=['pickupStatus'=>'no_show','boardingStatus'=>'no_show','cancellationStatus'=>'no_show','noShowAt'=>wow_now()];wow_set_doc('carpoolBookings',$bookingId,$updates,true);if(in_array($status,['dropped_off','no_show'],true))cp_recalculate_group($groupId,$group,$status==='no_show'?$bookingId:'');cp_log($groupId,'booking_'.$status,$bookingId,'Passenger '.str_replace('_',' ',$status));sos_json(['ok'=>true]);}
 sos_json(['ok'=>false,'error'=>'unsupported_action'],422);
}catch(Throwable $e){error_log('Carpool action: '.$e->getMessage());sos_json(['ok'=>false,'error'=>'carpool_operation_failed','message'=>$e->getMessage()],500);}

function cp_log(string $groupId,string $type,string $bookingId,string $message):void{$r=wow_firestore()->collection('carpoolRides')->document($groupId)->collection('activityLog')->newDocument();$r->set(['type'=>$type,'bookingId'=>$bookingId,'message'=>$message,'createdAt'=>wow_now()]);}
function cp_recalculate_group(string $groupId,array $group,string $exclude=''):void{$bookings=[];foreach((array)$group['passengerBookingIds'] as $id){if((string)$id===$exclude)continue;$b=wow_doc_data('carpoolBookings',(string)$id);if($b&&!in_array((string)($b['cancellationStatus']??''),['cancelled','no_show'],true))$bookings[]=$b;}$stops=cp_optimized_stops($bookings);$seats=array_sum(array_map(static fn($b)=>(int)$b['seatsRequired'],$bookings));$totalFare=array_sum(array_map(static fn($b)=>(float)$b['individualFare'],$bookings));$capacity=(int)($group['totalSeats']??$group['vehicleCapacity']??4);$allCompleted=$bookings&&count(array_filter($bookings,static fn($b)=>in_array((string)($b['bookingStatus']??''),['completed','paid'],true)))===count($bookings);$status=!$bookings?'cancelled':($allCompleted?'completed':(string)($group['status']??'active'));wow_set_doc('carpoolRides',$groupId,['passengerIds'=>array_values(array_unique(array_column($bookings,'passengerId'))),'passengerBookingIds'=>array_column($bookings,'bookingId'),'totalPassengers'=>count($bookings),'totalSeats'=>$capacity,'bookedSeats'=>$seats,'totalSeatsUsed'=>$seats,'availableSeats'=>max(0,$capacity-$seats),'optimizedStops'=>$stops,'totalFare'=>$totalFare,'pendingPaymentAmount'=>$totalFare-(float)($group['completedPaymentAmount']??0),'status'=>$status,'rideStatus'=>$status,'updatedAt'=>wow_now()],true);foreach($stops as $s){$field=$s['type']==='pickup'?'pickupOrder':'dropoffOrder';wow_set_doc('carpoolBookings',(string)$s['passengerBookingId'],[$field=>$s['order']],true);}}
