<?php
declare(strict_types=1);

function cp_num(array $v, string $key, float $fallback = 0): float { return is_numeric($v[$key] ?? null) ? (float)$v[$key] : $fallback; }
function cp_distance(float $aLat,float $aLng,float $bLat,float $bLng):float{$r=6371;$dLat=deg2rad($bLat-$aLat);$dLng=deg2rad($bLng-$aLng);$x=sin($dLat/2)**2+cos(deg2rad($aLat))*cos(deg2rad($bLat))*sin($dLng/2)**2;return $r*2*atan2(sqrt($x),sqrt(max(0,1-$x)));}
function cp_bearing(float $aLat,float $aLng,float $bLat,float $bLng):float{$y=sin(deg2rad($bLng-$aLng))*cos(deg2rad($bLat));$x=cos(deg2rad($aLat))*sin(deg2rad($bLat))-sin(deg2rad($aLat))*cos(deg2rad($bLat))*cos(deg2rad($bLng-$aLng));return fmod(rad2deg(atan2($y,$x))+360,360);}
function cp_angle(float $a,float $b):float{$v=abs($a-$b);return min($v,360-$v);}
function cp_time_ms($v):int{if($v instanceof \Google\Cloud\Core\Timestamp)return $v->get()->getTimestamp()*1000;if($v instanceof DateTimeInterface)return $v->getTimestamp()*1000;$t=strtotime((string)$v);return $t?$t*1000:0;}
function cp_compatibility(array $group,array $booking):array{
 $base=$group['routeAnchor']??[];$pickup=cp_distance(cp_num($base,'pickupLat'),cp_num($base,'pickupLng'),cp_num($booking,'pickupLat'),cp_num($booking,'pickupLng'));
 $destination=cp_distance(cp_num($base,'dropLat'),cp_num($base,'dropLng'),cp_num($booking,'dropLat'),cp_num($booking,'dropLng'));
 $b1=cp_bearing(cp_num($base,'pickupLat'),cp_num($base,'pickupLng'),cp_num($base,'dropLat'),cp_num($base,'dropLng'));$b2=cp_bearing(cp_num($booking,'pickupLat'),cp_num($booking,'pickupLng'),cp_num($booking,'dropLat'),cp_num($booking,'dropLng'));$angle=cp_angle($b1,$b2);
 $timeA=cp_time_ms($group['scheduledDateTime']??$group['createdAt']??'');$timeB=cp_time_ms($booking['scheduledDateTime']??$booking['createdAt']??'');$timeDiff=abs($timeA-$timeB)/60000;
 $direct=max(.1,cp_num($base,'distanceKm',cp_distance(cp_num($base,'pickupLat'),cp_num($base,'pickupLng'),cp_num($base,'dropLat'),cp_num($base,'dropLng'))));$detour=$pickup+$destination;$detourPct=($detour/$direct)*100;$extra=round($detour/0.45);
 $score=max(0,100-($pickup*12)-($destination*5)-($angle*.9)-($timeDiff*.35)-($detourPct*.25));
 return ['compatible'=>$pickup<=3.5&&$destination<=7&&$angle<=45&&$timeDiff<=30&&$detourPct<=35&&$extra<=20,'routeSimilarity'=>round(max(0,100-$angle*1.8),1),'pickupDistanceDifference'=>round($pickup,2),'destinationDirectionSimilarity'=>round(max(0,100-$angle*2),1),'estimatedDetour'=>round($detour,2),'estimatedAdditionalTime'=>$extra,'matchScore'=>round($score,1),'timeDifferenceMinutes'=>round($timeDiff,1)];
}
function cp_optimized_stops(array $bookings):array{
 $pending=[];foreach($bookings as $b){$id=(string)$b['bookingId'];$pending[]=['stopId'=>$id.'-pickup','passengerBookingId'=>$id,'type'=>'pickup','lat'=>(float)$b['pickupLat'],'lng'=>(float)$b['pickupLng'],'label'=>(string)$b['pickup'],'status'=>'pending'];$pending[]=['stopId'=>$id.'-dropoff','passengerBookingId'=>$id,'type'=>'dropoff','lat'=>(float)$b['dropLat'],'lng'=>(float)$b['dropLng'],'label'=>(string)$b['destination'],'status'=>'pending'];}
 $result=[];$picked=[];$current=$pending[0]??null;while($pending){$allowed=array_values(array_filter($pending,static fn($s)=>$s['type']==='pickup'||isset($picked[$s['passengerBookingId']])));if(!$allowed)$allowed=$pending;$best=null;$bestD=INF;foreach($allowed as $s){$d=$current?cp_distance((float)$current['lat'],(float)$current['lng'],(float)$s['lat'],(float)$s['lng']):0;if($d<$bestD){$best=$s;$bestD=$d;}}$best['order']=count($result)+1;$result[]=$best;if($best['type']==='pickup')$picked[$best['passengerBookingId']]=true;$pending=array_values(array_filter($pending,static fn($s)=>$s['stopId']!==$best['stopId']));$current=$best;}
 return $result;
}
function cp_create_booking_and_match(string $rideId,string $passengerUid,array $ride,array $input):array{
 $db=wow_firestore();$mobile=((string)($ride['source']??''))==='mobile';$bookingRef=$mobile?$db->collection('carpoolBookings')->document($rideId):$db->collection('carpoolBookings')->newDocument();$bookingId=$bookingRef->id();$existing=$bookingRef->snapshot();if($existing->exists()){$data=$existing->data();return ['carpoolRideId'=>(string)($data['carpoolRideId']??''),'bookingId'=>$bookingId,'matchStatus'=>(string)($data['bookingStatus']??'active'),'metrics'=>null];}$seats=max(1,min(3,(int)($input['seats_required']??$input['passengers']??1)));$private=(float)$ride['estimatedFare'];$shared=round((float)($input['shared_fare']??$ride['fare']??$private*.7),2);$scheduled=$ride['scheduledAt']??wow_now();
 $booking=['bookingId'=>$bookingId,'legacyRideId'=>$rideId,'passengerId'=>$passengerUid,'carpoolRideId'=>null,'pickup'=>(string)($ride['pickup']??$ride['pickupAddress']??''),'destination'=>(string)($ride['dropoff']??$ride['dropoffAddress']??$ride['destinationAddress']??''),'pickupLat'=>$ride['pickupLat'],'pickupLng'=>$ride['pickupLng'],'dropLat'=>$ride['dropLat'],'dropLng'=>$ride['dropLng'],'pickupOrder'=>1,'dropoffOrder'=>2,'seatsRequired'=>$seats,'individualFare'=>$shared,'originalPrivateFare'=>$private,'carpoolDiscount'=>round($private-$shared,2),'savings'=>round($private-$shared,2),'additionalRouteAdjustment'=>0,'cancellationAdjustment'=>0,'bookingStatus'=>'searching_match','pickupStatus'=>'pending','boardingStatus'=>'not_boarded','dropoffStatus'=>'pending','paymentStatus'=>'pending','cancellationStatus'=>'active','pickupNotes'=>trim((string)($input['pickup_notes']??'')),'scheduledDateTime'=>$scheduled,'isVerifiedPassenger'=>true,'createdAt'=>wow_now(),'updatedAt'=>wow_now()];
 $chosen=null;$metrics=null;foreach(wow_list_collection('carpoolRides',500) as $g){if(!in_array(strtolower((string)($g['status']??'')),['searching_match','searching_driver','scheduled'],true)||!empty($g['matchingLocked']))continue;if((int)($g['availableSeats']??0)<$seats)continue;$m=cp_compatibility($g,$booking);if($m['compatible']&&(!$metrics||$m['matchScore']>$metrics['matchScore'])){$chosen=$g;$metrics=$m;}}
 if(!$chosen){$groupRef=$db->collection('carpoolRides')->newDocument();$groupId=$groupRef->id();$booking['carpoolRideId']=$groupId;$stops=cp_optimized_stops([$booking]);$group=['carpoolRideId'=>$groupId,'tripId'=>$groupId,'rideType'=>'carpool','driverId'=>null,'vehicleId'=>null,'passengerIds'=>[$passengerUid],'passengerBookingIds'=>[$bookingId],'totalPassengers'=>1,'totalSeats'=>4,'bookedSeats'=>$seats,'totalSeatsUsed'=>$seats,'vehicleCapacity'=>4,'availableSeats'=>4-$seats,'optimizedStops'=>$stops,'sharedRoute'=>[],'totalDistance'=>(float)($ride['distanceKm']??0),'totalEstimatedTime'=>(float)($ride['durationMin']??$ride['durationMinutes']??0),'totalFare'=>$shared,'driverTotalEarning'=>0,'driverEarning'=>0,'platformCommission'=>0,'settlementStatus'=>'pending_payments','completedPaymentAmount'=>0,'pendingPaymentAmount'=>$shared,'status'=>isset($ride['scheduledAt'])?'scheduled':'searching_match','rideStatus'=>isset($ride['scheduledAt'])?'scheduled':'matching','matchStatus'=>'searching','matchingLocked'=>false,'matchingCutoffAt'=>isset($ride['scheduledAt'])?$ride['assignmentStartsAt']??$ride['scheduledAt']:new \Google\Cloud\Core\Timestamp((new DateTimeImmutable())->modify('+10 minutes')),'maxAllowedDetour'=>35,'scheduledDateTime'=>$scheduled,'routeAnchor'=>['pickupLat'=>$ride['pickupLat'],'pickupLng'=>$ride['pickupLng'],'dropLat'=>$ride['dropLat'],'dropLng'=>$ride['dropLng'],'distanceKm'=>(float)($ride['distanceKm']??0)],'createdAt'=>wow_now(),'startedAt'=>null,'completedAt'=>null,'updatedAt'=>wow_now()];$groupRef->set($group);$chosen=$group;
 }else{$groupId=(string)$chosen['uid'];$booking['carpoolRideId']=$groupId;$all=[];foreach((array)$chosen['passengerBookingIds'] as $id){$b=wow_doc_data('carpoolBookings',(string)$id);if($b&&($b['cancellationStatus']??'active')==='active')$all[]=$b;}$all[]=$booking;$stops=cp_optimized_stops($all);$ids=array_values(array_unique(array_merge((array)$chosen['passengerBookingIds'],[$bookingId])));$passengerIds=array_values(array_unique(array_merge((array)($chosen['passengerIds']??[]),[$passengerUid])));$used=(int)$chosen['totalSeatsUsed']+$seats;$totalFare=(float)($chosen['totalFare']??$chosen['pendingPaymentAmount']??0)+$shared;wow_set_doc('carpoolRides',$groupId,['passengerIds'=>$passengerIds,'passengerBookingIds'=>$ids,'totalPassengers'=>count($ids),'totalSeats'=>(int)($chosen['totalSeats']??$chosen['vehicleCapacity']??4),'bookedSeats'=>$used,'totalSeatsUsed'=>$used,'availableSeats'=>max(0,(int)$chosen['vehicleCapacity']-$used),'optimizedStops'=>$stops,'totalFare'=>$totalFare,'driverTotalEarning'=>(float)($chosen['driverTotalEarning']??0),'pendingPaymentAmount'=>(float)($chosen['pendingPaymentAmount']??0)+$shared,'matchStatus'=>'matched','status'=>isset($ride['scheduledAt'])?'scheduled':'searching_driver','rideStatus'=>isset($ride['scheduledAt'])?'scheduled':'confirmed','lastMatchMetrics'=>$metrics,'updatedAt'=>wow_now()],true);foreach($stops as $s){$field=$s['type']==='pickup'?'pickupOrder':'dropoffOrder';wow_set_doc('carpoolBookings',(string)$s['passengerBookingId'],[$field=>$s['order']],true);}}
 $bookingRef->set($booking);wow_set_doc('rides',$rideId,['isCarpool'=>true,'carpoolRideId'=>$booking['carpoolRideId'],'carpoolBookingId'=>$bookingId,'seatsRequired'=>$seats,'carpoolStatus'=>'active','matchStatus'=>$chosen&&$metrics?'matched':'searching','sharedFare'=>$shared,'originalFare'=>$private,'estimatedSavings'=>round($private-$shared,2),'maxAllowedDetour'=>35,'estimatedAdditionalTime'=>$metrics['estimatedAdditionalTime']??8,'updatedAt'=>wow_now()],true);
 $log=$db->collection('carpoolRides')->document((string)$booking['carpoolRideId'])->collection('activityLog')->newDocument();$log->set(['type'=>$metrics?'passenger_matched':'carpool_created','bookingId'=>$bookingId,'metrics'=>$metrics,'message'=>$metrics?'Compatible passenger added':'Carpool request created','createdAt'=>wow_now()]);
 return ['carpoolRideId'=>$booking['carpoolRideId'],'bookingId'=>$bookingId,'matchStatus'=>$metrics?'matched':'searching','metrics'=>$metrics];
}
